# English translations for Open-Capture
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the project
# FIRST AUTHOR <nathan.cheval@edissyum.com>, 2021.
msgid ""
msgstr ""
"Project-Id-Version:  0.1\n"
"Report-Msgid-Bugs-To: nathan.cheval@edissyum.com\n"
"POT-Creation-Date: 2024-08-20 15:40+0200\n"
"PO-Revision-Date: 2019-09-02 17:48+0200\n"
"Last-Translator: Nathan CHEVAL <nathan.cheval@edissyum.com>\n"
"Language: en\n"
"Language-Team: en <nathan.cheval@edissyum.com>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.16.0\n"

#: custom/edissyum/src/backend/process_queue_splitter.py:238
#: custom/edissyum/src/backend/process_queue_verifier.py:186
msgid "FILE_UPLOADED_WORKFLOW"
msgstr "File uploaded successfully with workflow"

#: src/backend/functions.py:43 src/backend/functions.py:55
#: src/backend/functions.py:60
msgid "NO_DATA_OR_DATA_MISSING"
msgstr "No data or data missing"

#: src/backend/functions.py:52
msgid "JSON_ERROR"
msgstr "JSON construction error"

#: src/backend/functions.py:55
msgid "IS_NOT"
msgstr "is not instance of type"

#: src/backend/functions.py:115 src/backend/functions.py:133
#: src/backend/functions.py:143
msgid "UPLOAD_ERRROR"
msgstr "Error while uploading file(s)"

#: src/backend/functions.py:116
msgid "FORMATS_FILE_NOT_FOUND"
msgstr "The file containing allowed extensions and MIME types is not found"

#: src/backend/functions.py:134
msgid "FILE_EXTENSION_NOT_ALLOWED"
msgstr "File extension is not allowed"

#: src/backend/functions.py:144
msgid "FILE_MIME_NOT_ALLOWED"
msgstr "File MIME type doesn't match to extension"

#: src/backend/scripting_functions.py:81
msgid "WORFKLOW_NOT_FOUND"
msgstr "Workflow doesn't exists"

#: src/backend/controllers/verifier.py:545
#: src/backend/controllers/workflow.py:228
#: src/backend/controllers/workflow.py:297
#: src/backend/controllers/workflow.py:488 src/backend/process/main.py:64
#: src/backend/process/main_ia.py:58 src/backend/scripting_functions.py:132
msgid "SCRIPT_CONTAINS_NOT_ALLOWED_CODE"
msgstr "Script contains not allowed code :"

#: src/backend/splitter_exports.py:100
msgid "OUTPUT_NOT_FOUND"
msgstr "Output not found"

#: src/backend/models/outputs.py:101 src/backend/splitter_exports.py:135
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr "Output type doesn't exists"

#: src/backend/splitter_exports.py:186 src/backend/splitter_exports.py:329
msgid "EXPORT_PDF_ERROR"
msgstr "Error while exporting PDF"

#: src/backend/splitter_exports.py:263
msgid "EXPORT_VERIFIER_ERROR"
msgstr "Error while exporting to verifier module"

#: src/backend/splitter_exports.py:274
msgid "EXPORT_OPENCAPTUREFORMEM_ERROR"
msgstr "Error while exporting to Open-Capture For MEM"

#: src/backend/splitter_exports.py:298 src/backend/splitter_exports.py:352
msgid "EXPORT_XML_ERROR"
msgstr "Error while exporting XML"

#: src/backend/splitter_exports.py:372
msgid "CHECK_FOLDER_ERROR"
msgstr "Check folder error"

#: src/backend/splitter_exports.py:373
msgid "FOLDER_DOES_NOT_EXIST"
msgstr "Folder does not exist"

#: src/backend/splitter_exports.py:393
msgid "OPENADS_ADD_DOC_ERROR"
msgstr "OpenADS add document error"

#: src/backend/verifier_exports.py:157 src/backend/verifier_exports.py:160
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Destination folder for XML doesn't exists"

#: src/backend/verifier_exports.py:360 src/backend/verifier_exports.py:363
#: src/backend/verifier_exports.py:443 src/backend/verifier_exports.py:446
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Destination folder for PDF doesn't exists"

#: src/backend/verifier_exports.py:505 src/backend/verifier_exports.py:539
#: src/backend/verifier_exports.py:545
msgid "EXPORT_COOG_ERROR"
msgstr "Error while exporting to COOG"

#: src/backend/verifier_exports.py:506
msgid "COOG_JSON_ERROR"
msgstr "The JSON content is incorrect"

#: src/backend/verifier_exports.py:551
msgid "COOG_WS_INFO_WRONG"
msgstr "Web service informations are wrong"

#: src/backend/verifier_exports.py:557
msgid "COOG_WS_INFO_EMPTY"
msgstr "Web service informations are empty"

#: src/backend/verifier_exports.py:733 src/backend/verifier_exports.py:739
#: src/backend/verifier_exports.py:745
msgid "EXPORT_MEM_ERROR"
msgstr "Error during MEM Courrier export"

#: src/backend/verifier_exports.py:740
msgid "PDF_FILE_NOT_FOUND"
msgstr "PDF file not found"

#: src/backend/verifier_exports.py:751
msgid "MEM_WS_INFO_WRONG"
msgstr "MEM Courrier informations are wrong"

#: src/backend/verifier_exports.py:757
msgid "MEM_WS_INFO_EMPTY"
msgstr "MEM Courrier informations are empty"

#: src/backend/classes/COOGWebServices.py:44
#: src/backend/classes/MEMWebServices.py:40
msgid "HOST_NOT_FOUND"
msgstr "Host not found"

#: src/backend/classes/OpenCaptureForMEMWebServices.py:44
msgid "HOST_NOT_FOUND_OR_OTHER_ERROR"
msgstr "Host not found or other error"

#: src/backend/classes/SMTP.py:227
msgid "RESET_PASSWORD"
msgstr "Reset password"

#: src/backend/classes/SMTP.py:229
msgid "FORGOT_EMAIL_HEADER"
msgstr ""
"Hello,<br/><br/>You requested to reset your Open-Capture account "
"password.<br/><br/>To change it, please click on the link below :<br/>"

#: src/backend/classes/SMTP.py:229
msgid "CLICK_HERE"
msgstr "Click here"

#: src/backend/classes/SMTP.py:229
msgid "FORGOT_EMAIL_FOOTER"
msgstr ""
"<br/><br/>If you did not requested this action, you can ignore this "
"email.<br/><br/>"

#: src/backend/classes/SMTP.py:246
msgid "SMTP_TEST_SEND"
msgstr "Test email sent"

#: src/backend/classes/SMTP.py:247
msgid "SMTP_TEST_SEND_BODY"
msgstr "This is a test email sent by Open-Capture"

#: src/backend/controllers/accounts.py:70 src/backend/models/accounts.py:61
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr "Error retrieving supplier"

#: src/backend/controllers/accounts.py:83
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr "Error retrieving address"

#: src/backend/controllers/accounts.py:110
#: src/backend/controllers/accounts.py:232
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr "Error updating supplier positions"

#: src/backend/controllers/accounts.py:137
#: src/backend/controllers/accounts.py:263
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr "Error update supplier pages"

#: src/backend/controllers/accounts.py:190
msgid "SUPPLIER_UPDATED"
msgstr "Supplier updated&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:195
#: src/backend/controllers/accounts.py:201
msgid "UPDATE_SUPPLIER_ERROR"
msgstr "Error updating supplier"

#: src/backend/controllers/accounts.py:291
#: src/backend/controllers/accounts.py:297
#: src/backend/controllers/accounts.py:322
#: src/backend/controllers/accounts.py:329 src/backend/models/accounts.py:127
msgid "UPDATE_ADDRESS_ERROR"
msgstr "Error updating address"

#: src/backend/controllers/accounts.py:353 src/backend/models/accounts.py:147
msgid "CREATE_ADDRESS_ERROR"
msgstr "Error creating address"

#: src/backend/controllers/accounts.py:390
msgid "SUPPLIER_CREATED"
msgstr "Supplier created&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:398
#: src/backend/controllers/accounts.py:404 src/backend/models/accounts.py:167
msgid "CREATE_SUPPLIER_ERROR"
msgstr "Error creating supplier"

#: src/backend/controllers/accounts.py:405
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A supplier already exists with this vat number"

#: src/backend/controllers/accounts.py:442 src/backend/controllers/user.py:248
#: src/backend/controllers/user.py:278 src/backend/models/accounts.py:231
#: src/backend/models/accounts.py:254 src/backend/models/accounts.py:273
#: src/backend/models/user.py:215
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr "Error retrieving customer"

#: src/backend/controllers/accounts.py:486
msgid "CUSTOMER_UPDATED"
msgstr "Customer updated&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:491
#: src/backend/controllers/accounts.py:497
#: src/backend/controllers/splitter.py:333 src/backend/models/accounts.py:295
msgid "UPDATE_CUSTOMER_ERROR"
msgstr "Error updating customer"

#: src/backend/controllers/accounts.py:525
msgid "CUSTOMER_CREATED"
msgstr "Customer created&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:533
#: src/backend/controllers/accounts.py:539 src/backend/models/accounts.py:315
msgid "CREATE_CUSTOMER_ERROR"
msgstr "Error creating customer"

#: src/backend/controllers/accounts.py:540
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A customer already exists with this vat number"

#: src/backend/controllers/accounts.py:556
msgid "CUSTOMER_DELETED"
msgstr "Customer deleted&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:561
#: src/backend/controllers/accounts.py:567 src/backend/models/accounts.py:337
msgid "DELETE_CUSTOMER_ERROR"
msgstr "Error deleting customer"

#: src/backend/controllers/accounts.py:584
msgid "SUPPLIER_DELETED"
msgstr "Supplier deleted&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:589
#: src/backend/controllers/accounts.py:595 src/backend/models/accounts.py:189
msgid "DELETE_SUPPLIER_ERROR"
msgstr "Error deleting supplier"

#: src/backend/controllers/artificial_intelligence.py:74
#: src/backend/controllers/artificial_intelligence.py:376
#: src/backend/controllers/artificial_intelligence.py:402
msgid "GET_IA_MODEL_BY_ID_ERROR"
msgstr "Error retrieving ai model"

#: src/backend/controllers/artificial_intelligence.py:99
msgid "CREATE_IA_MODEL_ERROR"
msgstr "Error creating ai models"

#: src/backend/controllers/artificial_intelligence.py:121
msgid "DELETE_AI_MODEL"
msgstr "Delete AI model&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:160
msgid "UPDATE_AI_MODEL"
msgstr "Update AI model&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:165
msgid "UPDATE_IA_MODEL_ERROR"
msgstr "Error updating ai model"

#: src/backend/controllers/artificial_intelligence.py:228
msgid "CREATE_AI_MODEL"
msgstr "Create AI model&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:377
#: src/backend/controllers/artificial_intelligence.py:403
#: src/backend/models/artificial_intelligence.py:59
msgid "IA_MODEL_DOESNT_EXISTS"
msgstr "AI model doesn't exists"

#: src/backend/controllers/artificial_intelligence.py:439
msgid "RENAME_AI_MODEL_ERROR"
msgstr "Error renaming ai models"

#: src/backend/controllers/artificial_intelligence.py:440
msgid "FILE_DOESNT_EXISTS"
msgstr "The AI file doesn't exists"

#: src/backend/controllers/attachments.py:90
msgid "UPLOAD_ATTACHMENTS_VERIFIER"
msgstr "Uploading attachment in document n°<strong>%(document_id)s</strong>"

#: src/backend/controllers/attachments.py:92
msgid "UPLOAD_ATTACHMENTS_SPLITTER"
msgstr "Uploading attachment in batch n°<strong>%(batch_id)s</strong>"

#: src/backend/controllers/attachments.py:147
msgid "DELETE_ATTACHMENTS"
msgstr "Deleting attachment n°<strong>%(attachment_id)s</strong>"

#: src/backend/controllers/auth.py:57 src/backend/controllers/auth.py:86
msgid "PGSQL_ERROR"
msgstr "Error while connecting to database"

#: src/backend/controllers/auth.py:81 src/backend/controllers/auth.py:374
#: src/backend/controllers/auth.py:389 src/backend/controllers/auth.py:416
#: src/backend/controllers/auth.py:597 src/backend/controllers/auth.py:608
#: src/backend/controllers/auth.py:618
msgid "LOGIN_ERROR"
msgstr "Login error"

#: src/backend/controllers/auth.py:82 src/backend/models/auth.py:43
msgid "BAD_AUTHENTICATION"
msgstr "Bad authentication informations"

#: src/backend/controllers/auth.py:143 src/backend/controllers/auth.py:175
#: src/backend/controllers/auth.py:227 src/backend/controllers/auth.py:281
#: src/backend/controllers/auth.py:310 src/backend/controllers/auth.py:324
#: src/backend/controllers/auth.py:440 src/backend/controllers/auth.py:483
#: src/backend/controllers/auth.py:498
msgid "SESSION_EXPIRED"
msgstr "Your session has expired, please log in again"

#: src/backend/controllers/auth.py:144 src/backend/controllers/auth.py:176
#: src/backend/controllers/auth.py:441 src/backend/controllers/auth.py:483
#: src/backend/controllers/auth.py:499 src/backend/controllers/auth.py:509
#: src/backend/controllers/auth.py:521 src/backend/controllers/auth.py:566
msgid "JWT_ERROR"
msgstr "Authentification by token error"

#: src/backend/controllers/auth.py:311
msgid "RESET_JWT_ERROR"
msgstr "Reset JWT error"

#: src/backend/controllers/auth.py:325
msgid "UNIQUE_URL_JWT_ERROR"
msgstr "Unique URL JWT error"

#: src/backend/controllers/auth.py:367
msgid "LOGOUT"
msgstr "Log out"

#: src/backend/controllers/auth.py:390
msgid "USER_WEBSERVICE"
msgstr "The user couldn't connect to the application (webservice user)"

#: src/backend/controllers/auth.py:411 src/backend/controllers/auth.py:463
msgid "LOGIN"
msgstr "User log in"

#: src/backend/controllers/auth.py:509
msgid "AUTHORIZATION_HEADER_INCORRECT"
msgstr "The authorization header is incorrect (missing 'Bearer' or 'Basic')"

#: src/backend/controllers/auth.py:521
msgid "ACCOUNT_ALREADY_LOGGED"
msgstr ""
"Your account is already log in another machine. Only one connection is "
"allowed per account"

#: src/backend/controllers/auth.py:553
msgid "FIRSTNAME"
msgstr "Firstname"

#: src/backend/controllers/auth.py:568 src/backend/controllers/auth.py:573
msgid "REST_ERROR"
msgstr "Authentification by webservice user error"

#: src/backend/controllers/auth.py:569
msgid "USER_DO_NOT_EXISTS"
msgstr "User does not exist"

#: src/backend/controllers/auth.py:573
msgid "PASSWORD_INCORRECT"
msgstr "Incorrect password"

#: src/backend/controllers/auth.py:578
msgid "AUTH_ERROR"
msgstr "Authentification error"

#: src/backend/controllers/auth.py:578
msgid "VALID_TOKEN_OR_USER_WS_MANDATORY"
msgstr "Valid token or webservice user is mandatory"

#: src/backend/controllers/auth.py:609
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr "Several authentication methods are enabled"

#: src/backend/controllers/auth.py:633
msgid "LDAP_ERROR"
msgstr "LDAP error"

#: src/backend/controllers/auth.py:634 src/backend/models/auth.py:136
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr "No LDAP configurations found"

#: src/backend/controllers/auth.py:645 src/backend/models/auth.py:161
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr "Error while updating login method"

#: src/backend/controllers/auth.py:660
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr "Error while loading login methods"

#: src/backend/controllers/auth.py:672
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr "Error while disabling login methods"

#: src/backend/controllers/auth.py:684
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr "Error while enabling login methods"

#: src/backend/controllers/auth.py:714 src/backend/controllers/auth.py:905
#: src/backend/controllers/auth.py:961 src/backend/controllers/auth.py:976
#: src/backend/controllers/auth.py:984 src/backend/controllers/auth.py:990
msgid "LDAP_CONNECTION_ERROR"
msgstr "Unable to connect to LDAP server"

#: src/backend/controllers/auth.py:715
msgid "LOGIN_LDAP_ERROR"
msgstr "Error while logging using LDAP"

#: src/backend/controllers/auth.py:893 src/backend/controllers/auth.py:899
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr "Synchronization's informations are incorrect"

#: src/backend/controllers/auth.py:895 src/backend/controllers/auth.py:901
#: src/backend/controllers/auth.py:907 src/backend/controllers/auth.py:913
#: src/backend/controllers/auth.py:919
msgid "LDAP_SYNCHRO_ERROR"
msgstr "Error while syncing LDAP"

#: src/backend/controllers/auth.py:911 src/backend/controllers/auth.py:917
#: src/backend/controllers/auth.py:996
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr "Missing informations"

#: src/backend/controllers/auth.py:959 src/backend/controllers/auth.py:974
#: src/backend/controllers/auth.py:982
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr "Incorrect information"

#: src/backend/controllers/auth.py:994
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr "One or more information are missing to establish the connection"

#: src/backend/controllers/config.py:64
msgid "LANGUAGE_CHANGED"
msgstr "Change language to&nbsp;<strong>%(lang)s</strong>"

#: src/backend/controllers/config.py:79
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr "Error while retrieving configuration"

#: src/backend/controllers/config.py:109
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr "Error while retrieving configurations"

#: src/backend/controllers/config.py:140
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr "Error while retrieving docservers"

#: src/backend/controllers/config.py:178
msgid "RETRIEVE_REGEX_ERRORS"
msgstr "Error while retrieving regex"

#: src/backend/controllers/config.py:190 src/backend/controllers/config.py:219
#: src/backend/controllers/config.py:231 src/backend/controllers/config.py:258
#: src/backend/models/config.py:199 src/backend/models/config.py:223
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr "Error while updating configuration"

#: src/backend/controllers/config.py:191 src/backend/controllers/config.py:232
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr "The value of token expiration could'nt be 0 or less"

#: src/backend/controllers/config.py:214 src/backend/controllers/config.py:253
msgid "UPDATE_CONFIGURATION"
msgstr "Configuration updated&nbsp;<strong>%(config)s</strong>"

#: src/backend/controllers/config.py:281
msgid "UPDATE_REGEX"
msgstr "Regex updated&nbsp;<strong>%(regex)s</strong>"

#: src/backend/controllers/config.py:286 src/backend/models/config.py:245
msgid "UPDATE_REGEX_ERROR"
msgstr "Error while updating REGEX"

#: src/backend/controllers/config.py:308
msgid "UPDATE_DOCSERVER"
msgstr "Docserver updated&nbsp;<strong>%(docserver)s</strong>"

#: src/backend/controllers/config.py:313 src/backend/models/config.py:271
msgid "UPDATE_DOCSERVER_ERROR"
msgstr "Error while updating docserver"

#: src/backend/controllers/config.py:355 src/backend/controllers/config.py:371
#: src/backend/controllers/config.py:376
msgid "ERROR_UPDATING_IMAGE"
msgstr "Error while updating login image"

#: src/backend/controllers/config.py:356 src/backend/controllers/config.py:372
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr "Custom image path is not writeable"

#: src/backend/controllers/config.py:366
msgid "UPDATE_LOGIN_IMAGE"
msgstr "Login image updated"

#: src/backend/controllers/config.py:377 src/backend/controllers/user.py:544
msgid "CUSTOM_NOT_PRESENT"
msgstr "No custom is present"

#: src/backend/controllers/custom_fields.py:33
#: src/backend/controllers/custom_fields.py:49
#: src/backend/controllers/custom_fields.py:62
msgid "CUSTOM_FIELDS_ERROR"
msgstr "Custom fields error"

#: src/backend/controllers/custom_fields.py:75
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr "Error while deleting custom field"

#: src/backend/controllers/doctypes.py:39
#: src/backend/controllers/doctypes.py:81 src/backend/models/doctypes.py:131
#: src/backend/models/doctypes.py:134
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr "Error while updating default doctype"

#: src/backend/controllers/doctypes.py:45 src/backend/models/doctypes.py:51
msgid "ADD_DOCTYPE_ERROR"
msgstr "Error while adding doctype"

#: src/backend/controllers/doctypes.py:65
#: src/backend/controllers/doctypes.py:101
#: src/backend/controllers/doctypes.py:114
#: src/backend/controllers/doctypes.py:166
#: src/backend/controllers/doctypes.py:197
#: src/backend/controllers/doctypes.py:236
#: src/backend/controllers/doctypes.py:264
#: src/backend/controllers/doctypes.py:287
#: src/backend/controllers/doctypes.py:315
msgid "DOCTYPE_ERROR"
msgstr "Doctype error"

#: src/backend/controllers/doctypes.py:133
msgid "BUNDLESEPARATOR"
msgstr "SEPARATEUR DE LOT / BUNDLE SEPARATOR"

#: src/backend/controllers/doctypes.py:140
msgid "DOCUMENTSEPARATOR"
msgstr "SEPARATEUR DE DOCUMENT / DOCUMENT SEPARATOR"

#: src/backend/controllers/doctypes.py:159
msgid "DOCTYPESEPARATOR"
msgstr "SEPARATEUR AVEC TYPE DE DOCUMENT / SEPARATOR WITH DOCUMENT TYPE"

#: src/backend/controllers/forms.py:72 src/backend/controllers/forms.py:106
#: src/backend/controllers/forms.py:229
msgid "FORMS_ERROR"
msgstr "Forms error"

#: src/backend/controllers/forms.py:101
msgid "CREATE_FORM"
msgstr "Form created&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:121 src/backend/controllers/forms.py:170
#: src/backend/models/forms.py:66
msgid "GET_FORM_BY_ID_ERROR"
msgstr "Error retrieving form"

#: src/backend/controllers/forms.py:153
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr "Error retrieving form fields"

#: src/backend/controllers/forms.py:218
msgid "UPDATE_FORM"
msgstr "Form updated&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:223 src/backend/controllers/forms.py:381
#: src/backend/controllers/forms.py:387
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr "Error updating form fields"

#: src/backend/controllers/forms.py:245
msgid "DELETE_FORM"
msgstr "Form deleted&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:250 src/backend/controllers/forms.py:256
msgid "DELETE_FORM_ERROR"
msgstr "Error deleting form"

#: src/backend/controllers/forms.py:265 src/backend/controllers/outputs.py:66
#: src/backend/controllers/positions_masks.py:150
#: src/backend/controllers/workflow.py:120
msgid "COPY_OF"
msgstr "Copy of"

#: src/backend/controllers/forms.py:286
msgid "DUPLICATE_FORM"
msgstr "Form duplicated&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:291 src/backend/controllers/forms.py:297
msgid "DUPLICATE_FORM_ERROR"
msgstr "Error duplicating form"

#: src/backend/controllers/forms.py:313
msgid "DISABLE_FORM"
msgstr "Form disabled&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:318 src/backend/controllers/forms.py:324
msgid "DISABLE_FORM_ERROR"
msgstr "Error disabling form"

#: src/backend/controllers/forms.py:340
msgid "ENABLE_FORM"
msgstr "Form enabled&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:345 src/backend/controllers/forms.py:351
msgid "ENABLE_FORM_ERROR"
msgstr "Error enabling form"

#: src/backend/controllers/forms.py:367
msgid "GET_FORMS_FIELDS_ERROR"
msgstr "Error while retrieving form fields"

#: src/backend/controllers/history.py:31
msgid "ADD_HISTORY_ERROR"
msgstr "Error while adding new history"

#: src/backend/controllers/mailcollect.py:38
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr "Error while retrieving MailCollect processes"

#: src/backend/controllers/mailcollect.py:53
msgid "UPDATE_MAILCOLLECT_PROCESS"
msgstr "MailCollect process updated&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:61
msgid "UPDATE_PROCESS_ERROR"
msgstr "Error while updating MailCollect process"

#: src/backend/controllers/mailcollect.py:76
msgid "CREATE_MAILCOLLECT_PROCESS"
msgstr "MailCollect process created&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:82
msgid "CREATE_PROCESS_ERROR"
msgstr "Error while creating MailCollect process"

#: src/backend/controllers/mailcollect.py:98
msgid "DELETE_MAILCOLLECT_PROCESS"
msgstr "MailCollect process deleted&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:103
#: src/backend/controllers/mailcollect.py:109
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while deleting MailCollect process"

#: src/backend/controllers/mailcollect.py:125
msgid "ENABLE_MAILCOLLECT_PROCESS"
msgstr "MailCollect process enabled&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:130
#: src/backend/controllers/mailcollect.py:136
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while enabling MailCollect process"

#: src/backend/controllers/mailcollect.py:152
msgid "DISABLE_MAILCOLLECT_PROCESS"
msgstr "MailCollect process disabled&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:157
#: src/backend/controllers/mailcollect.py:163
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while disabling MailCollect process"

#: src/backend/controllers/mailcollect.py:184
#: src/backend/controllers/mailcollect.py:194
#: src/backend/controllers/mailcollect.py:206
#: src/backend/controllers/mailcollect.py:216
msgid "MAILCOLLECT_ERROR"
msgstr "MailCollect error"

#: src/backend/controllers/outputs.py:75
msgid "DUPLICATE_OUTPUT"
msgstr "Output duplicated&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:80 src/backend/controllers/outputs.py:86
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr "Error while duplicate ouput"

#: src/backend/controllers/outputs.py:115
#: src/backend/controllers/outputs.py:144
#: src/backend/controllers/outputs.py:150
msgid "UPDATE_OUTPUT_ERROR"
msgstr "Error while updating output"

#: src/backend/controllers/outputs.py:116
msgid "NOT_ALLOWED_OUTPUT_PATH"
msgstr "Output path is not allowed"

#: src/backend/controllers/outputs.py:139
msgid "UPDATE_OUTPUT"
msgstr "Output updated&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:173
msgid "CREATE_OUTPUT"
msgstr "Output created&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:181
msgid "CREATE_OUTPUT_ERROR"
msgstr "Error while creating output"

#: src/backend/controllers/outputs.py:194
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr "Error while retrieving output"

#: src/backend/controllers/outputs.py:207
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr "Error while retrieving output type"

#: src/backend/controllers/outputs.py:223
msgid "DELETE_OUTPUT"
msgstr "Output deleted&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:228
#: src/backend/controllers/outputs.py:234
msgid "DELETE_OUTPUT_ERROR"
msgstr "Error while deleting output"

#: src/backend/controllers/outputs.py:262
#: src/backend/controllers/outputs.py:271
#: src/backend/controllers/outputs.py:278
msgid "OUTPUT_FOLDER_CREATION_ERROR"
msgstr "Error while creating output folder"

#: src/backend/controllers/outputs.py:263
#: src/backend/controllers/workflow.py:65
msgid "FOLDER_NOT_ALLOWED_ERROR"
msgstr "Capture path not allowed"

#: src/backend/controllers/outputs.py:272
#: src/backend/controllers/workflow.py:74
#: src/backend/controllers/workflow.py:398
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr "Cannot create folder because of permission issue"

#: src/backend/controllers/outputs.py:279
#: src/backend/controllers/workflow.py:81
msgid "CAN_NOT_ACCESS_FOLDER_PERMISSION_ERROR"
msgstr "Cannot create folder because of permission issue"

#: src/backend/controllers/positions_masks.py:43
#: src/backend/controllers/positions_masks.py:66
#: src/backend/controllers/positions_masks.py:108
#: src/backend/controllers/positions_masks.py:114
msgid "POSITION_MASKS_ERROR"
msgstr "Position masks error"

#: src/backend/controllers/positions_masks.py:57
msgid "CREATE_POSITIONS_MASK"
msgstr "Position mask created&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:81
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/controllers/positions_masks.py:103
msgid "UPDATE_POSITIONS_MASK"
msgstr "Position mask updated&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:130
#: src/backend/controllers/positions_masks.py:216
msgid "DELETE_POSITIONS_MASK"
msgstr "Position mask deleted&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:135
#: src/backend/controllers/positions_masks.py:141
msgid "DELETE_POSITION_MASK_ERROR"
msgstr "Error while deleting positions mask"

#: src/backend/controllers/positions_masks.py:167
#: src/backend/controllers/positions_masks.py:173
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr "Error while duplicating positions mask"

#: src/backend/controllers/positions_masks.py:189
msgid "DISABLE_POSITIONS_MASK"
msgstr "Position mask disabled&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:194
#: src/backend/controllers/positions_masks.py:200
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr "Error while disabling positions mask"

#: src/backend/controllers/positions_masks.py:221
#: src/backend/controllers/positions_masks.py:227
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr "Error while enabling positions mask"

#: src/backend/controllers/positions_masks.py:250
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updating positions mask positions"

#: src/backend/controllers/positions_masks.py:273
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updateing positions mask pages"

#: src/backend/controllers/positions_masks.py:291
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask positions"

#: src/backend/controllers/positions_masks.py:309
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask pages"

#: src/backend/controllers/privileges.py:38
#: src/backend/controllers/privileges.py:66
#: src/backend/controllers/privileges.py:94
msgid "GET_PRIVILEGES_ERROR"
msgstr "Error while retrieving privileges"

#: src/backend/controllers/roles.py:39 src/backend/controllers/user.py:122
#: src/backend/controllers/user.py:138 src/backend/controllers/user.py:219
#: src/backend/models/user.py:145 src/backend/models/user.py:192
msgid "GET_USER_BY_ID_ERROR"
msgstr "Error while retrieving user"

#: src/backend/controllers/roles.py:49 src/backend/controllers/roles.py:169
msgid "GET_ROLE_BY_ID_ERROR"
msgstr "Error while retrieving role"

#: src/backend/controllers/roles.py:88
msgid "UPDATE_ROLE"
msgstr "Role updated&nbsp;<strong>{{ role }}</strong>"

#: src/backend/controllers/roles.py:93 src/backend/controllers/roles.py:99
#: src/backend/controllers/roles.py:150 src/backend/controllers/roles.py:156
#: src/backend/models/roles.py:85
msgid "UPDATE_ROLE_ERROR"
msgstr "Error while trying to update role"

#: src/backend/controllers/roles.py:121
msgid "CREATE_ROLE"
msgstr "New role created&nbsp;<strong>%(role)s</strong>"

#: src/backend/controllers/roles.py:130 src/backend/models/roles.py:105
msgid "CREATE_ROLE_ERROR"
msgstr "Error while creating role"

#: src/backend/controllers/roles.py:185
msgid "DELETE_ROLE"
msgstr "Role&nbsp;<strong>%(role)s</strong> deleted"

#: src/backend/controllers/roles.py:190 src/backend/controllers/roles.py:196
msgid "DELETE_ROLE_ERROR"
msgstr "Error while deleting role"

#: src/backend/controllers/roles.py:210 src/backend/controllers/roles.py:216
msgid "DISABLE_ROLE_ERROR"
msgstr "Error while disabling role"

#: src/backend/controllers/roles.py:230 src/backend/controllers/roles.py:236
msgid "ENABLE_ROLE_ERROR"
msgstr "Error while enabling role"

#: src/backend/controllers/smtp.py:47
msgid "SMTP_TEST_SEND_EMAIL_ERROR"
msgstr "Error while sending test email"

#: src/backend/controllers/smtp.py:53
msgid "SMTP_TEST_CONNECTION_ERROR"
msgstr "Error while connecting to SMTP"

#: src/backend/controllers/splitter.py:117
msgid "LOAD_METADATA_ERROR"
msgstr "Error while loading metada"

#: src/backend/controllers/splitter.py:177
#: src/backend/controllers/verifier.py:148
msgid "AT"
msgstr "at"

#: src/backend/controllers/splitter.py:209
msgid "FORM_UNDEFINED"
msgstr "Form undefined"

#: src/backend/controllers/splitter.py:212
msgid "CUSTOMER_UNDEFINED"
msgstr "Customer undefined"

#: src/backend/controllers/splitter.py:272
#: src/backend/controllers/splitter.py:303
#: src/backend/controllers/splitter.py:323
msgid "BATCH_NOT_FOUND"
msgstr "Batch not found"

#: src/backend/controllers/splitter.py:273
#: src/backend/controllers/splitter.py:304
#: src/backend/controllers/splitter.py:324
msgid "BATCH_ID_NOT_FOUND"
msgstr "Batch %(id)s not found"

#: src/backend/controllers/splitter.py:287
msgid "DELETE_BATCH_SUCCESS"
msgstr "Deletion of batch n°<strong>%(batch_id)s</strong>"

#: src/backend/controllers/splitter.py:292
#: src/backend/controllers/splitter.py:313
#: src/backend/controllers/verifier.py:865
msgid "UPDATE_STATUS_ERROR"
msgstr "Error while updating status"

#: src/backend/controllers/splitter.py:371
#: src/backend/controllers/splitter.py:384
#: src/backend/controllers/verifier.py:444
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr "Error while removing lock"

#: src/backend/controllers/splitter.py:486
msgid "ADD_DOCUMENT_ERROR"
msgstr "Error while adding document"

#: src/backend/controllers/splitter.py:511
msgid "UPDATE_BATCH_ERROR"
msgstr "Error while updating batch"

#: src/backend/controllers/splitter.py:525
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr "Error while updating document"

#: src/backend/controllers/splitter.py:538
#: src/backend/controllers/verifier.py:418
#: src/backend/controllers/verifier.py:424
msgid "UPDATE_DOCUMENT_ERROR"
msgstr "Error while updating document"

#: src/backend/controllers/splitter.py:556
#: src/backend/controllers/splitter.py:571
#: src/backend/controllers/splitter.py:586
msgid "UPDATE_PAGES_ERROR"
msgstr "Error while updating pages"

#: src/backend/controllers/splitter.py:600
msgid "CMIS_CONNECTION_ERROR"
msgstr "Error while connecting to CMIS"

#: src/backend/controllers/splitter.py:613
msgid "OPENADS_CONNECTION_ERROR"
msgstr "OpenADS connection error"

#: src/backend/controllers/splitter.py:712
#: src/backend/controllers/verifier.py:844 src/backend/models/splitter.py:618
#: src/backend/models/verifier.py:197
msgid "GET_TOTALS_ERROR"
msgstr "Error while retrievings totals"

#: src/backend/controllers/splitter.py:811
msgid "GET_BATCH_OUTPUTS_ERROR"
msgstr "Error while retrieving output"

#: src/backend/controllers/status.py:31
msgid "RETRIEVES_STATUS_ERROR"
msgstr "Error while retrieving status"

#: src/backend/controllers/user.py:73
msgid "CREATE_USER"
msgstr "User created&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:78
msgid "CREATE_USER_ERROR"
msgstr "Error while creating user"

#: src/backend/controllers/user.py:155
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr "Error while retrieving user"

#: src/backend/controllers/user.py:181
msgid "USER_FORGOT_SUCCESS"
msgstr ""
"Password reset email sent successfully for "
"user&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:186
msgid "SEND_EMAIL_FORGOT_PASSWORD_ERROR"
msgstr "Error sending password reset email"

#: src/backend/controllers/user.py:209
msgid "USER_RESET_PASSWORD_SUCCESS"
msgstr "User&nbsp;<strong>%(user)s</strong> reset password successfully"

#: src/backend/controllers/user.py:213 src/backend/controllers/user.py:218
msgid "RESET_PASSWORD_ERROR"
msgstr "Erreur while reseting password"

#: src/backend/controllers/user.py:214
msgid "RESET_TOKEN_MISMATCH"
msgstr "Reset token mismatch. Maybe the token is expired"

#: src/backend/controllers/user.py:299
msgid "UPDATE_PROFILE"
msgstr "Update profile"

#: src/backend/controllers/user.py:300
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr "The old password do not match"

#: src/backend/controllers/user.py:306
msgid "UPDATE_USER"
msgstr "Update user"

#: src/backend/controllers/user.py:307
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr "Password do not match"

#: src/backend/controllers/user.py:337
msgid "USER_UPDATED"
msgstr "User updated&nbsp<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:342 src/backend/controllers/user.py:348
#: src/backend/models/user.py:260 src/backend/models/user.py:326
msgid "UPDATE_USER_ERROR"
msgstr "Error while updating user"

#: src/backend/controllers/user.py:364
msgid "DELETE_USER"
msgstr "User deleted&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:372 src/backend/controllers/user.py:378
msgid "DELETE_USER_ERROR"
msgstr "Error while deleting user"

#: src/backend/controllers/user.py:394
msgid "DISABLE_USER"
msgstr "User disabled&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:402 src/backend/controllers/user.py:408
msgid "DISABLE_USER_ERROR"
msgstr "Error while disabling user"

#: src/backend/controllers/user.py:424
msgid "ENABLE_USER"
msgstr "User enabled&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:432 src/backend/controllers/user.py:438
msgid "ENABLE_USER_ERROR"
msgstr "Error while enabling user"

#: src/backend/controllers/user.py:455 src/backend/controllers/user.py:461
#: src/backend/models/user.py:282
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr "Error while updating user customers"

#: src/backend/controllers/user.py:476 src/backend/controllers/user.py:483
#: src/backend/models/user.py:304
msgid "UPDATE_FORMS_USER_ERROR"
msgstr "Error while updating user forms"

#: src/backend/controllers/user.py:526
msgid "USER_EXPORT_ERROR"
msgstr "Error while exporting users"

#: src/backend/controllers/user.py:543 src/backend/controllers/user.py:560
msgid "ERROR_IMPORTING_USER"
msgstr "Error importing users"

#: src/backend/controllers/user.py:576
msgid "GET_DEFAULT_ROUTE_ERROR"
msgstr "Error while retrieving default route"

#: src/backend/controllers/verifier.py:53
msgid "UPLOAD_DOCUMENTS_ERROR"
msgstr "Error while uploading documents"

#: src/backend/controllers/verifier.py:112 src/backend/models/splitter.py:222
#: src/backend/models/verifier.py:40
msgid "GET_DOCUMENT_BY_ID_ERROR"
msgstr "Error while retrieving document"

#: src/backend/controllers/verifier.py:129 src/backend/models/verifier.py:64
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR"
msgstr "Error while retrieving document using token"

#: src/backend/controllers/verifier.py:130
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR_MESSAGE"
msgstr "No document found with this token"

#: src/backend/controllers/verifier.py:256
#: src/backend/controllers/verifier.py:358
msgid "UPDATE_DOCUMENT_POSITIONS_ERROR"
msgstr "Error while updating document positions"

#: src/backend/controllers/verifier.py:279
#: src/backend/controllers/verifier.py:376
msgid "UPDATE_DOCUMENT_PAGES_ERROR"
msgstr "Error while updating document pages"

#: src/backend/controllers/verifier.py:302
#: src/backend/controllers/verifier.py:320
msgid "UPDATE_DOCUMENT_DATA_ERROR"
msgstr "Error while updating document datas"

#: src/backend/controllers/verifier.py:392
msgid "DELETE_DOCUMENT_SUCCESS"
msgstr "Deletion of document n°<strong>%(document_id)s</strong>"

#: src/backend/controllers/verifier.py:397
#: src/backend/controllers/verifier.py:403
msgid "DELETE_DOCUMENT_ERROR"
msgstr "Error while deleting document"

#: src/backend/controllers/verifier.py:737
#: src/backend/controllers/verifier.py:740
#: src/backend/controllers/verifier.py:757
#: src/backend/controllers/verifier.py:783
#: src/backend/controllers/verifier.py:784
msgid "API_INSEE_ERROR_CONNEXION"
msgstr "Error while connecting to INSEE API"

#: src/backend/controllers/verifier.py:814
msgid "VAT_NOT_VALID"
msgstr "VAT number not valid"

#: src/backend/controllers/verifier.py:821
#: src/backend/controllers/verifier.py:822
msgid "VAT_API_ERROR"
msgstr "API for VAT number unreachable"

#: src/backend/controllers/verifier.py:855
msgid "DOCUMENT_NOT_FOUND"
msgstr "document not found"

#: src/backend/controllers/verifier.py:856
msgid "DOCUMENT_ID_NOT_FOUND"
msgstr "document %(id)s not found"

#: src/backend/controllers/verifier.py:910
msgid "NO_FORM"
msgstr "No form associated"

#: src/backend/controllers/verifier.py:921
msgid "FORM_NOT_FOUND"
msgstr "Form does not exist"

#: src/backend/controllers/workflow.py:64
#: src/backend/controllers/workflow.py:73
#: src/backend/controllers/workflow.py:80
msgid "WORKFLOW_FOLDER_CREATION_ERROR"
msgstr "Error while creating input folder"

#: src/backend/controllers/workflow.py:95
msgid "GET_WORKFLOW_BY_ID_ERROR"
msgstr "Error while retrieving workflow"

#: src/backend/controllers/workflow.py:108
msgid "GET_WORKFLOW_BY_WORKFLOW_ID_ERROR"
msgstr "Error while retrieving workflow"

#: src/backend/controllers/workflow.py:133
msgid "DUPLICATE_WORKFLOW"
msgstr "Workflow duplicated&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:138
#: src/backend/controllers/workflow.py:144
msgid "DUPLICATE_WORKFLOW_ERROR"
msgstr "Error duplicating workflow"

#: src/backend/controllers/workflow.py:169
#: src/backend/controllers/workflow.py:181
#: src/backend/controllers/workflow.py:192
#: src/backend/controllers/workflow.py:227
#: src/backend/controllers/workflow.py:247
msgid "CREATE_WORKFLOW_ERROR"
msgstr "Error while creating workflow"

#: src/backend/controllers/workflow.py:170
#: src/backend/controllers/workflow.py:257
msgid "NOT_ALLOWED_INPUT_PATH"
msgstr "The input path is not allowed"

#: src/backend/controllers/workflow.py:182
msgid "WORKFLOW_ID_ALREADY_EXISTS"
msgstr "The label short already exists"

#: src/backend/controllers/workflow.py:193
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr "The document capture path is already set in another workflow"

#: src/backend/controllers/workflow.py:239
msgid "CREATE_WORKFLOW"
msgstr "Workflow created&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:256
#: src/backend/controllers/workflow.py:296
#: src/backend/controllers/workflow.py:313
#: src/backend/controllers/workflow.py:319
msgid "UPDATE_WORKFLOW_ERROR"
msgstr "Error while trying to update workflow"

#: src/backend/controllers/workflow.py:308
msgid "UPDATE_WORKFLOW"
msgstr "Workflow updated&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:336
msgid "DELETE_WORKFLOW"
msgstr "Workflow deleted&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:341
#: src/backend/controllers/workflow.py:347
msgid "DELETE_WORKFLOW_ERROR"
msgstr "Error while deleting workflow"

#: src/backend/controllers/workflow.py:397
#: src/backend/controllers/workflow.py:419
msgid "FS_WATCHER_CREATION_ERROR"
msgstr "Error while creating fs watcher settings"

#: src/backend/controllers/workflow.py:420
#: src/backend/controllers/workflow.py:472
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr "Fs watcher config doesnt exists"

#: src/backend/controllers/workflow.py:425
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr "Script sample doesn't exists"

#: src/backend/controllers/workflow.py:431
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr "Script folder doesn't exists"

#: src/backend/controllers/workflow.py:471
msgid "FS_WATCHER_DELETION_ERROR"
msgstr "Error while deleting fs watcher settings"

#: src/backend/controllers/workflow.py:498
msgid "LINE"
msgstr "Line"

#: src/backend/controllers/workflow.py:499
msgid "COLUMN"
msgstr "column"

#: src/backend/models/accounts.py:105
msgid "SUPPLIER_UPDATE_ERROR"
msgstr "Error while updating supplier"

#: src/backend/models/artificial_intelligence.py:80
msgid "IA_MODEL_CREATE_ERROR"
msgstr "Error while creating ai models"

#: src/backend/models/artificial_intelligence.py:101
msgid "IA_MODEL_UPDATE_ERROR"
msgstr "Error while updating ai models"

#: src/backend/models/attachments.py:38
msgid "CREATE_ATTACHMENT_ERROR"
msgstr "Error while creating attachment"

#: src/backend/models/auth.py:45
msgid "USER_DISABLED"
msgstr "User disabled"

#: src/backend/models/auth.py:66 src/backend/models/auth.py:76
#: src/backend/models/roles.py:61
msgid "ROLE_DOESNT_EXISTS"
msgstr "Role doesn't exists"

#: src/backend/models/auth.py:97 src/backend/models/user.py:37
msgid "BAD_USERNAME"
msgstr "Bad username"

#: src/backend/models/auth.py:207
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Error while disabling login method"

#: src/backend/models/auth.py:229
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Error while enabling login method"

#: src/backend/models/custom_fields.py:57
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr "Error while creating custom field"

#: src/backend/models/custom_fields.py:60
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr "Custom field already exist"

#: src/backend/models/custom_fields.py:111
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr "Error while updating custom fields"

#: src/backend/models/custom_fields.py:134
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr "Error while deleting custom field"

#: src/backend/models/doctypes.py:54
msgid "DOCTYPE_ALREADY_EXIST"
msgstr "Doctype already exist"

#: src/backend/models/doctypes.py:100
msgid "UPDATE_DOCTYPE_ERROR"
msgstr "Error while updating doctype"

#: src/backend/models/forms.py:45
msgid "GET_FORMS_ERROR"
msgstr "Error while retrieving forms"

#: src/backend/models/forms.py:89
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr "Error while retrieving form settings"

#: src/backend/models/forms.py:112
msgid "GET_DEFAULT_FORM_ERROR"
msgstr "Error while retrieving default form"

#: src/backend/models/forms.py:136
msgid "UPDATE_FORM_ERROR"
msgstr "Error while updating form"

#: src/backend/models/forms.py:158
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr "Error while updating form fields"

#: src/backend/models/forms.py:215
msgid "ADD_FORM_ERROR"
msgstr "Error while creating form"

#: src/backend/models/forms.py:218
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr "Form label already exist"

#: src/backend/models/mailcollect.py:86
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr "Error while updating MailCollect process"

#: src/backend/models/outputs.py:78
msgid "OUTPUT_DOESNT_EXISTS"
msgstr "Output doesn't exists"

#: src/backend/models/outputs.py:125
msgid "OUTPUT_UPDATE_ERROR"
msgstr "Error while updating output"

#: src/backend/models/outputs.py:145
msgid "OUTPUT_CREATE_ERROR"
msgstr "Error while creating output"

#: src/backend/models/positions_masks.py:63
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/models/positions_masks.py:87
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr "Error while updating positions mask"

#: src/backend/models/positions_masks.py:109
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr "Error while updating positions mask fields"

#: src/backend/models/positions_masks.py:144
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr "Error while creating positions mask"

#: src/backend/models/positions_masks.py:147
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr "Positions mask label already exists"

#: src/backend/models/privileges.py:38 src/backend/models/privileges.py:59
#: src/backend/models/privileges.py:83
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr "Error while retrieving privileges"

#: src/backend/models/roles.py:127
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr "Error while updating role privileges"

#: src/backend/models/roles.py:149
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr "Error while creating role privileges"

#: src/backend/models/splitter.py:78
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr "Error while getting splitter index"

#: src/backend/models/splitter.py:125
msgid "UPDATE_SETTINGS_ERROR"
msgstr "Error while updating splitter settings"

#: src/backend/models/splitter.py:150
msgid "INSERT_PAGE_ERROR"
msgstr "Error while inserting splitter pages"

#: src/backend/models/splitter.py:247
msgid "GET_DOCUMENTS_ERROR"
msgstr "Error while getting splitter documents"

#: src/backend/models/splitter.py:269 src/backend/models/splitter.py:292
msgid "GET_PAGES_ERROR"
msgstr "Error while getting splitter pages"

#: src/backend/models/splitter.py:314
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr "Error while getting splitter source pages value"

#: src/backend/models/splitter.py:337
msgid "GET_DOCUMENT_ERROR"
msgstr "Error while retrieving document"

#: src/backend/models/splitter.py:359
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr "Error while getting splitter maximum index"

#: src/backend/models/status.py:40
msgid "NO_STATUS"
msgstr "No status"

#: src/backend/models/user.py:39
msgid "BAD_PASSWORD"
msgstr "Bad password"

#: src/backend/models/user.py:50
msgid "USER"
msgstr "The user"

#: src/backend/models/user.py:50
msgid "ALREADY_REGISTERED"
msgstr "Already registered"

#: src/backend/models/user.py:53
msgid "USER_RESTORED"
msgstr "ths user is restored"

#: src/backend/models/user.py:168
msgid "GET_USER_BY_MAIL_ERROR"
msgstr "No user found with this email address"

#: src/backend/models/user.py:237
msgid "GET_FORMS_BY_USER_ID_ERROR"
msgstr "Error while retrieving forms by user"

#: src/backend/models/verifier.py:128 src/backend/models/verifier.py:149
msgid "DOCUMENT_UPDATE_ERROR"
msgstr "Error while updating document"

#: src/backend/models/workflow.py:60 src/backend/models/workflow.py:83
msgid "WORKFLOW_DOESNT_EXISTS"
msgstr "Workflow doesn't exists"

#: src/backend/models/workflow.py:105
msgid "WORKFLOW_CREATE_ERROR"
msgstr "Error while creating workflow"

#: src/backend/models/workflow.py:127
msgid "WORKFLOW_UPDATE_ERROR"
msgstr "Error while updating workflow"

#: src/backend/rest/accounts.py:35 src/backend/rest/accounts.py:56
#: src/backend/rest/accounts.py:69 src/backend/rest/accounts.py:81
#: src/backend/rest/accounts.py:120 src/backend/rest/accounts.py:142
#: src/backend/rest/accounts.py:164 src/backend/rest/accounts.py:190
#: src/backend/rest/accounts.py:217 src/backend/rest/accounts.py:251
#: src/backend/rest/accounts.py:287 src/backend/rest/accounts.py:298
#: src/backend/rest/accounts.py:309 src/backend/rest/accounts.py:338
#: src/backend/rest/accounts.py:367 src/backend/rest/accounts.py:379
#: src/backend/rest/accounts.py:401 src/backend/rest/accounts.py:412
#: src/backend/rest/accounts.py:438 src/backend/rest/accounts.py:463
#: src/backend/rest/accounts.py:488 src/backend/rest/accounts.py:510
#: src/backend/rest/accounts.py:521
#: src/backend/rest/artificial_intelligence.py:30
#: src/backend/rest/artificial_intelligence.py:40
#: src/backend/rest/artificial_intelligence.py:51
#: src/backend/rest/artificial_intelligence.py:62
#: src/backend/rest/artificial_intelligence.py:74
#: src/backend/rest/artificial_intelligence.py:91
#: src/backend/rest/artificial_intelligence.py:106
#: src/backend/rest/artificial_intelligence.py:118
#: src/backend/rest/attachments.py:30 src/backend/rest/attachments.py:49
#: src/backend/rest/attachments.py:68 src/backend/rest/attachments.py:77
#: src/backend/rest/attachments.py:86 src/backend/rest/attachments.py:97
#: src/backend/rest/attachments.py:108 src/backend/rest/attachments.py:117
#: src/backend/rest/auth.py:82 src/backend/rest/auth.py:131
#: src/backend/rest/auth.py:141 src/backend/rest/auth.py:167
#: src/backend/rest/auth.py:200 src/backend/rest/auth.py:239
#: src/backend/rest/auth.py:258 src/backend/rest/config.py:30
#: src/backend/rest/config.py:40 src/backend/rest/config.py:61
#: src/backend/rest/config.py:73 src/backend/rest/config.py:84
#: src/backend/rest/config.py:105 src/backend/rest/config.py:126
#: src/backend/rest/config.py:154 src/backend/rest/config.py:173
#: src/backend/rest/config.py:196 src/backend/rest/config.py:219
#: src/backend/rest/custom_fields.py:32 src/backend/rest/custom_fields.py:46
#: src/backend/rest/custom_fields.py:57 src/backend/rest/custom_fields.py:68
#: src/backend/rest/custom_fields.py:78 src/backend/rest/doctypes.py:31
#: src/backend/rest/doctypes.py:47 src/backend/rest/doctypes.py:58
#: src/backend/rest/doctypes.py:69 src/backend/rest/doctypes.py:80
#: src/backend/rest/doctypes.py:90 src/backend/rest/doctypes.py:101
#: src/backend/rest/doctypes.py:116 src/backend/rest/forms.py:34
#: src/backend/rest/forms.py:62 src/backend/rest/forms.py:74
#: src/backend/rest/forms.py:120 src/backend/rest/forms.py:143
#: src/backend/rest/forms.py:164 src/backend/rest/forms.py:184
#: src/backend/rest/forms.py:210 src/backend/rest/forms.py:221
#: src/backend/rest/forms.py:232 src/backend/rest/forms.py:243
#: src/backend/rest/forms.py:255 src/backend/rest/history.py:54
#: src/backend/rest/history.py:79 src/backend/rest/history.py:99
#: src/backend/rest/locale.py:31 src/backend/rest/mailcollect.py:30
#: src/backend/rest/mailcollect.py:40 src/backend/rest/mailcollect.py:70
#: src/backend/rest/mailcollect.py:104 src/backend/rest/mailcollect.py:137
#: src/backend/rest/mailcollect.py:148 src/backend/rest/mailcollect.py:159
#: src/backend/rest/monitoring.py:30 src/backend/rest/monitoring.py:40
#: src/backend/rest/monitoring.py:50 src/backend/rest/monitoring.py:61
#: src/backend/rest/outputs.py:32 src/backend/rest/outputs.py:55
#: src/backend/rest/outputs.py:74 src/backend/rest/outputs.py:86
#: src/backend/rest/outputs.py:98 src/backend/rest/outputs.py:124
#: src/backend/rest/outputs.py:136 src/backend/rest/outputs.py:161
#: src/backend/rest/outputs.py:172 src/backend/rest/positions_masks.py:33
#: src/backend/rest/positions_masks.py:53
#: src/backend/rest/positions_masks.py:74
#: src/backend/rest/positions_masks.py:85
#: src/backend/rest/positions_masks.py:109
#: src/backend/rest/positions_masks.py:120
#: src/backend/rest/positions_masks.py:131
#: src/backend/rest/positions_masks.py:142
#: src/backend/rest/positions_masks.py:153
#: src/backend/rest/positions_masks.py:164
#: src/backend/rest/positions_masks.py:175
#: src/backend/rest/positions_masks.py:186 src/backend/rest/privileges.py:29
#: src/backend/rest/privileges.py:39 src/backend/rest/roles.py:55
#: src/backend/rest/roles.py:65 src/backend/rest/roles.py:87
#: src/backend/rest/roles.py:106 src/backend/rest/roles.py:116
#: src/backend/rest/roles.py:126 src/backend/rest/roles.py:136
#: src/backend/rest/splitter.py:31 src/backend/rest/splitter.py:58
#: src/backend/rest/splitter.py:68 src/backend/rest/splitter.py:78
#: src/backend/rest/splitter.py:89 src/backend/rest/splitter.py:110
#: src/backend/rest/splitter.py:130 src/backend/rest/splitter.py:141
#: src/backend/rest/splitter.py:151 src/backend/rest/splitter.py:162
#: src/backend/rest/splitter.py:176 src/backend/rest/splitter.py:187
#: src/backend/rest/splitter.py:198 src/backend/rest/splitter.py:209
#: src/backend/rest/splitter.py:220 src/backend/rest/splitter.py:239
#: src/backend/rest/splitter.py:250 src/backend/rest/splitter.py:265
#: src/backend/rest/splitter.py:268 src/backend/rest/splitter.py:286
#: src/backend/rest/splitter.py:298 src/backend/rest/splitter.py:309
#: src/backend/rest/splitter.py:320 src/backend/rest/splitter.py:330
#: src/backend/rest/splitter.py:341 src/backend/rest/status.py:32
#: src/backend/rest/user.py:31 src/backend/rest/user.py:59
#: src/backend/rest/user.py:102 src/backend/rest/user.py:124
#: src/backend/rest/user.py:185 src/backend/rest/user.py:212
#: src/backend/rest/user.py:222 src/backend/rest/user.py:232
#: src/backend/rest/user.py:249 src/backend/rest/user.py:269
#: src/backend/rest/user.py:279 src/backend/rest/user.py:299
#: src/backend/rest/user.py:314 src/backend/rest/verifier.py:45
#: src/backend/rest/verifier.py:110 src/backend/rest/verifier.py:139
#: src/backend/rest/verifier.py:167 src/backend/rest/verifier.py:179
#: src/backend/rest/verifier.py:190 src/backend/rest/verifier.py:202
#: src/backend/rest/verifier.py:214 src/backend/rest/verifier.py:239
#: src/backend/rest/verifier.py:264 src/backend/rest/verifier.py:289
#: src/backend/rest/verifier.py:312 src/backend/rest/verifier.py:334
#: src/backend/rest/verifier.py:356 src/backend/rest/verifier.py:367
#: src/backend/rest/verifier.py:395 src/backend/rest/verifier.py:423
#: src/backend/rest/verifier.py:452 src/backend/rest/verifier.py:463
#: src/backend/rest/verifier.py:475 src/backend/rest/verifier.py:508
#: src/backend/rest/verifier.py:544 src/backend/rest/verifier.py:565
#: src/backend/rest/verifier.py:579 src/backend/rest/verifier.py:590
#: src/backend/rest/verifier.py:612 src/backend/rest/verifier.py:634
#: src/backend/rest/verifier.py:654 src/backend/rest/verifier.py:667
#: src/backend/rest/verifier.py:678 src/backend/rest/verifier.py:699
#: src/backend/rest/workflow.py:32 src/backend/rest/workflow.py:54
#: src/backend/rest/workflow.py:84 src/backend/rest/workflow.py:110
#: src/backend/rest/workflow.py:122 src/backend/rest/workflow.py:134
#: src/backend/rest/workflow.py:146 src/backend/rest/workflow.py:158
#: src/backend/rest/workflow.py:186 src/backend/rest/workflow.py:210
#: src/backend/rest/workflow.py:221
msgid "UNAUTHORIZED_ROUTE"
msgstr "You are not authorized to access this route"

#: src/backend/rest/accounts.py:44 src/backend/rest/accounts.py:106
#: src/backend/rest/accounts.py:128 src/backend/rest/accounts.py:150
#: src/backend/rest/accounts.py:177 src/backend/rest/accounts.py:203
#: src/backend/rest/accounts.py:229 src/backend/rest/accounts.py:275
#: src/backend/rest/accounts.py:319 src/backend/rest/accounts.py:348
#: src/backend/rest/accounts.py:389 src/backend/rest/accounts.py:426
#: src/backend/rest/accounts.py:451 src/backend/rest/attachments.py:38
#: src/backend/rest/attachments.py:57 src/backend/rest/auth.py:37
#: src/backend/rest/auth.py:55 src/backend/rest/auth.py:70
#: src/backend/rest/auth.py:91 src/backend/rest/auth.py:111
#: src/backend/rest/auth.py:155 src/backend/rest/auth.py:188
#: src/backend/rest/auth.py:221 src/backend/rest/auth.py:246
#: src/backend/rest/auth.py:265 src/backend/rest/config.py:49
#: src/backend/rest/config.py:93 src/backend/rest/config.py:114
#: src/backend/rest/config.py:136 src/backend/rest/config.py:161
#: src/backend/rest/config.py:184 src/backend/rest/config.py:207
#: src/backend/rest/config.py:230 src/backend/rest/coog.py:37
#: src/backend/rest/forms.py:46 src/backend/rest/forms.py:86
#: src/backend/rest/forms.py:131 src/backend/rest/forms.py:152
#: src/backend/rest/forms.py:172 src/backend/rest/forms.py:197
#: src/backend/rest/forms.py:268 src/backend/rest/history.py:40
#: src/backend/rest/history.py:67 src/backend/rest/history.py:87
#: src/backend/rest/mailcollect.py:58 src/backend/rest/mailcollect.py:92
#: src/backend/rest/mailcollect.py:125 src/backend/rest/mem.py:37
#: src/backend/rest/mem.py:56 src/backend/rest/mem.py:75
#: src/backend/rest/mem.py:94 src/backend/rest/mem.py:113
#: src/backend/rest/mem.py:132 src/backend/rest/mem.py:151
#: src/backend/rest/mem.py:170 src/backend/rest/mem.py:189
#: src/backend/rest/mem.py:214 src/backend/rest/monitoring.py:70
#: src/backend/rest/opencaptureformem.py:37
#: src/backend/rest/opencaptureformem.py:55 src/backend/rest/outputs.py:40
#: src/backend/rest/outputs.py:111 src/backend/rest/outputs.py:148
#: src/backend/rest/outputs.py:180 src/backend/rest/positions_masks.py:41
#: src/backend/rest/positions_masks.py:62
#: src/backend/rest/positions_masks.py:97 src/backend/rest/roles.py:37
#: src/backend/rest/roles.py:75 src/backend/rest/roles.py:94
#: src/backend/rest/roles.py:145 src/backend/rest/smtp.py:39
#: src/backend/rest/splitter.py:98 src/backend/rest/splitter.py:118
#: src/backend/rest/user.py:47 src/backend/rest/user.py:70
#: src/backend/rest/user.py:112 src/backend/rest/user.py:139
#: src/backend/rest/user.py:156 src/backend/rest/user.py:172
#: src/backend/rest/user.py:200 src/backend/rest/user.py:257
#: src/backend/rest/user.py:287 src/backend/rest/user.py:324
#: src/backend/rest/verifier.py:58 src/backend/rest/verifier.py:126
#: src/backend/rest/verifier.py:154 src/backend/rest/verifier.py:226
#: src/backend/rest/verifier.py:251 src/backend/rest/verifier.py:276
#: src/backend/rest/verifier.py:299 src/backend/rest/verifier.py:322
#: src/backend/rest/verifier.py:344 src/backend/rest/verifier.py:377
#: src/backend/rest/verifier.py:405 src/backend/rest/verifier.py:433
#: src/backend/rest/verifier.py:487 src/backend/rest/verifier.py:519
#: src/backend/rest/verifier.py:552 src/backend/rest/verifier.py:599
#: src/backend/rest/verifier.py:621 src/backend/rest/verifier.py:642
#: src/backend/rest/verifier.py:687 src/backend/rest/workflow.py:41
#: src/backend/rest/workflow.py:69 src/backend/rest/workflow.py:92
#: src/backend/rest/workflow.py:173 src/backend/rest/workflow.py:198
#: src/backend/rest/workflow.py:228
msgid "BAD_REQUEST"
msgstr "Bad request"

#: src/backend/rest/attachments.py:90 src/backend/rest/attachments.py:101
#: src/backend/rest/verifier.py:570
msgid "DOWNLOAD_FILE"
msgstr "Download file"

#: src/backend/rest/attachments.py:90 src/backend/rest/attachments.py:101
#: src/backend/rest/verifier.py:570
msgid "FILE_NOT_FOUND"
msgstr "File not found"

#: src/backend/rest/splitter.py:51 src/backend/rest/verifier.py:103
msgid "UNKNOW_ERROR"
msgstr "Unknow error"

#: src/backend/rest/verifier.py:98
msgid "UNIQUE_URL_TOKEN_GENERATION_ERROR"
msgstr "Error while generating unique url token"

#: src/backend/rest/verifier.py:99
msgid "INTERFACE_IS_NOT_USED_OR_FORM_UNIQUE_URL_NOT_SET"
msgstr ""
"Interface use is not set in workflow or unique url settings is malformed "
"on the form"

#~ msgid "GET_ATTACHMENTS_ERROR"
#~ msgstr "Error while retrieving attachments"

#~ msgid "GET_ATTACHMENT_ERROR"
#~ msgstr "Error while retrieving attachment"

