# English translations for Open-Capture
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the project
# FIRST AUTHOR <nathan.cheval@edissyum.com>, 2021.
msgid ""
msgstr ""
"Project-Id-Version:  0.1\n"
"Report-Msgid-Bugs-To: nathan.cheval@edissyum.com\n"
"POT-Creation-Date: 2023-02-13 15:57+0100\n"
"PO-Revision-Date: 2019-09-02 17:48+0200\n"
"Last-Translator: Nathan CHEVAL <nathan.cheval@edissyum.com>\n"
"Language: en\n"
"Language-Team: en <nathan.cheval@edissyum.com>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.11.0\n"

#: launch_worker.py:47 launch_worker_splitter.py:49
msgid "FILE_UPLOADED"
msgstr "File uploaded successfully via fs-watcher with input"

#: src/backend/verifier_exports.py:85 src/backend/verifier_exports.py:88
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Destination folder for XML doesn't exists"

#: src/backend/verifier_exports.py:154 src/backend/verifier_exports.py:157
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Destination folder for PDF doesn't exists"

#: src/backend/controllers/splitter.py:390
#: src/backend/controllers/splitter.py:396 src/backend/verifier_exports.py:309
#: src/backend/verifier_exports.py:315 src/backend/verifier_exports.py:321
msgid "EXPORT_MEM_ERROR"
msgstr "Error during MEM Courrier export"

#: src/backend/verifier_exports.py:316
msgid "PDF_FILE_NOT_FOUND"
msgstr "PDF file not found"

#: src/backend/verifier_exports.py:327
msgid "MEM_WS_INFO_WRONG"
msgstr "MEM Courrier informations are wrong"

#: src/backend/controllers/splitter.py:402 src/backend/verifier_exports.py:333
msgid "MEM_WS_INFO_EMPTY"
msgstr "MEM Courrier informations are empty"

#: src/backend/classes/MEMWebServices.py:38
msgid "HOST_NOT_FOUND"
msgstr "Host not found"

#: src/backend/classes/SMTP.py:218
msgid "RESET_PASSWORD"
msgstr "Reset password"

#: src/backend/classes/SMTP.py:220
msgid "FORGOT_EMAIL_HEADER"
msgstr ""
"Hello,<br/><br/>You requested to reset your Open-Capture account "
"password.<br/><br/>To change it, please click on the link below :<br/>"

#: src/backend/classes/SMTP.py:220
msgid "CLICK_HERE"
msgstr "Click here"

#: src/backend/classes/SMTP.py:220
msgid "FORGOT_EMAIL_FOOTER"
msgstr ""
"<br/><br/>If you did not requested this action, you can ignore this "
"email.<br/><br/>"

#: src/backend/controllers/accounts.py:45 src/backend/models/accounts.py:55
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr "Error retrieving supplier"

#: src/backend/controllers/accounts.py:58 src/backend/models/accounts.py:75
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr "Error retrieving address"

#: src/backend/controllers/accounts.py:85
#: src/backend/controllers/accounts.py:170
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr "Error updating supplier positions"

#: src/backend/controllers/accounts.py:112
#: src/backend/controllers/accounts.py:201
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr "Error update supplier pages"

#: src/backend/controllers/accounts.py:133
#: src/backend/controllers/accounts.py:139
msgid "UPDATE_SUPPLIER_ERROR"
msgstr "Error updating supplier"

#: src/backend/controllers/accounts.py:225
#: src/backend/controllers/accounts.py:231
#: src/backend/controllers/accounts.py:255
#: src/backend/controllers/accounts.py:261 src/backend/models/accounts.py:115
msgid "UPDATE_ADDRESS_ERROR"
msgstr "Error updating address"

#: src/backend/controllers/accounts.py:285 src/backend/models/accounts.py:132
msgid "CREATE_ADDRESS_ERROR"
msgstr "Error creating address"

#: src/backend/controllers/accounts.py:322
#: src/backend/controllers/accounts.py:328 src/backend/models/accounts.py:149
msgid "CREATE_SUPPLIER_ERROR"
msgstr "Error creating supplier"

#: src/backend/controllers/accounts.py:329
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A supplier already exists with this vat number"

#: src/backend/controllers/accounts.py:349 src/backend/controllers/user.py:204
#: src/backend/models/accounts.py:204 src/backend/models/accounts.py:224
#: src/backend/models/accounts.py:240 src/backend/models/user.py:183
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr "Error retrieving customer"

#: src/backend/controllers/accounts.py:391
#: src/backend/controllers/accounts.py:397 src/backend/models/accounts.py:259
msgid "UPDATE_CUSTOMER_ERROR"
msgstr "Error updating customer"

#: src/backend/controllers/accounts.py:426
#: src/backend/controllers/accounts.py:432 src/backend/models/accounts.py:276
msgid "CREATE_CUSTOMER_ERROR"
msgstr "Error creating customer"

#: src/backend/controllers/accounts.py:433
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A customer already exists with this vat number"

#: src/backend/controllers/accounts.py:447
#: src/backend/controllers/accounts.py:453 src/backend/models/accounts.py:295
msgid "DELETE_CUSTOMER_ERROR"
msgstr "Error deleting customer"

#: src/backend/controllers/accounts.py:468
#: src/backend/controllers/accounts.py:474 src/backend/models/accounts.py:168
msgid "DELETE_SUPPLIER_ERROR"
msgstr "Error deleting supplier"

#: src/backend/controllers/accounts.py:496
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr "Error while loading supplier referencial"

#: src/backend/controllers/artificial_intelligence.py:74
#: src/backend/controllers/artificial_intelligence.py:377
msgid "GET_IA_MODEL_BY_ID_ERROR"
msgstr "Error retrieving ai model"

#: src/backend/controllers/artificial_intelligence.py:98
msgid "CREATE_IA_MODEL_ERROR"
msgstr "Error creating ai models"

#: src/backend/controllers/artificial_intelligence.py:109
msgid "UPDATE_IA_MODEL_ERROR"
msgstr "Error updating ai model"

#: src/backend/controllers/artificial_intelligence.py:378
#: src/backend/models/artificial_intelligence.py:53
msgid "IA_MODEL_DOESNT_EXISTS"
msgstr "AI model doesn't exists"

#: src/backend/controllers/auth.py:103
msgid "RESET_JWT_ERROR"
msgstr "Reset JWT error"

#: src/backend/controllers/auth.py:115 src/backend/controllers/auth.py:162
#: src/backend/controllers/auth.py:204 src/backend/controllers/auth.py:251
#: src/backend/controllers/auth.py:262 src/backend/controllers/auth.py:272
#: src/backend/controllers/auth.py:299 src/backend/rest/auth.py:69
msgid "LOGIN_ERROR"
msgstr "Login error"

#: src/backend/controllers/auth.py:180 src/backend/controllers/auth.py:219
#: src/backend/controllers/auth.py:227 src/backend/controllers/auth.py:230
#: src/backend/controllers/auth.py:232
msgid "JWT_ERROR"
msgstr "Authentification by token error"

#: src/backend/controllers/auth.py:227
msgid "ACCOUNT_ALREADY_LOGGED"
msgstr ""
"Your account is already log in another machine. Only one connection is "
"allowed per account"

#: src/backend/controllers/auth.py:263
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr "Several authentication methods are enabled"

#: src/backend/controllers/auth.py:287
msgid "LDAP_ERROR"
msgstr "LDAP error"

#: src/backend/controllers/auth.py:288 src/backend/models/auth.py:125
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr "No LDAP configurations found"

#: src/backend/controllers/auth.py:314
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr "Error while loading login methods"

#: src/backend/controllers/auth.py:326
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr "Error while disabling login methods"

#: src/backend/controllers/auth.py:338
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr "Error while enabling login methods"

#: src/backend/controllers/auth.py:361 src/backend/controllers/auth.py:546
#: src/backend/controllers/auth.py:602 src/backend/controllers/auth.py:617
#: src/backend/controllers/auth.py:625 src/backend/controllers/auth.py:631
msgid "LDAP_CONNECTION_ERROR"
msgstr "Unable to connect to LDAP server"

#: src/backend/controllers/auth.py:362
msgid "LOGIN_LDAP_ERROR"
msgstr "Error while logging using LDAP"

#: src/backend/controllers/auth.py:534 src/backend/controllers/auth.py:540
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr "Synchronization's informations are incorrect"

#: src/backend/controllers/auth.py:536 src/backend/controllers/auth.py:542
#: src/backend/controllers/auth.py:548 src/backend/controllers/auth.py:554
#: src/backend/controllers/auth.py:560
msgid "LDAP_SYNCHRO_ERROR"
msgstr "Error while syncing LDAP"

#: src/backend/controllers/auth.py:552 src/backend/controllers/auth.py:558
#: src/backend/controllers/auth.py:637 src/backend/rest/auth.py:110
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr "Missing informations"

#: src/backend/controllers/auth.py:600 src/backend/controllers/auth.py:615
#: src/backend/controllers/auth.py:623
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr "Incorrect information"

#: src/backend/controllers/auth.py:635 src/backend/rest/auth.py:108
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr "One or more information are missing to establish the connection"

#: src/backend/controllers/config.py:62
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr "Error while retrieving configuration"

#: src/backend/controllers/config.py:78
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr "Error while retrieving configurations"

#: src/backend/controllers/config.py:94
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr "Error while retrieving docservers"

#: src/backend/controllers/config.py:110
msgid "RETRIEVE_REGEX_ERRORS"
msgstr "Error while retrieving regex"

#: src/backend/controllers/config.py:122 src/backend/controllers/config.py:142
#: src/backend/models/config.py:157
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr "Error while updating configuration"

#: src/backend/controllers/config.py:123
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr "The value of token expiration could'nt be 0 or less"

#: src/backend/controllers/config.py:163 src/backend/models/config.py:176
msgid "UPDATE_REGEX_ERROR"
msgstr "Error while updating REGEX"

#: src/backend/controllers/config.py:183 src/backend/models/config.py:199
msgid "UPDATE_DOCSERVER_ERROR"
msgstr "Error while updating docserver"

#: src/backend/controllers/config.py:224 src/backend/controllers/config.py:234
#: src/backend/controllers/config.py:239
msgid "ERROR_UPDATING_IMAGE"
msgstr "Error while updating login image"

#: src/backend/controllers/config.py:225 src/backend/controllers/config.py:235
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr "Custom image path is not writeable"

#: src/backend/controllers/config.py:240
msgid "CUSTOM_NOT_PRESENT"
msgstr "No custom is present"

#: src/backend/controllers/custom_fields.py:33
#: src/backend/controllers/custom_fields.py:49
#: src/backend/controllers/custom_fields.py:62
msgid "CUSTOM_FIELDS_ERROR"
msgstr "Custom fields error"

#: src/backend/controllers/custom_fields.py:75
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr "Error while deleting custom field"

#: src/backend/controllers/doctypes.py:35
#: src/backend/controllers/doctypes.py:77 src/backend/models/doctypes.py:119
#: src/backend/models/doctypes.py:122
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr "Error while updating default doctype"

#: src/backend/controllers/doctypes.py:41 src/backend/models/doctypes.py:48
msgid "ADD_DOCTYPE_ERROR"
msgstr "Error while adding doctype"

#: src/backend/controllers/doctypes.py:61
#: src/backend/controllers/doctypes.py:97
#: src/backend/controllers/doctypes.py:110
#: src/backend/controllers/doctypes.py:162
#: src/backend/controllers/doctypes.py:193
msgid "DOCTYPE_ERROR"
msgstr "Doctype error"

#: src/backend/controllers/doctypes.py:129
msgid "BUNDLESEPARATOR"
msgstr "SEPARATEUR DE LOT / BUNDLE SEPARATOR"

#: src/backend/controllers/doctypes.py:136
msgid "DOCUMENTSEPARATOR"
msgstr "SEPARATEUR DE DOCUMENT / DOCUMENT SEPARATOR"

#: src/backend/controllers/doctypes.py:155
msgid "DOCTYPESEPARATOR"
msgstr "SEPARATEUR AVEC TYPE DE DOCUMENT / SEPARATOR WITH DOCUMENT TYPE"

#: src/backend/controllers/forms.py:46 src/backend/controllers/forms.py:56
#: src/backend/controllers/forms.py:82 src/backend/controllers/forms.py:190
msgid "FORMS_ERROR"
msgstr "Forms error"

#: src/backend/controllers/forms.py:97 src/backend/controllers/forms.py:146
#: src/backend/models/forms.py:57
msgid "GET_FORM_BY_ID_ERROR"
msgstr "Error retrieving form"

#: src/backend/controllers/forms.py:129
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr "Error retrieving form fields"

#: src/backend/controllers/forms.py:184 src/backend/controllers/forms.py:312
#: src/backend/controllers/forms.py:318
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr "Error updating form fields"

#: src/backend/controllers/forms.py:204 src/backend/controllers/forms.py:210
msgid "DELETE_FORM_ERROR"
msgstr "Error deleting form"

#: src/backend/controllers/forms.py:219 src/backend/controllers/inputs.py:84
#: src/backend/controllers/outputs.py:54
#: src/backend/controllers/positions_masks.py:159
msgid "COPY_OF"
msgstr "Copy of"

#: src/backend/controllers/forms.py:236 src/backend/controllers/forms.py:242
msgid "DUPLICATE_FORM_ERROR"
msgstr "Error duplicating form"

#: src/backend/controllers/forms.py:256 src/backend/controllers/forms.py:262
msgid "DISABLE_FORM_ERROR"
msgstr "Error disabling form"

#: src/backend/controllers/forms.py:276 src/backend/controllers/forms.py:282
msgid "ENABLE_FORM_ERROR"
msgstr "Error enabling form"

#: src/backend/controllers/forms.py:298
msgid "GET_FORMS_FIELDS_ERROR"
msgstr "Error while retrieving form fields"

#: src/backend/controllers/history.py:28
msgid "ADD_HISTORY_ERROR"
msgstr "Error while adding new history"

#: src/backend/controllers/inputs.py:66 src/backend/controllers/inputs.py:72
msgid "UPDATE_INPUT_ERROR"
msgstr "Error while updating input"

#: src/backend/controllers/inputs.py:97 src/backend/controllers/inputs.py:103
msgid "DUPLICATE_INPUT_ERROR"
msgstr "Error while duplicate input"

#: src/backend/controllers/inputs.py:132 src/backend/controllers/inputs.py:143
#: src/backend/controllers/inputs.py:156
msgid "CREATE_INPUT_ERROR"
msgstr "Error while creating input"

#: src/backend/controllers/inputs.py:133
msgid "INPUT_ID_ALREADY_EXISTS"
msgstr "The label short already exists"

#: src/backend/controllers/inputs.py:144
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr "The document capture path is already set in another input"

#: src/backend/controllers/inputs.py:169
msgid "GET_INPUT_BY_ID_ERROR"
msgstr "Error while retrieving input"

#: src/backend/controllers/inputs.py:190 src/backend/controllers/inputs.py:196
msgid "DELETE_INPUT_ERROR"
msgstr "Error while deleting input"

#: src/backend/controllers/inputs.py:232
msgid "FS_WATCHER_DELETION_ERROR"
msgstr "Error while deleting fs watcher settings"

#: src/backend/controllers/inputs.py:233 src/backend/controllers/inputs.py:300
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr "Fs watcher config doesnt exists"

#: src/backend/controllers/inputs.py:279 src/backend/controllers/inputs.py:299
msgid "FS_WATCHER_CREATION_ERROR"
msgstr "Error while creating fs watcher settings"

#: src/backend/controllers/inputs.py:280
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr "Cannot create folder because of permission issue"

#: src/backend/controllers/inputs.py:305
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr "Script sample doesn't exists"

#: src/backend/controllers/inputs.py:311
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr "Script folder doesn't exists"

#: src/backend/controllers/mailcollect.py:36
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr "Error while retrieving MailCollect processes"

#: src/backend/controllers/mailcollect.py:52
msgid "UPDATE_PROCESS_ERROR"
msgstr "Error while updating MailCollect process"

#: src/backend/controllers/mailcollect.py:68
msgid "CREATE_PROCESS_ERROR"
msgstr "Error while creating MailCollect process"

#: src/backend/controllers/mailcollect.py:82
#: src/backend/controllers/mailcollect.py:88
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while deleting MailCollect process"

#: src/backend/controllers/mailcollect.py:102
#: src/backend/controllers/mailcollect.py:108
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while enabling MailCollect process"

#: src/backend/controllers/mailcollect.py:122
#: src/backend/controllers/mailcollect.py:128
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while disabling MailCollect process"

#: src/backend/controllers/mailcollect.py:142
#: src/backend/controllers/mailcollect.py:152
msgid "MAILCOLLECT_ERROR"
msgstr "MailCollect error"

#: src/backend/controllers/outputs.py:61 src/backend/controllers/outputs.py:67
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr "Error while duplicate ouput"

#: src/backend/controllers/outputs.py:92 src/backend/controllers/outputs.py:98
msgid "UPDATE_OUTPUT_ERROR"
msgstr "Error while updating output"

#: src/backend/controllers/outputs.py:122
msgid "CREATE_OUTPUT_ERROR"
msgstr "Error while creating output"

#: src/backend/controllers/outputs.py:135
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr "Error while retrieving output"

#: src/backend/controllers/outputs.py:148
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr "Error while retrieving output type"

#: src/backend/controllers/outputs.py:162
#: src/backend/controllers/outputs.py:168
msgid "DELETE_OUTPUT_ERROR"
msgstr "Error while deleting output"

#: src/backend/controllers/positions_masks.py:42
#: src/backend/controllers/positions_masks.py:62
#: src/backend/controllers/positions_masks.py:117
#: src/backend/controllers/positions_masks.py:123
msgid "POSITION_MASKS_ERROR"
msgstr "Position masks error"

#: src/backend/controllers/positions_masks.py:77
#: src/backend/controllers/positions_masks.py:94
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/controllers/positions_masks.py:141
#: src/backend/controllers/positions_masks.py:147
msgid "DELETE_POSITION_MASK_ERROR"
msgstr "Error while deleting positions mask"

#: src/backend/controllers/positions_masks.py:175
#: src/backend/controllers/positions_masks.py:181
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr "Error while duplicating positions mask"

#: src/backend/controllers/positions_masks.py:199
#: src/backend/controllers/positions_masks.py:205
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr "Error while disabling positions mask"

#: src/backend/controllers/positions_masks.py:223
#: src/backend/controllers/positions_masks.py:229
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr "Error while enabling positions mask"

#: src/backend/controllers/positions_masks.py:255
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updating positions mask positions"

#: src/backend/controllers/positions_masks.py:281
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updateing positions mask pages"

#: src/backend/controllers/positions_masks.py:302
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask positions"

#: src/backend/controllers/positions_masks.py:323
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask pages"

#: src/backend/controllers/privileges.py:37
#: src/backend/controllers/privileges.py:65
msgid "GET_PRIVILEGES_ERROR"
msgstr "Error while retrieving privileges"

#: src/backend/controllers/roles.py:47 src/backend/controllers/roles.py:53
#: src/backend/controllers/roles.py:95 src/backend/controllers/roles.py:101
#: src/backend/models/roles.py:75
msgid "UPDATE_ROLE_ERROR"
msgstr "Error while trying to update role"

#: src/backend/controllers/roles.py:75 src/backend/models/roles.py:92
msgid "CREATE_ROLE_ERROR"
msgstr "Error while creating role"

#: src/backend/controllers/roles.py:114
msgid "GET_ROLE_BY_ID_ERROR"
msgstr "Error while retrieving role"

#: src/backend/controllers/roles.py:128 src/backend/controllers/roles.py:134
msgid "DELETE_ROLE_ERROR"
msgstr "Error while deleting role"

#: src/backend/controllers/roles.py:148 src/backend/controllers/roles.py:154
msgid "DISABLE_ROLE_ERROR"
msgstr "Error while disabling role"

#: src/backend/controllers/roles.py:168 src/backend/controllers/roles.py:174
msgid "ENABLE_ROLE_ERROR"
msgstr "Error while enabling role"

#: src/backend/controllers/splitter.py:85
msgid "LOAD_METADATA_ERROR"
msgstr "Error while loading metada"

#: src/backend/controllers/splitter.py:122
#: src/backend/controllers/verifier.py:75
msgid "AT"
msgstr "at"

#: src/backend/controllers/splitter.py:141
msgid "FORM_UNDEFINED"
msgstr "Form undefined"

#: src/backend/controllers/splitter.py:144
msgid "CUSTOMER_UNDEFINED"
msgstr "Customer undefined"

#: src/backend/controllers/splitter.py:234
#: src/backend/controllers/verifier.py:345
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr "Error while removing lock"

#: src/backend/controllers/splitter.py:339
msgid "ADD_DOCUMENT_ERROR"
msgstr "Error while adding document"

#: src/backend/controllers/splitter.py:474
#: src/backend/controllers/splitter.py:731
msgid "EXPORT_PDF_ERROR"
msgstr "Error while exporting PDF"

#: src/backend/controllers/splitter.py:496
#: src/backend/controllers/splitter.py:756
msgid "EXPORT_XML_ERROR"
msgstr "Error while exporting XML"

#: src/backend/controllers/splitter.py:512
msgid "UPDATE_BATCH_ERROR"
msgstr "Error while updating batch"

#: src/backend/controllers/splitter.py:525
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr "Error while updating document"

#: src/backend/controllers/splitter.py:538
msgid "UPDATE_DOCUMENT_ERROR"
msgstr "Error while updating document"

#: src/backend/controllers/splitter.py:553
#: src/backend/controllers/splitter.py:574
#: src/backend/controllers/splitter.py:589
#: src/backend/controllers/splitter.py:604
msgid "UPDATE_PAGES_ERROR"
msgstr "Error while updating pages"

#: src/backend/controllers/splitter.py:618
msgid "CMIS_CONNECTION_ERROR"
msgstr "Errur while connecting to CMIS"

#: src/backend/controllers/splitter.py:631
msgid "OPENADS_CONNECTION_ERROR"
msgstr "OpenADS connection error"

#: src/backend/controllers/splitter.py:806
msgid "CHECK_FOLDER_ERROR"
msgstr "Check folder error"

#: src/backend/controllers/splitter.py:824
msgid "OPENADS_ADD_DOC_ERROR"
msgstr "OpenADS add document error"

#: src/backend/controllers/splitter.py:909
#: src/backend/controllers/verifier.py:559 src/backend/models/splitter.py:500
#: src/backend/models/verifier.py:153
msgid "GET_TOTALS_ERROR"
msgstr "Error while retrievings totals"

#: src/backend/controllers/status.py:31
msgid "RETRIEVES_STATUS_ERROR"
msgstr "Error while retrieving status"

#: src/backend/controllers/tasks_watcher.py:34
msgid "CREATE_TASK_ERROR"
msgstr "Error while createing new task"

#: src/backend/controllers/user.py:63
msgid "CREATE_USER_ERROR"
msgstr "Error while creating user"

#: src/backend/controllers/user.py:101 src/backend/controllers/user.py:117
#: src/backend/controllers/user.py:176 src/backend/models/user.py:122
#: src/backend/models/user.py:163
msgid "GET_USER_BY_ID_ERROR"
msgstr "Error while retrieving user"

#: src/backend/controllers/user.py:134
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr "Error while retrieving user"

#: src/backend/controllers/user.py:153
msgid "SEND_EMAIL_FORGOT_PASSWORD_ERROR"
msgstr "Error sending password reset email"

#: src/backend/controllers/user.py:170 src/backend/controllers/user.py:175
msgid "RESET_PASSWORD_ERROR"
msgstr "Erreur while reseting password"

#: src/backend/controllers/user.py:171
msgid "RESET_TOKEN_MISMATCH"
msgstr "Reset token mismatch. Maybe the token is expired"

#: src/backend/controllers/user.py:220
msgid "UPDATE_PROFILE"
msgstr "Update profile"

#: src/backend/controllers/user.py:221
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr "The old password do not match"

#: src/backend/controllers/user.py:226
msgid "UPDATE_USER"
msgstr "Update user"

#: src/backend/controllers/user.py:227
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr "Password do not match"

#: src/backend/controllers/user.py:254 src/backend/controllers/user.py:260
#: src/backend/models/user.py:203 src/backend/models/user.py:241
msgid "UPDATE_USER_ERROR"
msgstr "Error while updating user"

#: src/backend/controllers/user.py:274 src/backend/controllers/user.py:280
msgid "DELETE_USER_ERROR"
msgstr "Error while deleting user"

#: src/backend/controllers/user.py:294 src/backend/controllers/user.py:300
msgid "DISABLE_USER_ERROR"
msgstr "Error while disabling user"

#: src/backend/controllers/user.py:314 src/backend/controllers/user.py:320
msgid "ENABLE_USER_ERROR"
msgstr "Error while enabling user"

#: src/backend/controllers/user.py:337 src/backend/controllers/user.py:343
#: src/backend/models/user.py:222
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr "Error while updating user customers"

#: src/backend/controllers/verifier.py:56 src/backend/models/verifier.py:37
msgid "GET_INVOICE_BY_ID_ERROR"
msgstr "Error while retrieving invoice"

#: src/backend/controllers/verifier.py:167
#: src/backend/controllers/verifier.py:269
msgid "UPDATE_INVOICE_POSITIONS_ERROR"
msgstr "Error while updating invoice positions"

#: src/backend/controllers/verifier.py:190
#: src/backend/controllers/verifier.py:287
msgid "UPDATE_INVOICE_PAGES_ERROR"
msgstr "Error while updating invoice pages"

#: src/backend/controllers/verifier.py:213
#: src/backend/controllers/verifier.py:231
msgid "UPDATE_INVOICE_DATA_ERROR"
msgstr "Error while updating invoice datas"

#: src/backend/controllers/verifier.py:301
#: src/backend/controllers/verifier.py:307
msgid "DELETE_INVOICE_ERROR"
msgstr "Error while deleting invoice"

#: src/backend/controllers/verifier.py:322
#: src/backend/controllers/verifier.py:328
msgid "UPDATE_INVOICE_ERROR"
msgstr "Error while updating invoice"

#: src/backend/controllers/verifier.py:467
#: src/backend/controllers/verifier.py:470
#: src/backend/controllers/verifier.py:487
#: src/backend/controllers/verifier.py:506
#: src/backend/controllers/verifier.py:507
msgid "API_INSEE_ERROR_CONNEXION"
msgstr "Error while connecting to INSEE API"

#: src/backend/controllers/verifier.py:531
msgid "VAT_NOT_VALID"
msgstr "VAT number not valid"

#: src/backend/controllers/verifier.py:536
#: src/backend/controllers/verifier.py:537
msgid "VAT_API_ERROR"
msgstr "API for VAT number unreachable"

#: src/backend/models/accounts.py:96
msgid "SUPPLIER_UPDATE_ERROR"
msgstr "Error while updating supplier"

#: src/backend/models/artificial_intelligence.py:71
msgid "IA_MODEL_CREATE_ERROR"
msgstr "Error while creating ai models"

#: src/backend/models/artificial_intelligence.py:89
msgid "IA_MODEL_UPDATE_ERROR"
msgstr "Error while updating ai models"

#: src/backend/models/auth.py:40 src/backend/models/auth.py:92
#: src/backend/models/user.py:40 src/backend/rest/auth.py:70
msgid "BAD_USERNAME"
msgstr "Bad username"

#: src/backend/models/auth.py:42 src/backend/models/user.py:42
msgid "BAD_PASSWORD"
msgstr "Bad password"

#: src/backend/models/auth.py:44
msgid "USER_DELETED"
msgstr "User deleted"

#: src/backend/models/auth.py:46
msgid "USER_DISABLED"
msgstr "User disabled"

#: src/backend/models/auth.py:64 src/backend/models/auth.py:74
#: src/backend/models/roles.py:54
msgid "ROLE_DOESNT_EXISTS"
msgstr "Role doesn't exists"

#: src/backend/models/auth.py:147
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr "Error while updating login method"

#: src/backend/models/auth.py:187
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Error while disabling login method"

#: src/backend/models/auth.py:206
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Error while enabling login method"

#: src/backend/models/custom_fields.py:52
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr "Error while creating custom field"

#: src/backend/models/custom_fields.py:55
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr "Custom field already exist"

#: src/backend/models/custom_fields.py:97
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr "Error while updating custom fields"

#: src/backend/models/custom_fields.py:117
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr "Error while deleting custom field"

#: src/backend/models/doctypes.py:51
msgid "DOCTYPE_ALREADY_EXIST"
msgstr "Doctype already exist"

#: src/backend/models/doctypes.py:91
msgid "UPDATE_DOCTYPE_ERROR"
msgstr "Error while updating doctype"

#: src/backend/models/forms.py:77
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr "Error while retrieving form settings"

#: src/backend/models/forms.py:97
msgid "GET_DEFAULT_FORM_ERROR"
msgstr "Error while retrieving default form"

#: src/backend/models/forms.py:118
msgid "UPDATE_FORM_ERROR"
msgstr "Error while updating form"

#: src/backend/models/forms.py:137
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr "Error while updating form fields"

#: src/backend/models/forms.py:187
msgid "ADD_FORM_ERROR"
msgstr "Error while creating form"

#: src/backend/models/forms.py:190
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr "Form label already exist"

#: src/backend/models/inputs.py:54
msgid "INPUT_DOESNT_EXISTS"
msgstr "Input doesn't exists"

#: src/backend/models/inputs.py:90
msgid "INPUT_UPDATE_ERROR"
msgstr "Error while updating input"

#: src/backend/models/inputs.py:107
msgid "INPUT_CREATE_ERROR"
msgstr "Error while creating input"

#: src/backend/models/mailcollect.py:76
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr "Error while updating MailCollect process"

#: src/backend/models/outputs.py:69
msgid "OUTPUT_DOESNT_EXISTS"
msgstr "Output doesn't exists"

#: src/backend/models/outputs.py:89
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr "Output type doesn't exists"

#: src/backend/models/outputs.py:110
msgid "OUTPUT_UPDATE_ERROR"
msgstr "Error while updating output"

#: src/backend/models/outputs.py:127
msgid "OUTPUT_CREATE_ERROR"
msgstr "Error while creating output"

#: src/backend/models/positions_masks.py:57
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/models/positions_masks.py:78
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr "Error while updating positions mask"

#: src/backend/models/positions_masks.py:97
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr "Error while updating positions mask fields"

#: src/backend/models/positions_masks.py:129
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr "Error while creating positions mask"

#: src/backend/models/positions_masks.py:132
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr "Positions mask label already exists"

#: src/backend/models/privileges.py:35 src/backend/models/privileges.py:53
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr "Error while retrieving privileges"

#: src/backend/models/roles.py:111
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr "Error while updating role privileges"

#: src/backend/models/roles.py:130
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr "Error while creating role privileges"

#: src/backend/models/splitter.py:69
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr "Error while getting splitter index"

#: src/backend/models/splitter.py:110
msgid "UPDATE_SETTINGS_ERROR"
msgstr "Error while updating splitter settings"

#: src/backend/models/splitter.py:132
msgid "INSERT_PAGE_ERROR"
msgstr "Error while inserting splitter pages"

#: src/backend/models/splitter.py:193
msgid "GET_BATCH_ERROR"
msgstr "Error while getting splitter batches"

#: src/backend/models/splitter.py:213
msgid "GET_DOCUMENTS_ERROR"
msgstr "Error while getting splitter documents"

#: src/backend/models/splitter.py:232 src/backend/models/splitter.py:252
msgid "GET_PAGES_ERROR"
msgstr "Error while getting splitter pages"

#: src/backend/models/splitter.py:271
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr "Error while getting splitter source pages value"

#: src/backend/models/splitter.py:291
msgid "GET_DOCUMENT_ERROR"
msgstr "Error while retrieving document"

#: src/backend/models/splitter.py:310
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr "Error while getting splitter maximum index"

#: src/backend/models/status.py:37
msgid "NO_STATUS"
msgstr "No status"

#: src/backend/models/tasks_watcher.py:72
msgid "UPDATE_TASK_ERROR"
msgstr "Error while updating task"

#: src/backend/models/user.py:44
msgid "USER"
msgstr "User"

#: src/backend/models/user.py:44
msgid "ALREADY_REGISTERED"
msgstr "Already registered"

#: src/backend/models/user.py:142
msgid "GET_USER_BY_MAIL_ERROR"
msgstr "No user found with this email address"

#: src/backend/models/verifier.py:92 src/backend/models/verifier.py:110
msgid "INVOICE_UPDATE_ERROR"
msgstr "Error while updating invoice"

#: src/backend/rest/auth.py:45 src/backend/rest/auth.py:74
msgid "PGSQL_ERROR"
msgstr "Error while connecting to database"

#: src/backend/rest/auth.py:133 src/backend/rest/auth.py:161
#: src/backend/rest/auth.py:176
msgid "REQUEST_MODIFS_ERROR"
msgstr "Error in the database impossible to make the change"

#: src/backend/rest/auth.py:146
msgid "RETRIEVE_LOGIN_METHODS_ERROR"
msgstr "Error while retrieving loading methods"

#: src/backend/rest/splitter.py:42 src/backend/rest/verifier.py:37
msgid "UNKNOW_ERROR"
msgstr "Unknow error"

