# English translations for Open-Capture
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the project
# FIRST AUTHOR <nathan.cheval@edissyum.com>, 2021.
msgid ""
msgstr ""
"Project-Id-Version:  0.1\n"
"Report-Msgid-Bugs-To: nathan.cheval@edissyum.com\n"
"POT-Creation-Date: 2023-09-05 14:48+0200\n"
"PO-Revision-Date: 2019-09-02 17:48+0200\n"
"Last-Translator: Nathan CHEVAL <nathan.cheval@edissyum.com>\n"
"Language: en\n"
"Language-Team: en <nathan.cheval@edissyum.com>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.3\n"

#: custom/edissyum/src/backend/process_queue_splitter.py:212
#: custom/edissyum/src/backend/process_queue_verifier.py:184
#: custom/test/src/backend/process_queue_splitter.py:213
#: custom/test/src/backend/process_queue_verifier.py:184
msgid "FILE_UPLOADED_WORKFLOW"
msgstr "File uploaded successfully with workflow"

#: src/backend/functions.py:37 src/backend/functions.py:50
#: src/backend/functions.py:52 src/backend/functions.py:60
#: src/backend/functions.py:61
msgid "NO_DATA_OR_DATA_MISSING"
msgstr "No data or data missing"

#: src/backend/functions.py:45
msgid "JSON_ERROR"
msgstr "JSON construction error"

#: src/backend/scripting_functions.py:84
msgid "WORFKLOW_NOT_FOUND"
msgstr "Workflow doesn't exists"

#: src/backend/splitter_exports.py:95
msgid "OUTPUT_NOT_FOUND"
msgstr "Output not found"

#: src/backend/models/outputs.py:101 src/backend/splitter_exports.py:123
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr "Output type doesn't exists"

#: src/backend/splitter_exports.py:170 src/backend/splitter_exports.py:273
msgid "EXPORT_PDF_ERROR"
msgstr "Error while exporting PDF"

#: src/backend/splitter_exports.py:241 src/backend/splitter_exports.py:296
msgid "EXPORT_XML_ERROR"
msgstr "Error while exporting XML"

#: src/backend/splitter_exports.py:316
msgid "CHECK_FOLDER_ERROR"
msgstr "Check folder error"

#: src/backend/splitter_exports.py:317
msgid "FOLDER_DOES_NOT_EXIST"
msgstr "Folder does not exist"

#: src/backend/splitter_exports.py:335
msgid "OPENADS_ADD_DOC_ERROR"
msgstr "OpenADS add document error"

#: src/backend/verifier_exports.py:151 src/backend/verifier_exports.py:154
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Destination folder for XML doesn't exists"

#: src/backend/verifier_exports.py:353 src/backend/verifier_exports.py:356
#: src/backend/verifier_exports.py:423 src/backend/verifier_exports.py:426
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Destination folder for PDF doesn't exists"

#: src/backend/verifier_exports.py:586 src/backend/verifier_exports.py:592
#: src/backend/verifier_exports.py:598
msgid "EXPORT_MEM_ERROR"
msgstr "Error during MEM Courrier export"

#: src/backend/verifier_exports.py:593
msgid "PDF_FILE_NOT_FOUND"
msgstr "PDF file not found"

#: src/backend/verifier_exports.py:604
msgid "MEM_WS_INFO_WRONG"
msgstr "MEM Courrier informations are wrong"

#: src/backend/verifier_exports.py:610
msgid "MEM_WS_INFO_EMPTY"
msgstr "MEM Courrier informations are empty"

#: src/backend/classes/MEMWebServices.py:40
msgid "HOST_NOT_FOUND"
msgstr "Host not found"

#: src/backend/classes/SMTP.py:223
msgid "RESET_PASSWORD"
msgstr "Reset password"

#: src/backend/classes/SMTP.py:225
msgid "FORGOT_EMAIL_HEADER"
msgstr ""
"Hello,<br/><br/>You requested to reset your Open-Capture account "
"password.<br/><br/>To change it, please click on the link below :<br/>"

#: src/backend/classes/SMTP.py:225
msgid "CLICK_HERE"
msgstr "Click here"

#: src/backend/classes/SMTP.py:225
msgid "FORGOT_EMAIL_FOOTER"
msgstr ""
"<br/><br/>If you did not requested this action, you can ignore this "
"email.<br/><br/>"

#: src/backend/classes/SMTP.py:242
msgid "SMTP_TEST_SEND"
msgstr "Test email sent"

#: src/backend/classes/SMTP.py:243
msgid "SMTP_TEST_SEND_BODY"
msgstr "This is a test email sent by Open-Capture"

#: src/backend/controllers/accounts.py:71 src/backend/models/accounts.py:61
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr "Error retrieving supplier"

#: src/backend/controllers/accounts.py:84
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr "Error retrieving address"

#: src/backend/controllers/accounts.py:111
#: src/backend/controllers/accounts.py:239
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr "Error updating supplier positions"

#: src/backend/controllers/accounts.py:138
#: src/backend/controllers/accounts.py:270
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr "Error update supplier pages"

#: src/backend/controllers/accounts.py:196
msgid "SUPPLIER_UPDATED"
msgstr "Supplier updated&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:202
#: src/backend/controllers/accounts.py:208
msgid "UPDATE_SUPPLIER_ERROR"
msgstr "Error updating supplier"

#: src/backend/controllers/accounts.py:294
#: src/backend/controllers/accounts.py:300
#: src/backend/controllers/accounts.py:325
#: src/backend/controllers/accounts.py:332 src/backend/models/accounts.py:127
msgid "UPDATE_ADDRESS_ERROR"
msgstr "Error updating address"

#: src/backend/controllers/accounts.py:356 src/backend/models/accounts.py:147
msgid "CREATE_ADDRESS_ERROR"
msgstr "Error creating address"

#: src/backend/controllers/accounts.py:401
msgid "SUPPLIER_CREATED"
msgstr "Supplier created&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:409
#: src/backend/controllers/accounts.py:415 src/backend/models/accounts.py:167
msgid "CREATE_SUPPLIER_ERROR"
msgstr "Error creating supplier"

#: src/backend/controllers/accounts.py:416
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A supplier already exists with this vat number"

#: src/backend/controllers/accounts.py:453 src/backend/controllers/user.py:248
#: src/backend/controllers/user.py:278 src/backend/models/accounts.py:231
#: src/backend/models/accounts.py:254 src/backend/models/accounts.py:273
#: src/backend/models/user.py:210
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr "Error retrieving customer"

#: src/backend/controllers/accounts.py:497
msgid "CUSTOMER_UPDATED"
msgstr "Customer updated&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:502
#: src/backend/controllers/accounts.py:508 src/backend/models/accounts.py:295
msgid "UPDATE_CUSTOMER_ERROR"
msgstr "Error updating customer"

#: src/backend/controllers/accounts.py:536
msgid "CUSTOMER_CREATED"
msgstr "Customer created&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:544
#: src/backend/controllers/accounts.py:550 src/backend/models/accounts.py:315
msgid "CREATE_CUSTOMER_ERROR"
msgstr "Error creating customer"

#: src/backend/controllers/accounts.py:551
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A customer already exists with this vat number"

#: src/backend/controllers/accounts.py:567
msgid "CUSTOMER_DELETED"
msgstr "Customer deleted&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:572
#: src/backend/controllers/accounts.py:578 src/backend/models/accounts.py:337
msgid "DELETE_CUSTOMER_ERROR"
msgstr "Error deleting customer"

#: src/backend/controllers/accounts.py:595
msgid "SUPPLIER_DELETED"
msgstr "Supplier deleted&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:600
#: src/backend/controllers/accounts.py:606 src/backend/models/accounts.py:189
msgid "DELETE_SUPPLIER_ERROR"
msgstr "Error deleting supplier"

#: src/backend/controllers/accounts.py:624
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr "Error while loading supplier referencial"

#: src/backend/controllers/artificial_intelligence.py:74
#: src/backend/controllers/artificial_intelligence.py:371
#: src/backend/controllers/artificial_intelligence.py:397
msgid "GET_IA_MODEL_BY_ID_ERROR"
msgstr "Error retrieving ai model"

#: src/backend/controllers/artificial_intelligence.py:98
msgid "CREATE_IA_MODEL_ERROR"
msgstr "Error creating ai models"

#: src/backend/controllers/artificial_intelligence.py:120
msgid "DELETE_AI_MODEL"
msgstr "Delete AI model&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:155
msgid "UPDATE_AI_MODEL"
msgstr "Update AI model&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:160
msgid "UPDATE_IA_MODEL_ERROR"
msgstr "Error updating ai model"

#: src/backend/controllers/artificial_intelligence.py:222
msgid "CREATE_AI_MODEL"
msgstr "Create AI model&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:372
#: src/backend/controllers/artificial_intelligence.py:398
#: src/backend/models/artificial_intelligence.py:59
msgid "IA_MODEL_DOESNT_EXISTS"
msgstr "AI model doesn't exists"

#: src/backend/controllers/artificial_intelligence.py:433
msgid "RENAME_AI_MODEL_ERROR"
msgstr "Error renaming ai models"

#: src/backend/controllers/artificial_intelligence.py:434
msgid "FILE_DOESNT_EXISTS"
msgstr "The AI file doesn't exists"

#: src/backend/controllers/auth.py:66 src/backend/controllers/auth.py:317
#: src/backend/controllers/auth.py:373 src/backend/controllers/auth.py:383
#: src/backend/controllers/auth.py:393 src/backend/controllers/auth.py:438
msgid "JWT_ERROR"
msgstr "Authentification by token error"

#: src/backend/controllers/auth.py:185
msgid "RESET_JWT_ERROR"
msgstr "Reset JWT error"

#: src/backend/controllers/auth.py:194
msgid "UNIQUE_URL_JWT_ERROR"
msgstr "Unique URL JWT error"

#: src/backend/controllers/auth.py:228
msgid "LOGOUT"
msgstr "Log out"

#: src/backend/controllers/auth.py:235 src/backend/controllers/auth.py:250
#: src/backend/controllers/auth.py:296 src/backend/controllers/auth.py:349
#: src/backend/controllers/auth.py:469 src/backend/controllers/auth.py:480
#: src/backend/controllers/auth.py:490 src/backend/controllers/auth.py:517
#: src/backend/rest/auth.py:83
msgid "LOGIN_ERROR"
msgstr "Login error"

#: src/backend/controllers/auth.py:251
msgid "USER_WEBSERVICE"
msgstr "The user couldn't connect to the application (webservice user)"

#: src/backend/controllers/auth.py:291 src/backend/controllers/auth.py:344
msgid "LOGIN"
msgstr "User log in"

#: src/backend/controllers/auth.py:383
msgid "AUTHORIZATION_HEADER_INCORRECT"
msgstr "The authorization header is incorrect (missing 'Bearer' or 'Basic')"

#: src/backend/controllers/auth.py:393
msgid "ACCOUNT_ALREADY_LOGGED"
msgstr ""
"Your account is already log in another machine. Only one connection is "
"allowed per account"

#: src/backend/controllers/auth.py:425
msgid "FIRSTNAME"
msgstr "Firstname"

#: src/backend/controllers/auth.py:440 src/backend/controllers/auth.py:445
msgid "REST_ERROR"
msgstr "Authentification by webservice user error"

#: src/backend/controllers/auth.py:441
msgid "USER_DO_NOT_EXISTS"
msgstr "User does not exist"

#: src/backend/controllers/auth.py:445
msgid "PASSWORD_INCORRECT"
msgstr "Incorrect password"

#: src/backend/controllers/auth.py:450
msgid "AUTH_ERROR"
msgstr "Authentification error"

#: src/backend/controllers/auth.py:450
msgid "VALID_TOKEN_OR_USER_WS_MANDATORY"
msgstr "Valid token or webservice user is mandatory"

#: src/backend/controllers/auth.py:481
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr "Several authentication methods are enabled"

#: src/backend/controllers/auth.py:505
msgid "LDAP_ERROR"
msgstr "LDAP error"

#: src/backend/controllers/auth.py:506 src/backend/models/auth.py:140
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr "No LDAP configurations found"

#: src/backend/controllers/auth.py:532
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr "Error while loading login methods"

#: src/backend/controllers/auth.py:544
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr "Error while disabling login methods"

#: src/backend/controllers/auth.py:556
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr "Error while enabling login methods"

#: src/backend/controllers/auth.py:586 src/backend/controllers/auth.py:773
#: src/backend/controllers/auth.py:829 src/backend/controllers/auth.py:844
#: src/backend/controllers/auth.py:852 src/backend/controllers/auth.py:858
msgid "LDAP_CONNECTION_ERROR"
msgstr "Unable to connect to LDAP server"

#: src/backend/controllers/auth.py:587
msgid "LOGIN_LDAP_ERROR"
msgstr "Error while logging using LDAP"

#: src/backend/controllers/auth.py:761 src/backend/controllers/auth.py:767
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr "Synchronization's informations are incorrect"

#: src/backend/controllers/auth.py:763 src/backend/controllers/auth.py:769
#: src/backend/controllers/auth.py:775 src/backend/controllers/auth.py:781
#: src/backend/controllers/auth.py:787
msgid "LDAP_SYNCHRO_ERROR"
msgstr "Error while syncing LDAP"

#: src/backend/controllers/auth.py:779 src/backend/controllers/auth.py:785
#: src/backend/controllers/auth.py:864 src/backend/rest/auth.py:183
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr "Missing informations"

#: src/backend/controllers/auth.py:827 src/backend/controllers/auth.py:842
#: src/backend/controllers/auth.py:850
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr "Incorrect information"

#: src/backend/controllers/auth.py:862 src/backend/rest/auth.py:184
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr "One or more information are missing to establish the connection"

#: src/backend/controllers/config.py:64
msgid "LANGUAGE_CHANGED"
msgstr "Change language to&nbsp;<strong>%(lang)s</strong>"

#: src/backend/controllers/config.py:79
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr "Error while retrieving configuration"

#: src/backend/controllers/config.py:109
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr "Error while retrieving configurations"

#: src/backend/controllers/config.py:139
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr "Error while retrieving docservers"

#: src/backend/controllers/config.py:177
msgid "RETRIEVE_REGEX_ERRORS"
msgstr "Error while retrieving regex"

#: src/backend/controllers/config.py:189 src/backend/controllers/config.py:218
#: src/backend/controllers/config.py:230 src/backend/controllers/config.py:257
#: src/backend/models/config.py:199 src/backend/models/config.py:223
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr "Error while updating configuration"

#: src/backend/controllers/config.py:190 src/backend/controllers/config.py:231
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr "The value of token expiration could'nt be 0 or less"

#: src/backend/controllers/config.py:213 src/backend/controllers/config.py:252
msgid "UPDATE_CONFIGURATION"
msgstr "Configuration updated&nbsp;<strong>%(config)s</strong>"

#: src/backend/controllers/config.py:280
msgid "UPDATE_REGEX"
msgstr "Regex updated&nbsp;<strong>%(regex)s</strong>"

#: src/backend/controllers/config.py:285 src/backend/models/config.py:245
msgid "UPDATE_REGEX_ERROR"
msgstr "Error while updating REGEX"

#: src/backend/controllers/config.py:307
msgid "UPDATE_DOCSERVER"
msgstr "Docserver updated&nbsp;<strong>%(docserver)s</strong>"

#: src/backend/controllers/config.py:312 src/backend/models/config.py:271
msgid "UPDATE_DOCSERVER_ERROR"
msgstr "Error while updating docserver"

#: src/backend/controllers/config.py:354 src/backend/controllers/config.py:370
#: src/backend/controllers/config.py:375
msgid "ERROR_UPDATING_IMAGE"
msgstr "Error while updating login image"

#: src/backend/controllers/config.py:355 src/backend/controllers/config.py:371
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr "Custom image path is not writeable"

#: src/backend/controllers/config.py:365
msgid "UPDATE_LOGIN_IMAGE"
msgstr "Login image updated"

#: src/backend/controllers/config.py:376
msgid "CUSTOM_NOT_PRESENT"
msgstr "No custom is present"

#: src/backend/controllers/custom_fields.py:33
#: src/backend/controllers/custom_fields.py:49
#: src/backend/controllers/custom_fields.py:62
msgid "CUSTOM_FIELDS_ERROR"
msgstr "Custom fields error"

#: src/backend/controllers/custom_fields.py:75
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr "Error while deleting custom field"

#: src/backend/controllers/doctypes.py:39
#: src/backend/controllers/doctypes.py:81 src/backend/models/doctypes.py:131
#: src/backend/models/doctypes.py:134
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr "Error while updating default doctype"

#: src/backend/controllers/doctypes.py:45 src/backend/models/doctypes.py:51
msgid "ADD_DOCTYPE_ERROR"
msgstr "Error while adding doctype"

#: src/backend/controllers/doctypes.py:65
#: src/backend/controllers/doctypes.py:101
#: src/backend/controllers/doctypes.py:114
#: src/backend/controllers/doctypes.py:166
#: src/backend/controllers/doctypes.py:197
#: src/backend/controllers/doctypes.py:236
#: src/backend/controllers/doctypes.py:265
#: src/backend/controllers/doctypes.py:291
#: src/backend/controllers/doctypes.py:320 src/backend/controllers/user.py:556
msgid "DOCTYPE_ERROR"
msgstr "Doctype error"

#: src/backend/controllers/doctypes.py:133
msgid "BUNDLESEPARATOR"
msgstr "SEPARATEUR DE LOT / BUNDLE SEPARATOR"

#: src/backend/controllers/doctypes.py:140
msgid "DOCUMENTSEPARATOR"
msgstr "SEPARATEUR DE DOCUMENT / DOCUMENT SEPARATOR"

#: src/backend/controllers/doctypes.py:159
msgid "DOCTYPESEPARATOR"
msgstr "SEPARATEUR AVEC TYPE DE DOCUMENT / SEPARATOR WITH DOCUMENT TYPE"

#: src/backend/controllers/forms.py:72 src/backend/controllers/forms.py:106
#: src/backend/controllers/forms.py:229
msgid "FORMS_ERROR"
msgstr "Forms error"

#: src/backend/controllers/forms.py:101
msgid "CREATE_FORM"
msgstr "Form created&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:121 src/backend/controllers/forms.py:170
#: src/backend/models/forms.py:66
msgid "GET_FORM_BY_ID_ERROR"
msgstr "Error retrieving form"

#: src/backend/controllers/forms.py:153
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr "Error retrieving form fields"

#: src/backend/controllers/forms.py:218
msgid "UPDATE_FORM"
msgstr "Form updated&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:223 src/backend/controllers/forms.py:381
#: src/backend/controllers/forms.py:387
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr "Error updating form fields"

#: src/backend/controllers/forms.py:245
msgid "DELETE_FORM"
msgstr "Form deleted&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:250 src/backend/controllers/forms.py:256
msgid "DELETE_FORM_ERROR"
msgstr "Error deleting form"

#: src/backend/controllers/forms.py:265 src/backend/controllers/outputs.py:66
#: src/backend/controllers/positions_masks.py:165
#: src/backend/controllers/workflow.py:112
msgid "COPY_OF"
msgstr "Copy of"

#: src/backend/controllers/forms.py:286
msgid "DUPLICATE_FORM"
msgstr "Form duplicated&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:291 src/backend/controllers/forms.py:297
msgid "DUPLICATE_FORM_ERROR"
msgstr "Error duplicating form"

#: src/backend/controllers/forms.py:313
msgid "DISABLE_FORM"
msgstr "Form disabled&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:318 src/backend/controllers/forms.py:324
msgid "DISABLE_FORM_ERROR"
msgstr "Error disabling form"

#: src/backend/controllers/forms.py:340
msgid "ENABLE_FORM"
msgstr "Form enabled&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:345 src/backend/controllers/forms.py:351
msgid "ENABLE_FORM_ERROR"
msgstr "Error enabling form"

#: src/backend/controllers/forms.py:367
msgid "GET_FORMS_FIELDS_ERROR"
msgstr "Error while retrieving form fields"

#: src/backend/controllers/history.py:31
msgid "ADD_HISTORY_ERROR"
msgstr "Error while adding new history"

#: src/backend/controllers/mailcollect.py:38
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr "Error while retrieving MailCollect processes"

#: src/backend/controllers/mailcollect.py:53
msgid "UPDATE_MAILCOLLECT_PROCESS"
msgstr "MailCollect process updated&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:61
msgid "UPDATE_PROCESS_ERROR"
msgstr "Error while updating MailCollect process"

#: src/backend/controllers/mailcollect.py:76
msgid "CREATE_MAILCOLLECT_PROCESS"
msgstr "MailCollect process created&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:84
msgid "CREATE_PROCESS_ERROR"
msgstr "Error while creating MailCollect process"

#: src/backend/controllers/mailcollect.py:100
msgid "DELETE_MAILCOLLECT_PROCESS"
msgstr "MailCollect process deleted&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:105
#: src/backend/controllers/mailcollect.py:111
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while deleting MailCollect process"

#: src/backend/controllers/mailcollect.py:127
msgid "ENABLE_MAILCOLLECT_PROCESS"
msgstr "MailCollect process enabled&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:132
#: src/backend/controllers/mailcollect.py:138
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while enabling MailCollect process"

#: src/backend/controllers/mailcollect.py:154
msgid "DISABLE_MAILCOLLECT_PROCESS"
msgstr "MailCollect process disabled&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:159
#: src/backend/controllers/mailcollect.py:165
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while disabling MailCollect process"

#: src/backend/controllers/mailcollect.py:179
#: src/backend/controllers/mailcollect.py:189
msgid "MAILCOLLECT_ERROR"
msgstr "MailCollect error"

#: src/backend/controllers/outputs.py:75
msgid "DUPLICATE_OUTPUT"
msgstr "Output duplicated&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:80 src/backend/controllers/outputs.py:86
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr "Error while duplicate ouput"

#: src/backend/controllers/outputs.py:115
#: src/backend/controllers/outputs.py:144
#: src/backend/controllers/outputs.py:150
msgid "UPDATE_OUTPUT_ERROR"
msgstr "Error while updating output"

#: src/backend/controllers/outputs.py:116
msgid "NOT_ALLOWED_OUTPUT_PATH"
msgstr "Output path is not allowed"

#: src/backend/controllers/outputs.py:139
msgid "UPDATE_OUTPUT"
msgstr "Output updated&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:173
msgid "CREATE_OUTPUT"
msgstr "Output created&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:181
msgid "CREATE_OUTPUT_ERROR"
msgstr "Error while creating output"

#: src/backend/controllers/outputs.py:194
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr "Error while retrieving output"

#: src/backend/controllers/outputs.py:207
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr "Error while retrieving output type"

#: src/backend/controllers/outputs.py:223
msgid "DELETE_OUTPUT"
msgstr "Output deleted&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:228
#: src/backend/controllers/outputs.py:234
msgid "DELETE_OUTPUT_ERROR"
msgstr "Error while deleting output"

#: src/backend/controllers/outputs.py:262
#: src/backend/controllers/outputs.py:271
#: src/backend/controllers/outputs.py:278
msgid "OUTPUT_FOLDER_CREATION_ERROR"
msgstr "Error while creating output folder"

#: src/backend/controllers/outputs.py:263
#: src/backend/controllers/workflow.py:57
msgid "FOLDER_NOT_ALLOWED_ERROR"
msgstr "Capture path not allowed"

#: src/backend/controllers/outputs.py:272
#: src/backend/controllers/workflow.py:66
#: src/backend/controllers/workflow.py:327
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr "Cannot create folder because of permission issue"

#: src/backend/controllers/outputs.py:279
#: src/backend/controllers/workflow.py:73
msgid "CAN_NOT_ACCESS_FOLDER_PERMISSION_ERROR"
msgstr "Cannot create folder because of permission issue"

#: src/backend/controllers/positions_masks.py:43
#: src/backend/controllers/positions_masks.py:74
#: src/backend/controllers/positions_masks.py:123
#: src/backend/controllers/positions_masks.py:129
msgid "POSITION_MASKS_ERROR"
msgstr "Position masks error"

#: src/backend/controllers/positions_masks.py:65
msgid "CREATE_POSITIONS_MASK"
msgstr "Position mask created&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:89
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/controllers/positions_masks.py:118
msgid "UPDATE_POSITIONS_MASK"
msgstr "Position mask updated&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:145
#: src/backend/controllers/positions_masks.py:230
msgid "DELETE_POSITIONS_MASK"
msgstr "Position mask deleted&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:150
#: src/backend/controllers/positions_masks.py:156
msgid "DELETE_POSITION_MASK_ERROR"
msgstr "Error while deleting positions mask"

#: src/backend/controllers/positions_masks.py:181
#: src/backend/controllers/positions_masks.py:187
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr "Error while duplicating positions mask"

#: src/backend/controllers/positions_masks.py:203
msgid "DISABLE_POSITIONS_MASK"
msgstr "Position mask disabled&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:208
#: src/backend/controllers/positions_masks.py:214
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr "Error while disabling positions mask"

#: src/backend/controllers/positions_masks.py:235
#: src/backend/controllers/positions_masks.py:241
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr "Error while enabling positions mask"

#: src/backend/controllers/positions_masks.py:264
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updating positions mask positions"

#: src/backend/controllers/positions_masks.py:287
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updateing positions mask pages"

#: src/backend/controllers/positions_masks.py:305
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask positions"

#: src/backend/controllers/positions_masks.py:323
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask pages"

#: src/backend/controllers/privileges.py:38
#: src/backend/controllers/privileges.py:66
#: src/backend/controllers/privileges.py:94
msgid "GET_PRIVILEGES_ERROR"
msgstr "Error while retrieving privileges"

#: src/backend/controllers/roles.py:39 src/backend/controllers/user.py:122
#: src/backend/controllers/user.py:138 src/backend/controllers/user.py:219
#: src/backend/models/user.py:140 src/backend/models/user.py:187
msgid "GET_USER_BY_ID_ERROR"
msgstr "Error while retrieving user"

#: src/backend/controllers/roles.py:49 src/backend/controllers/roles.py:169
msgid "GET_ROLE_BY_ID_ERROR"
msgstr "Error while retrieving role"

#: src/backend/controllers/roles.py:88
msgid "UPDATE_ROLE"
msgstr "Role updated&nbsp;<strong>{{ role }}</strong>"

#: src/backend/controllers/roles.py:93 src/backend/controllers/roles.py:99
#: src/backend/controllers/roles.py:150 src/backend/controllers/roles.py:156
#: src/backend/models/roles.py:85
msgid "UPDATE_ROLE_ERROR"
msgstr "Error while trying to update role"

#: src/backend/controllers/roles.py:121
msgid "CREATE_ROLE"
msgstr "New role created&nbsp;<strong>%(role)s</strong>"

#: src/backend/controllers/roles.py:130 src/backend/models/roles.py:105
msgid "CREATE_ROLE_ERROR"
msgstr "Error while creating role"

#: src/backend/controllers/roles.py:185
msgid "DELETE_ROLE"
msgstr "Role&nbsp;<strong>%(role)s</strong> deleted"

#: src/backend/controllers/roles.py:190 src/backend/controllers/roles.py:196
msgid "DELETE_ROLE_ERROR"
msgstr "Error while deleting role"

#: src/backend/controllers/roles.py:210 src/backend/controllers/roles.py:216
msgid "DISABLE_ROLE_ERROR"
msgstr "Error while disabling role"

#: src/backend/controllers/roles.py:230 src/backend/controllers/roles.py:236
msgid "ENABLE_ROLE_ERROR"
msgstr "Error while enabling role"

#: src/backend/controllers/smtp.py:49
msgid "SMTP_TEST_SEND_EMAIL_ERROR"
msgstr "Error while sending test email"

#: src/backend/controllers/smtp.py:55
msgid "SMTP_TEST_CONNECTION_ERROR"
msgstr "Error while connecting to SMTP"

#: src/backend/controllers/splitter.py:114
msgid "LOAD_METADATA_ERROR"
msgstr "Error while loading metada"

#: src/backend/controllers/splitter.py:170
#: src/backend/controllers/verifier.py:125
msgid "AT"
msgstr "at"

#: src/backend/controllers/splitter.py:194
msgid "FORM_UNDEFINED"
msgstr "Form undefined"

#: src/backend/controllers/splitter.py:197
msgid "CUSTOMER_UNDEFINED"
msgstr "Customer undefined"

#: src/backend/controllers/splitter.py:255
#: src/backend/controllers/splitter.py:286
msgid "BATCH_NOT_FOUND"
msgstr "Batch not found"

#: src/backend/controllers/splitter.py:256
#: src/backend/controllers/splitter.py:287
msgid "BATCH_ID_NOT_FOUND"
msgstr "Batch %(id)s not found"

#: src/backend/controllers/splitter.py:270
msgid "DELETE_BATCH_SUCCESS"
msgstr "Deletion of batch n°<strong>%(batch_id)s</strong>"

#: src/backend/controllers/splitter.py:275
#: src/backend/controllers/splitter.py:296
#: src/backend/controllers/verifier.py:766
msgid "UPDATE_STATUS_ERROR"
msgstr "Error while updating status"

#: src/backend/controllers/splitter.py:331
#: src/backend/controllers/verifier.py:402
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr "Error while removing lock"

#: src/backend/controllers/splitter.py:433
msgid "ADD_DOCUMENT_ERROR"
msgstr "Error while adding document"

#: src/backend/controllers/splitter.py:459
msgid "UPDATE_BATCH_ERROR"
msgstr "Error while updating batch"

#: src/backend/controllers/splitter.py:472
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr "Error while updating document"

#: src/backend/controllers/splitter.py:485
#: src/backend/controllers/verifier.py:379
#: src/backend/controllers/verifier.py:385
msgid "UPDATE_DOCUMENT_ERROR"
msgstr "Error while updating document"

#: src/backend/controllers/splitter.py:500
#: src/backend/controllers/splitter.py:521
#: src/backend/controllers/splitter.py:536
#: src/backend/controllers/splitter.py:551
msgid "UPDATE_PAGES_ERROR"
msgstr "Error while updating pages"

#: src/backend/controllers/splitter.py:565
msgid "CMIS_CONNECTION_ERROR"
msgstr "Error while connecting to CMIS"

#: src/backend/controllers/splitter.py:578
msgid "OPENADS_CONNECTION_ERROR"
msgstr "OpenADS connection error"

#: src/backend/controllers/splitter.py:678
#: src/backend/controllers/verifier.py:745 src/backend/models/splitter.py:572
#: src/backend/models/verifier.py:195
msgid "GET_TOTALS_ERROR"
msgstr "Error while retrievings totals"

#: src/backend/controllers/splitter.py:777
msgid "GET_BATCH_OUTPUTS_ERROR"
msgstr "Error while retrieving output"

#: src/backend/controllers/status.py:31
msgid "RETRIEVES_STATUS_ERROR"
msgstr "Error while retrieving status"

#: src/backend/controllers/user.py:73
msgid "CREATE_USER"
msgstr "User created&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:78
msgid "CREATE_USER_ERROR"
msgstr "Error while creating user"

#: src/backend/controllers/user.py:155
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr "Error while retrieving user"

#: src/backend/controllers/user.py:181
msgid "USER_FORGOT_SUCCESS"
msgstr ""
"Password reset email sent successfully for "
"user&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:186
msgid "SEND_EMAIL_FORGOT_PASSWORD_ERROR"
msgstr "Error sending password reset email"

#: src/backend/controllers/user.py:209
msgid "USER_RESET_PASSWORD_SUCCESS"
msgstr "User&nbsp;<strong>%(user)s</strong> reset password successfully"

#: src/backend/controllers/user.py:213 src/backend/controllers/user.py:218
msgid "RESET_PASSWORD_ERROR"
msgstr "Erreur while reseting password"

#: src/backend/controllers/user.py:214
msgid "RESET_TOKEN_MISMATCH"
msgstr "Reset token mismatch. Maybe the token is expired"

#: src/backend/controllers/user.py:299
msgid "UPDATE_PROFILE"
msgstr "Update profile"

#: src/backend/controllers/user.py:300
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr "The old password do not match"

#: src/backend/controllers/user.py:306
msgid "UPDATE_USER"
msgstr "Update user"

#: src/backend/controllers/user.py:307
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr "Password do not match"

#: src/backend/controllers/user.py:337
msgid "USER_UPDATED"
msgstr "User updated&nbsp<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:342 src/backend/controllers/user.py:348
#: src/backend/models/user.py:255 src/backend/models/user.py:321
msgid "UPDATE_USER_ERROR"
msgstr "Error while updating user"

#: src/backend/controllers/user.py:364
msgid "DELETE_USER"
msgstr "User deleted&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:372 src/backend/controllers/user.py:378
msgid "DELETE_USER_ERROR"
msgstr "Error while deleting user"

#: src/backend/controllers/user.py:394
msgid "DISABLE_USER"
msgstr "User disabled&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:402 src/backend/controllers/user.py:408
msgid "DISABLE_USER_ERROR"
msgstr "Error while disabling user"

#: src/backend/controllers/user.py:424
msgid "ENABLE_USER"
msgstr "User enabled&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:432 src/backend/controllers/user.py:438
msgid "ENABLE_USER_ERROR"
msgstr "Error while enabling user"

#: src/backend/controllers/user.py:455 src/backend/controllers/user.py:461
#: src/backend/models/user.py:277
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr "Error while updating user customers"

#: src/backend/controllers/user.py:476 src/backend/controllers/user.py:483
#: src/backend/models/user.py:299
msgid "UPDATE_FORMS_USER_ERROR"
msgstr "Error while updating user forms"

#: src/backend/controllers/user.py:527
msgid "USER_EXPORT_ERROR"
msgstr "Error while exporting users"

#: src/backend/controllers/user.py:572
msgid "GET_DEFAULT_ROUTE_ERROR"
msgstr "Error while retrieving default route"

#: src/backend/controllers/verifier.py:89 src/backend/models/splitter.py:219
#: src/backend/models/verifier.py:40
msgid "GET_DOCUMENT_BY_ID_ERROR"
msgstr "Error while retrieving document"

#: src/backend/controllers/verifier.py:106 src/backend/models/verifier.py:64
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR"
msgstr "Error while retrieving document using token"

#: src/backend/controllers/verifier.py:107
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR_MESSAGE"
msgstr "No document found with this token"

#: src/backend/controllers/verifier.py:217
#: src/backend/controllers/verifier.py:319
msgid "UPDATE_DOCUMENT_POSITIONS_ERROR"
msgstr "Error while updating document positions"

#: src/backend/controllers/verifier.py:240
#: src/backend/controllers/verifier.py:337
msgid "UPDATE_DOCUMENT_PAGES_ERROR"
msgstr "Error while updating document pages"

#: src/backend/controllers/verifier.py:263
#: src/backend/controllers/verifier.py:281
msgid "UPDATE_DOCUMENT_DATA_ERROR"
msgstr "Error while updating document datas"

#: src/backend/controllers/verifier.py:353
msgid "DELETE_DOCUMENT_SUCCESS"
msgstr "Deletion of document n°<strong>%(document_id)s</strong>"

#: src/backend/controllers/verifier.py:358
#: src/backend/controllers/verifier.py:364
msgid "DELETE_DOCUMENT_ERROR"
msgstr "Error while deleting document"

#: src/backend/controllers/verifier.py:492
#: src/backend/controllers/workflow.py:430 src/backend/process/main.py:41
msgid "SCRIPT_CONTAINS_NOT_ALLOWED_CODE"
msgstr "Script contains not allowed code :"

#: src/backend/controllers/verifier.py:638
#: src/backend/controllers/verifier.py:641
#: src/backend/controllers/verifier.py:658
#: src/backend/controllers/verifier.py:684
#: src/backend/controllers/verifier.py:685
msgid "API_INSEE_ERROR_CONNEXION"
msgstr "Error while connecting to INSEE API"

#: src/backend/controllers/verifier.py:715
msgid "VAT_NOT_VALID"
msgstr "VAT number not valid"

#: src/backend/controllers/verifier.py:722
#: src/backend/controllers/verifier.py:723
msgid "VAT_API_ERROR"
msgstr "API for VAT number unreachable"

#: src/backend/controllers/verifier.py:756
msgid "DOCUMENT_NOT_FOUND"
msgstr "document not found"

#: src/backend/controllers/verifier.py:757
msgid "DOCUMENT_ID_NOT_FOUND"
msgstr "document %(id)s not found"

#: src/backend/controllers/verifier.py:812
msgid "NO_FORM"
msgstr "No form associated"

#: src/backend/controllers/workflow.py:56
#: src/backend/controllers/workflow.py:65
#: src/backend/controllers/workflow.py:72
msgid "WORKFLOW_FOLDER_CREATION_ERROR"
msgstr "Error while creating input folder"

#: src/backend/controllers/workflow.py:87
msgid "GET_WORKFLOW_BY_ID_ERROR"
msgstr "Error while retrieving workflow"

#: src/backend/controllers/workflow.py:100
msgid "GET_WORKFLOW_BY_WORKFLOW_ID_ERROR"
msgstr "Error while retrieving workflow"

#: src/backend/controllers/workflow.py:125
msgid "DUPLICATE_WORKFLOW"
msgstr "Workflow duplicated&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:130
#: src/backend/controllers/workflow.py:136
msgid "DUPLICATE_WORKFLOW_ERROR"
msgstr "Error duplicating workflow"

#: src/backend/controllers/workflow.py:161
#: src/backend/controllers/workflow.py:173
#: src/backend/controllers/workflow.py:184
#: src/backend/controllers/workflow.py:208
msgid "CREATE_WORKFLOW_ERROR"
msgstr "Error while creating workflow"

#: src/backend/controllers/workflow.py:162
#: src/backend/controllers/workflow.py:218
msgid "NOT_ALLOWED_INPUT_PATH"
msgstr "The input path is not allowed"

#: src/backend/controllers/workflow.py:174
msgid "WORKFLOW_ID_ALREADY_EXISTS"
msgstr "The label short already exists"

#: src/backend/controllers/workflow.py:185
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr "The document capture path is already set in another workflow"

#: src/backend/controllers/workflow.py:200
msgid "CREATE_WORKFLOW"
msgstr "Workflow created&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:217
#: src/backend/controllers/workflow.py:245
#: src/backend/controllers/workflow.py:251
msgid "UPDATE_WORKFLOW_ERROR"
msgstr "Error while trying to update workflow"

#: src/backend/controllers/workflow.py:240
msgid "UPDATE_WORKFLOW"
msgstr "Workflow updated&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:268
msgid "DELETE_WORKFLOW"
msgstr "Workflow deleted&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:273
#: src/backend/controllers/workflow.py:279
msgid "DELETE_WORKFLOW_ERROR"
msgstr "Error while deleting workflow"

#: src/backend/controllers/workflow.py:326
#: src/backend/controllers/workflow.py:348
msgid "FS_WATCHER_CREATION_ERROR"
msgstr "Error while creating fs watcher settings"

#: src/backend/controllers/workflow.py:349
#: src/backend/controllers/workflow.py:402
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr "Fs watcher config doesnt exists"

#: src/backend/controllers/workflow.py:354
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr "Script sample doesn't exists"

#: src/backend/controllers/workflow.py:360
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr "Script folder doesn't exists"

#: src/backend/controllers/workflow.py:401
msgid "FS_WATCHER_DELETION_ERROR"
msgstr "Error while deleting fs watcher settings"

#: src/backend/controllers/workflow.py:415
msgid "LINE"
msgstr "Line"

#: src/backend/controllers/workflow.py:416
msgid "COLUMN"
msgstr "column"

#: src/backend/models/accounts.py:105
msgid "SUPPLIER_UPDATE_ERROR"
msgstr "Error while updating supplier"

#: src/backend/models/artificial_intelligence.py:80
msgid "IA_MODEL_CREATE_ERROR"
msgstr "Error while creating ai models"

#: src/backend/models/artificial_intelligence.py:101
msgid "IA_MODEL_UPDATE_ERROR"
msgstr "Error while updating ai models"

#: src/backend/models/auth.py:43 src/backend/models/auth.py:101
#: src/backend/models/user.py:43 src/backend/rest/auth.py:84
msgid "BAD_USERNAME"
msgstr "Bad username"

#: src/backend/models/auth.py:45 src/backend/models/user.py:45
msgid "BAD_PASSWORD"
msgstr "Bad password"

#: src/backend/models/auth.py:47
msgid "USER_DELETED"
msgstr "User deleted"

#: src/backend/models/auth.py:49
msgid "USER_DISABLED"
msgstr "User disabled"

#: src/backend/models/auth.py:70 src/backend/models/auth.py:80
#: src/backend/models/roles.py:61
msgid "ROLE_DOESNT_EXISTS"
msgstr "Role doesn't exists"

#: src/backend/models/auth.py:165
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr "Error while updating login method"

#: src/backend/models/auth.py:211
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Error while disabling login method"

#: src/backend/models/auth.py:233
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Error while enabling login method"

#: src/backend/models/custom_fields.py:57
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr "Error while creating custom field"

#: src/backend/models/custom_fields.py:60
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr "Custom field already exist"

#: src/backend/models/custom_fields.py:110
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr "Error while updating custom fields"

#: src/backend/models/custom_fields.py:133
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr "Error while deleting custom field"

#: src/backend/models/doctypes.py:54
msgid "DOCTYPE_ALREADY_EXIST"
msgstr "Doctype already exist"

#: src/backend/models/doctypes.py:100
msgid "UPDATE_DOCTYPE_ERROR"
msgstr "Error while updating doctype"

#: src/backend/models/forms.py:45
msgid "GET_FORMS_ERROR"
msgstr "Error while retrieving forms"

#: src/backend/models/forms.py:89
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr "Error while retrieving form settings"

#: src/backend/models/forms.py:112
msgid "GET_DEFAULT_FORM_ERROR"
msgstr "Error while retrieving default form"

#: src/backend/models/forms.py:136
msgid "UPDATE_FORM_ERROR"
msgstr "Error while updating form"

#: src/backend/models/forms.py:158
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr "Error while updating form fields"

#: src/backend/models/forms.py:215
msgid "ADD_FORM_ERROR"
msgstr "Error while creating form"

#: src/backend/models/forms.py:218
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr "Form label already exist"

#: src/backend/models/mailcollect.py:85
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr "Error while updating MailCollect process"

#: src/backend/models/outputs.py:78
msgid "OUTPUT_DOESNT_EXISTS"
msgstr "Output doesn't exists"

#: src/backend/models/outputs.py:125
msgid "OUTPUT_UPDATE_ERROR"
msgstr "Error while updating output"

#: src/backend/models/outputs.py:145
msgid "OUTPUT_CREATE_ERROR"
msgstr "Error while creating output"

#: src/backend/models/positions_masks.py:63
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/models/positions_masks.py:87
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr "Error while updating positions mask"

#: src/backend/models/positions_masks.py:109
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr "Error while updating positions mask fields"

#: src/backend/models/positions_masks.py:144
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr "Error while creating positions mask"

#: src/backend/models/positions_masks.py:147
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr "Positions mask label already exists"

#: src/backend/models/privileges.py:38 src/backend/models/privileges.py:59
#: src/backend/models/privileges.py:83
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr "Error while retrieving privileges"

#: src/backend/models/roles.py:127
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr "Error while updating role privileges"

#: src/backend/models/roles.py:149
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr "Error while creating role privileges"

#: src/backend/models/splitter.py:78
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr "Error while getting splitter index"

#: src/backend/models/splitter.py:125
msgid "UPDATE_SETTINGS_ERROR"
msgstr "Error while updating splitter settings"

#: src/backend/models/splitter.py:150
msgid "INSERT_PAGE_ERROR"
msgstr "Error while inserting splitter pages"

#: src/backend/models/splitter.py:244
msgid "GET_DOCUMENTS_ERROR"
msgstr "Error while getting splitter documents"

#: src/backend/models/splitter.py:266 src/backend/models/splitter.py:289
msgid "GET_PAGES_ERROR"
msgstr "Error while getting splitter pages"

#: src/backend/models/splitter.py:311
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr "Error while getting splitter source pages value"

#: src/backend/models/splitter.py:334
msgid "GET_DOCUMENT_ERROR"
msgstr "Error while retrieving document"

#: src/backend/models/splitter.py:356
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr "Error while getting splitter maximum index"

#: src/backend/models/status.py:40
msgid "NO_STATUS"
msgstr "No status"

#: src/backend/models/user.py:47
msgid "USER"
msgstr "User"

#: src/backend/models/user.py:47
msgid "ALREADY_REGISTERED"
msgstr "Already registered"

#: src/backend/models/user.py:163
msgid "GET_USER_BY_MAIL_ERROR"
msgstr "No user found with this email address"

#: src/backend/models/user.py:232
msgid "GET_FORMS_BY_USER_ID_ERROR"
msgstr "Error while retrieving forms by user"

#: src/backend/models/verifier.py:128 src/backend/models/verifier.py:149
msgid "DOCUMENT_UPDATE_ERROR"
msgstr "Error while updating document"

#: src/backend/models/workflow.py:60 src/backend/models/workflow.py:83
msgid "WORKFLOW_DOESNT_EXISTS"
msgstr "Workflow doesn't exists"

#: src/backend/models/workflow.py:105
msgid "WORKFLOW_CREATE_ERROR"
msgstr "Error while creating workflow"

#: src/backend/models/workflow.py:127
msgid "WORKFLOW_UPDATE_ERROR"
msgstr "Error while updating workflow"

#: src/backend/rest/accounts.py:35 src/backend/rest/accounts.py:56
#: src/backend/rest/accounts.py:69 src/backend/rest/accounts.py:81
#: src/backend/rest/accounts.py:118 src/backend/rest/accounts.py:140
#: src/backend/rest/accounts.py:162 src/backend/rest/accounts.py:175
#: src/backend/rest/accounts.py:189 src/backend/rest/accounts.py:210
#: src/backend/rest/accounts.py:221 src/backend/rest/accounts.py:232
#: src/backend/rest/accounts.py:243 src/backend/rest/accounts.py:263
#: src/backend/rest/accounts.py:283 src/backend/rest/accounts.py:295
#: src/backend/rest/accounts.py:305 src/backend/rest/accounts.py:316
#: src/backend/rest/accounts.py:328 src/backend/rest/accounts.py:339
#: src/backend/rest/accounts.py:383
#: src/backend/rest/artificial_intelligence.py:30
#: src/backend/rest/artificial_intelligence.py:40
#: src/backend/rest/artificial_intelligence.py:51
#: src/backend/rest/artificial_intelligence.py:61
#: src/backend/rest/artificial_intelligence.py:72
#: src/backend/rest/artificial_intelligence.py:90
#: src/backend/rest/artificial_intelligence.py:105
#: src/backend/rest/artificial_intelligence.py:117 src/backend/rest/auth.py:114
#: src/backend/rest/auth.py:164 src/backend/rest/auth.py:174
#: src/backend/rest/auth.py:194 src/backend/rest/auth.py:205
#: src/backend/rest/auth.py:228 src/backend/rest/auth.py:247
#: src/backend/rest/config.py:31 src/backend/rest/config.py:41
#: src/backend/rest/config.py:51 src/backend/rest/config.py:61
#: src/backend/rest/config.py:72 src/backend/rest/config.py:82
#: src/backend/rest/config.py:92 src/backend/rest/config.py:109
#: src/backend/rest/config.py:120 src/backend/rest/config.py:131
#: src/backend/rest/config.py:143 src/backend/rest/custom_fields.py:32
#: src/backend/rest/custom_fields.py:46 src/backend/rest/custom_fields.py:57
#: src/backend/rest/custom_fields.py:68 src/backend/rest/custom_fields.py:78
#: src/backend/rest/doctypes.py:31 src/backend/rest/doctypes.py:47
#: src/backend/rest/doctypes.py:58 src/backend/rest/doctypes.py:69
#: src/backend/rest/doctypes.py:80 src/backend/rest/doctypes.py:90
#: src/backend/rest/doctypes.py:101 src/backend/rest/doctypes.py:116
#: src/backend/rest/forms.py:32 src/backend/rest/forms.py:46
#: src/backend/rest/forms.py:58 src/backend/rest/forms.py:91
#: src/backend/rest/forms.py:102 src/backend/rest/forms.py:114
#: src/backend/rest/forms.py:125 src/backend/rest/forms.py:137
#: src/backend/rest/forms.py:148 src/backend/rest/forms.py:159
#: src/backend/rest/forms.py:170 src/backend/rest/forms.py:182
#: src/backend/rest/history.py:39 src/backend/rest/history.py:49
#: src/backend/rest/history.py:59 src/backend/rest/locale.py:31
#: src/backend/rest/mailcollect.py:29 src/backend/rest/mailcollect.py:45
#: src/backend/rest/mailcollect.py:56 src/backend/rest/mailcollect.py:72
#: src/backend/rest/mailcollect.py:86 src/backend/rest/mailcollect.py:97
#: src/backend/rest/mailcollect.py:108 src/backend/rest/monitoring.py:29
#: src/backend/rest/monitoring.py:39 src/backend/rest/monitoring.py:49
#: src/backend/rest/monitoring.py:60 src/backend/rest/outputs.py:32
#: src/backend/rest/outputs.py:45 src/backend/rest/outputs.py:64
#: src/backend/rest/outputs.py:76 src/backend/rest/outputs.py:88
#: src/backend/rest/outputs.py:101 src/backend/rest/outputs.py:113
#: src/backend/rest/outputs.py:125 src/backend/rest/outputs.py:136
#: src/backend/rest/positions_masks.py:33
#: src/backend/rest/positions_masks.py:43
#: src/backend/rest/positions_masks.py:54
#: src/backend/rest/positions_masks.py:65
#: src/backend/rest/positions_masks.py:77
#: src/backend/rest/positions_masks.py:89
#: src/backend/rest/positions_masks.py:101
#: src/backend/rest/positions_masks.py:112
#: src/backend/rest/positions_masks.py:123
#: src/backend/rest/positions_masks.py:134
#: src/backend/rest/positions_masks.py:145
#: src/backend/rest/positions_masks.py:157 src/backend/rest/privileges.py:29
#: src/backend/rest/privileges.py:39 src/backend/rest/roles.py:43
#: src/backend/rest/roles.py:53 src/backend/rest/roles.py:64
#: src/backend/rest/roles.py:75 src/backend/rest/roles.py:85
#: src/backend/rest/roles.py:95 src/backend/rest/roles.py:105
#: src/backend/rest/splitter.py:30 src/backend/rest/splitter.py:52
#: src/backend/rest/splitter.py:62 src/backend/rest/splitter.py:72
#: src/backend/rest/splitter.py:83 src/backend/rest/splitter.py:98
#: src/backend/rest/splitter.py:109 src/backend/rest/splitter.py:119
#: src/backend/rest/splitter.py:130 src/backend/rest/splitter.py:144
#: src/backend/rest/splitter.py:155 src/backend/rest/splitter.py:166
#: src/backend/rest/splitter.py:177 src/backend/rest/splitter.py:196
#: src/backend/rest/splitter.py:207 src/backend/rest/splitter.py:222
#: src/backend/rest/splitter.py:225 src/backend/rest/splitter.py:243
#: src/backend/rest/splitter.py:255 src/backend/rest/splitter.py:266
#: src/backend/rest/splitter.py:277 src/backend/rest/splitter.py:287
#: src/backend/rest/splitter.py:298 src/backend/rest/status.py:31
#: src/backend/rest/user.py:30 src/backend/rest/user.py:41
#: src/backend/rest/user.py:66 src/backend/rest/user.py:76
#: src/backend/rest/user.py:108 src/backend/rest/user.py:119
#: src/backend/rest/user.py:129 src/backend/rest/user.py:139
#: src/backend/rest/user.py:156 src/backend/rest/user.py:167
#: src/backend/rest/user.py:177 src/backend/rest/user.py:188
#: src/backend/rest/user.py:203 src/backend/rest/verifier.py:45
#: src/backend/rest/verifier.py:96 src/backend/rest/verifier.py:108
#: src/backend/rest/verifier.py:129 src/backend/rest/verifier.py:142
#: src/backend/rest/verifier.py:154 src/backend/rest/verifier.py:166
#: src/backend/rest/verifier.py:179 src/backend/rest/verifier.py:192
#: src/backend/rest/verifier.py:205 src/backend/rest/verifier.py:218
#: src/backend/rest/verifier.py:231 src/backend/rest/verifier.py:244
#: src/backend/rest/verifier.py:255 src/backend/rest/verifier.py:274
#: src/backend/rest/verifier.py:293 src/backend/rest/verifier.py:313
#: src/backend/rest/verifier.py:325 src/backend/rest/verifier.py:337
#: src/backend/rest/verifier.py:360 src/backend/rest/verifier.py:378
#: src/backend/rest/verifier.py:390 src/backend/rest/verifier.py:401
#: src/backend/rest/verifier.py:414 src/backend/rest/verifier.py:427
#: src/backend/rest/verifier.py:438 src/backend/rest/verifier.py:451
#: src/backend/rest/verifier.py:462 src/backend/rest/verifier.py:477
#: src/backend/rest/workflow.py:32 src/backend/rest/workflow.py:44
#: src/backend/rest/workflow.py:57 src/backend/rest/workflow.py:71
#: src/backend/rest/workflow.py:83 src/backend/rest/workflow.py:95
#: src/backend/rest/workflow.py:107 src/backend/rest/workflow.py:119
#: src/backend/rest/workflow.py:132 src/backend/rest/workflow.py:145
#: src/backend/rest/workflow.py:156
msgid "UNAUTHORIZED_ROUTE"
msgstr "You are not authorized to access this route"

#: src/backend/rest/accounts.py:44 src/backend/rest/accounts.py:104
#: src/backend/rest/accounts.py:126 src/backend/rest/accounts.py:148
#: src/backend/rest/auth.py:39 src/backend/rest/auth.py:101
#: src/backend/rest/auth.py:123 src/backend/rest/auth.py:143
#: src/backend/rest/auth.py:235 src/backend/rest/auth.py:254
#: src/backend/rest/outputs.py:144 src/backend/rest/workflow.py:163
msgid "BAD_REQUEST"
msgstr "Bad request"

#: src/backend/rest/auth.py:59 src/backend/rest/auth.py:88
msgid "PGSQL_ERROR"
msgstr "Error while connecting to database"

#: src/backend/rest/auth.py:210
msgid "REQUEST_MODIFS_ERROR"
msgstr "Error in the database impossible to make the change"

#: src/backend/rest/monitoring.py:65 src/backend/rest/verifier.py:121
msgid "TOKEN_IS_MANDATORY"
msgstr "Valid token is mandatory"

#: src/backend/rest/splitter.py:45 src/backend/rest/verifier.py:89
msgid "UNKNOW_ERROR"
msgstr "Unknow error"

#: src/backend/rest/verifier.py:50
msgid "VERIFIER_UPLOAD_ERROR"
msgstr "Error while uploading file(s)"

#: src/backend/rest/verifier.py:51
msgid "WORKFLOW_ID_IS_MANDATORY"
msgstr "Workflow id is mandatory"

#: src/backend/rest/verifier.py:84
msgid "UNIQUE_URL_TOKEN_GENERATION_ERROR"
msgstr "Error while generating unique url token"

#: src/backend/rest/verifier.py:85
msgid "INTERFACE_IS_NOT_USED_OR_FORM_UNIQUE_URL_NOT_SET"
msgstr ""
"Interface use is not set in workflow or unique url settings is malformed "
"on the form"

