# English translations for Open-Capture
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the project
# FIRST AUTHOR <nathan.cheval@edissyum.com>, 2021.
msgid ""
msgstr ""
"Project-Id-Version:  0.1\n"
"Report-Msgid-Bugs-To: nathan.cheval@edissyum.com\n"
"POT-Creation-Date: 2023-05-24 14:23+0200\n"
"PO-Revision-Date: 2019-09-02 17:48+0200\n"
"Last-Translator: Nathan CHEVAL <nathan.cheval@edissyum.com>\n"
"Language: en\n"
"Language-Team: en <nathan.cheval@edissyum.com>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.12.1\n"

#: launch_worker.py:64 launch_worker_splitter.py:64
msgid "FILE_UPLOADED_WORKFLOW"
msgstr "File uploaded successfully via fs-watcher with workflow"

#: src/backend/verifier_exports.py:152 src/backend/verifier_exports.py:155
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Destination folder for XML doesn't exists"

#: src/backend/verifier_exports.py:354 src/backend/verifier_exports.py:357
#: src/backend/verifier_exports.py:424 src/backend/verifier_exports.py:427
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Destination folder for PDF doesn't exists"

#: src/backend/controllers/splitter.py:462
#: src/backend/controllers/splitter.py:468 src/backend/verifier_exports.py:585
#: src/backend/verifier_exports.py:591 src/backend/verifier_exports.py:597
msgid "EXPORT_MEM_ERROR"
msgstr "Error during MEM Courrier export"

#: src/backend/verifier_exports.py:592
msgid "PDF_FILE_NOT_FOUND"
msgstr "PDF file not found"

#: src/backend/verifier_exports.py:603
msgid "MEM_WS_INFO_WRONG"
msgstr "MEM Courrier informations are wrong"

#: src/backend/controllers/splitter.py:474 src/backend/verifier_exports.py:609
msgid "MEM_WS_INFO_EMPTY"
msgstr "MEM Courrier informations are empty"

#: src/backend/classes/MEMWebServices.py:39
msgid "HOST_NOT_FOUND"
msgstr "Host not found"

#: src/backend/classes/SMTP.py:223
msgid "RESET_PASSWORD"
msgstr "Reset password"

#: src/backend/classes/SMTP.py:225
msgid "FORGOT_EMAIL_HEADER"
msgstr ""
"Hello,<br/><br/>You requested to reset your Open-Capture account "
"password.<br/><br/>To change it, please click on the link below :<br/>"

#: src/backend/classes/SMTP.py:225
msgid "CLICK_HERE"
msgstr "Click here"

#: src/backend/classes/SMTP.py:225
msgid "FORGOT_EMAIL_FOOTER"
msgstr ""
"<br/><br/>If you did not requested this action, you can ignore this "
"email.<br/><br/>"

#: src/backend/classes/SMTP.py:242
msgid "SMTP_TEST_SEND"
msgstr "Test email sent"

#: src/backend/classes/SMTP.py:243
msgid "SMTP_TEST_SEND_BODY"
msgstr "This is a test email sent by Open-Capture"

#: src/backend/controllers/accounts.py:63 src/backend/models/accounts.py:61
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr "Error retrieving supplier"

#: src/backend/controllers/accounts.py:76
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr "Error retrieving address"

#: src/backend/controllers/accounts.py:103
#: src/backend/controllers/accounts.py:222
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr "Error updating supplier positions"

#: src/backend/controllers/accounts.py:130
#: src/backend/controllers/accounts.py:253
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr "Error update supplier pages"

#: src/backend/controllers/accounts.py:185
#: src/backend/controllers/accounts.py:191
msgid "UPDATE_SUPPLIER_ERROR"
msgstr "Error updating supplier"

#: src/backend/controllers/accounts.py:277
#: src/backend/controllers/accounts.py:283
#: src/backend/controllers/accounts.py:307
#: src/backend/controllers/accounts.py:313 src/backend/models/accounts.py:127
msgid "UPDATE_ADDRESS_ERROR"
msgstr "Error updating address"

#: src/backend/controllers/accounts.py:337 src/backend/models/accounts.py:147
msgid "CREATE_ADDRESS_ERROR"
msgstr "Error creating address"

#: src/backend/controllers/accounts.py:382
#: src/backend/controllers/accounts.py:388 src/backend/models/accounts.py:167
msgid "CREATE_SUPPLIER_ERROR"
msgstr "Error creating supplier"

#: src/backend/controllers/accounts.py:389
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A supplier already exists with this vat number"

#: src/backend/controllers/accounts.py:426 src/backend/controllers/user.py:219
#: src/backend/controllers/user.py:249 src/backend/models/accounts.py:231
#: src/backend/models/accounts.py:254 src/backend/models/accounts.py:273
#: src/backend/models/user.py:210
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr "Error retrieving customer"

#: src/backend/controllers/accounts.py:468
#: src/backend/controllers/accounts.py:474 src/backend/models/accounts.py:295
msgid "UPDATE_CUSTOMER_ERROR"
msgstr "Error updating customer"

#: src/backend/controllers/accounts.py:503
#: src/backend/controllers/accounts.py:509 src/backend/models/accounts.py:315
msgid "CREATE_CUSTOMER_ERROR"
msgstr "Error creating customer"

#: src/backend/controllers/accounts.py:510
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "A customer already exists with this vat number"

#: src/backend/controllers/accounts.py:524
#: src/backend/controllers/accounts.py:530 src/backend/models/accounts.py:337
msgid "DELETE_CUSTOMER_ERROR"
msgstr "Error deleting customer"

#: src/backend/controllers/accounts.py:545
#: src/backend/controllers/accounts.py:551 src/backend/models/accounts.py:189
msgid "DELETE_SUPPLIER_ERROR"
msgstr "Error deleting supplier"

#: src/backend/controllers/accounts.py:573
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr "Error while loading supplier referencial"

#: src/backend/controllers/artificial_intelligence.py:79
#: src/backend/controllers/artificial_intelligence.py:403
msgid "GET_IA_MODEL_BY_ID_ERROR"
msgstr "Error retrieving ai model"

#: src/backend/controllers/artificial_intelligence.py:103
msgid "CREATE_IA_MODEL_ERROR"
msgstr "Error creating ai models"

#: src/backend/controllers/artificial_intelligence.py:128
msgid "UPDATE_IA_MODEL_ERROR"
msgstr "Error updating ai model"

#: src/backend/controllers/artificial_intelligence.py:404
#: src/backend/models/artificial_intelligence.py:59
msgid "IA_MODEL_DOESNT_EXISTS"
msgstr "AI model doesn't exists"

#: src/backend/controllers/auth.py:66 src/backend/controllers/auth.py:301
#: src/backend/controllers/auth.py:345 src/backend/controllers/auth.py:355
#: src/backend/controllers/auth.py:365 src/backend/controllers/auth.py:404
#: src/backend/controllers/auth.py:415
msgid "JWT_ERROR"
msgstr "Authentification by token error"

#: src/backend/controllers/auth.py:185
msgid "RESET_JWT_ERROR"
msgstr "Reset JWT error"

#: src/backend/controllers/auth.py:194
msgid "UNIQUE_URL_JWT_ERROR"
msgstr "Unique URL JWT error"

#: src/backend/controllers/auth.py:227 src/backend/controllers/auth.py:242
#: src/backend/controllers/auth.py:280 src/backend/controllers/auth.py:325
#: src/backend/controllers/auth.py:434 src/backend/controllers/auth.py:445
#: src/backend/controllers/auth.py:455 src/backend/controllers/auth.py:482
#: src/backend/rest/auth.py:69
msgid "LOGIN_ERROR"
msgstr "Login error"

#: src/backend/controllers/auth.py:243
msgid "USER_WEBSERVICE"
msgstr "The user couldn't connect to the application (webservice user)"

#: src/backend/controllers/auth.py:355
msgid "AUTHORIZATION_HEADER_INCORRECT"
msgstr "The authorization header is incorrect (missing 'Bearer' or 'Basic')"

#: src/backend/controllers/auth.py:365
msgid "ACCOUNT_ALREADY_LOGGED"
msgstr ""
"Your account is already log in another machine. Only one connection is "
"allowed per account"

#: src/backend/controllers/auth.py:406 src/backend/controllers/auth.py:411
msgid "REST_ERROR"
msgstr "Authentification by webservice user error"

#: src/backend/controllers/auth.py:407
msgid "USER_DO_NOT_EXISTS"
msgstr "User does not exist"

#: src/backend/controllers/auth.py:411
msgid "PASSWORD_INCORRECT"
msgstr "Incorrect password"

#: src/backend/controllers/auth.py:415
msgid "VALID_TOKEN_MANDATORY"
msgstr "Valid token is mandatory"

#: src/backend/controllers/auth.py:446
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr "Several authentication methods are enabled"

#: src/backend/controllers/auth.py:470
msgid "LDAP_ERROR"
msgstr "LDAP error"

#: src/backend/controllers/auth.py:471 src/backend/models/auth.py:140
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr "No LDAP configurations found"

#: src/backend/controllers/auth.py:497
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr "Error while loading login methods"

#: src/backend/controllers/auth.py:509
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr "Error while disabling login methods"

#: src/backend/controllers/auth.py:521
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr "Error while enabling login methods"

#: src/backend/controllers/auth.py:544 src/backend/controllers/auth.py:729
#: src/backend/controllers/auth.py:785 src/backend/controllers/auth.py:800
#: src/backend/controllers/auth.py:808 src/backend/controllers/auth.py:814
msgid "LDAP_CONNECTION_ERROR"
msgstr "Unable to connect to LDAP server"

#: src/backend/controllers/auth.py:545
msgid "LOGIN_LDAP_ERROR"
msgstr "Error while logging using LDAP"

#: src/backend/controllers/auth.py:717 src/backend/controllers/auth.py:723
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr "Synchronization's informations are incorrect"

#: src/backend/controllers/auth.py:719 src/backend/controllers/auth.py:725
#: src/backend/controllers/auth.py:731 src/backend/controllers/auth.py:737
#: src/backend/controllers/auth.py:743
msgid "LDAP_SYNCHRO_ERROR"
msgstr "Error while syncing LDAP"

#: src/backend/controllers/auth.py:735 src/backend/controllers/auth.py:741
#: src/backend/controllers/auth.py:820 src/backend/rest/auth.py:133
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr "Missing informations"

#: src/backend/controllers/auth.py:783 src/backend/controllers/auth.py:798
#: src/backend/controllers/auth.py:806
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr "Incorrect information"

#: src/backend/controllers/auth.py:818 src/backend/rest/auth.py:134
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr "One or more information are missing to establish the connection"

#: src/backend/controllers/config.py:71
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr "Error while retrieving configuration"

#: src/backend/controllers/config.py:101
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr "Error while retrieving configurations"

#: src/backend/controllers/config.py:131
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr "Error while retrieving docservers"

#: src/backend/controllers/config.py:169
msgid "RETRIEVE_REGEX_ERRORS"
msgstr "Error while retrieving regex"

#: src/backend/controllers/config.py:181 src/backend/controllers/config.py:201
#: src/backend/controllers/config.py:213 src/backend/controllers/config.py:233
#: src/backend/models/config.py:199 src/backend/models/config.py:223
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr "Error while updating configuration"

#: src/backend/controllers/config.py:182 src/backend/controllers/config.py:214
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr "The value of token expiration could'nt be 0 or less"

#: src/backend/controllers/config.py:254 src/backend/models/config.py:245
msgid "UPDATE_REGEX_ERROR"
msgstr "Error while updating REGEX"

#: src/backend/controllers/config.py:274 src/backend/models/config.py:271
msgid "UPDATE_DOCSERVER_ERROR"
msgstr "Error while updating docserver"

#: src/backend/controllers/config.py:316 src/backend/controllers/config.py:326
#: src/backend/controllers/config.py:331
msgid "ERROR_UPDATING_IMAGE"
msgstr "Error while updating login image"

#: src/backend/controllers/config.py:317 src/backend/controllers/config.py:327
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr "Custom image path is not writeable"

#: src/backend/controllers/config.py:332
msgid "CUSTOM_NOT_PRESENT"
msgstr "No custom is present"

#: src/backend/controllers/custom_fields.py:33
#: src/backend/controllers/custom_fields.py:49
#: src/backend/controllers/custom_fields.py:62
msgid "CUSTOM_FIELDS_ERROR"
msgstr "Custom fields error"

#: src/backend/controllers/custom_fields.py:75
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr "Error while deleting custom field"

#: src/backend/controllers/doctypes.py:34
#: src/backend/controllers/doctypes.py:76 src/backend/models/doctypes.py:131
#: src/backend/models/doctypes.py:134
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr "Error while updating default doctype"

#: src/backend/controllers/doctypes.py:40 src/backend/models/doctypes.py:51
msgid "ADD_DOCTYPE_ERROR"
msgstr "Error while adding doctype"

#: src/backend/controllers/doctypes.py:60
#: src/backend/controllers/doctypes.py:96
#: src/backend/controllers/doctypes.py:109
#: src/backend/controllers/doctypes.py:161
#: src/backend/controllers/doctypes.py:192
msgid "DOCTYPE_ERROR"
msgstr "Doctype error"

#: src/backend/controllers/doctypes.py:128
msgid "BUNDLESEPARATOR"
msgstr "SEPARATEUR DE LOT / BUNDLE SEPARATOR"

#: src/backend/controllers/doctypes.py:135
msgid "DOCUMENTSEPARATOR"
msgstr "SEPARATEUR DE DOCUMENT / DOCUMENT SEPARATOR"

#: src/backend/controllers/doctypes.py:154
msgid "DOCTYPESEPARATOR"
msgstr "SEPARATEUR AVEC TYPE DE DOCUMENT / SEPARATOR WITH DOCUMENT TYPE"

#: src/backend/controllers/forms.py:71 src/backend/controllers/forms.py:97
#: src/backend/controllers/forms.py:214
msgid "FORMS_ERROR"
msgstr "Forms error"

#: src/backend/controllers/forms.py:112 src/backend/controllers/forms.py:161
#: src/backend/models/forms.py:66
msgid "GET_FORM_BY_ID_ERROR"
msgstr "Error retrieving form"

#: src/backend/controllers/forms.py:144
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr "Error retrieving form fields"

#: src/backend/controllers/forms.py:208 src/backend/controllers/forms.py:337
#: src/backend/controllers/forms.py:343
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr "Error updating form fields"

#: src/backend/controllers/forms.py:228 src/backend/controllers/forms.py:234
msgid "DELETE_FORM_ERROR"
msgstr "Error deleting form"

#: src/backend/controllers/forms.py:243 src/backend/controllers/outputs.py:65
#: src/backend/controllers/positions_masks.py:144
#: src/backend/controllers/workflow.py:106
msgid "COPY_OF"
msgstr "Copy of"

#: src/backend/controllers/forms.py:261 src/backend/controllers/forms.py:267
msgid "DUPLICATE_FORM_ERROR"
msgstr "Error duplicating form"

#: src/backend/controllers/forms.py:281 src/backend/controllers/forms.py:287
msgid "DISABLE_FORM_ERROR"
msgstr "Error disabling form"

#: src/backend/controllers/forms.py:301 src/backend/controllers/forms.py:307
msgid "ENABLE_FORM_ERROR"
msgstr "Error enabling form"

#: src/backend/controllers/forms.py:323
msgid "GET_FORMS_FIELDS_ERROR"
msgstr "Error while retrieving form fields"

#: src/backend/controllers/history.py:36
msgid "ADD_HISTORY_ERROR"
msgstr "Error while adding new history"

#: src/backend/controllers/mailcollect.py:36
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr "Error while retrieving MailCollect processes"

#: src/backend/controllers/mailcollect.py:52
msgid "UPDATE_PROCESS_ERROR"
msgstr "Error while updating MailCollect process"

#: src/backend/controllers/mailcollect.py:68
msgid "CREATE_PROCESS_ERROR"
msgstr "Error while creating MailCollect process"

#: src/backend/controllers/mailcollect.py:82
#: src/backend/controllers/mailcollect.py:88
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while deleting MailCollect process"

#: src/backend/controllers/mailcollect.py:102
#: src/backend/controllers/mailcollect.py:108
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while enabling MailCollect process"

#: src/backend/controllers/mailcollect.py:122
#: src/backend/controllers/mailcollect.py:128
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Error while disabling MailCollect process"

#: src/backend/controllers/mailcollect.py:142
#: src/backend/controllers/mailcollect.py:152
msgid "MAILCOLLECT_ERROR"
msgstr "MailCollect error"

#: src/backend/controllers/outputs.py:72 src/backend/controllers/outputs.py:78
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr "Error while duplicate ouput"

#: src/backend/controllers/outputs.py:107
#: src/backend/controllers/outputs.py:129
#: src/backend/controllers/outputs.py:135
msgid "UPDATE_OUTPUT_ERROR"
msgstr "Error while updating output"

#: src/backend/controllers/outputs.py:108
msgid "NOT_ALLOWED_OUTPUT_PATH"
msgstr "Output path is not allowed"

#: src/backend/controllers/outputs.py:159
msgid "CREATE_OUTPUT_ERROR"
msgstr "Error while creating output"

#: src/backend/controllers/outputs.py:172
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr "Error while retrieving output"

#: src/backend/controllers/outputs.py:185
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr "Error while retrieving output type"

#: src/backend/controllers/outputs.py:199
#: src/backend/controllers/outputs.py:205
msgid "DELETE_OUTPUT_ERROR"
msgstr "Error while deleting output"

#: src/backend/controllers/positions_masks.py:43
#: src/backend/controllers/positions_masks.py:67
#: src/backend/controllers/positions_masks.py:109
#: src/backend/controllers/positions_masks.py:115
msgid "POSITION_MASKS_ERROR"
msgstr "Position masks error"

#: src/backend/controllers/positions_masks.py:82
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/controllers/positions_masks.py:129
#: src/backend/controllers/positions_masks.py:135
msgid "DELETE_POSITION_MASK_ERROR"
msgstr "Error while deleting positions mask"

#: src/backend/controllers/positions_masks.py:160
#: src/backend/controllers/positions_masks.py:166
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr "Error while duplicating positions mask"

#: src/backend/controllers/positions_masks.py:180
#: src/backend/controllers/positions_masks.py:186
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr "Error while disabling positions mask"

#: src/backend/controllers/positions_masks.py:200
#: src/backend/controllers/positions_masks.py:206
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr "Error while enabling positions mask"

#: src/backend/controllers/positions_masks.py:229
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updating positions mask positions"

#: src/backend/controllers/positions_masks.py:252
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Error while updateing positions mask pages"

#: src/backend/controllers/positions_masks.py:270
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask positions"

#: src/backend/controllers/positions_masks.py:288
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr "Error wile deleting positions mask pages"

#: src/backend/controllers/privileges.py:38
#: src/backend/controllers/privileges.py:66
#: src/backend/controllers/privileges.py:94
msgid "GET_PRIVILEGES_ERROR"
msgstr "Error while retrieving privileges"

#: src/backend/controllers/roles.py:56 src/backend/controllers/roles.py:62
#: src/backend/controllers/roles.py:104 src/backend/controllers/roles.py:110
#: src/backend/models/roles.py:84
msgid "UPDATE_ROLE_ERROR"
msgstr "Error while trying to update role"

#: src/backend/controllers/roles.py:84 src/backend/models/roles.py:104
msgid "CREATE_ROLE_ERROR"
msgstr "Error while creating role"

#: src/backend/controllers/roles.py:123
msgid "GET_ROLE_BY_ID_ERROR"
msgstr "Error while retrieving role"

#: src/backend/controllers/roles.py:137 src/backend/controllers/roles.py:143
msgid "DELETE_ROLE_ERROR"
msgstr "Error while deleting role"

#: src/backend/controllers/roles.py:157 src/backend/controllers/roles.py:163
msgid "DISABLE_ROLE_ERROR"
msgstr "Error while disabling role"

#: src/backend/controllers/roles.py:177 src/backend/controllers/roles.py:183
msgid "ENABLE_ROLE_ERROR"
msgstr "Error while enabling role"

#: src/backend/controllers/smtp.py:49
msgid "SMTP_TEST_SEND_EMAIL_ERROR"
msgstr "Error while sending test email"

#: src/backend/controllers/smtp.py:55
msgid "SMTP_TEST_CONNECTION_ERROR"
msgstr "Error while connecting to SMTP"

#: src/backend/controllers/splitter.py:113
msgid "LOAD_METADATA_ERROR"
msgstr "Error while loading metada"

#: src/backend/controllers/splitter.py:169
#: src/backend/controllers/verifier.py:129
msgid "AT"
msgstr "at"

#: src/backend/controllers/splitter.py:193
msgid "FORM_UNDEFINED"
msgstr "Form undefined"

#: src/backend/controllers/splitter.py:196
msgid "CUSTOMER_UNDEFINED"
msgstr "Customer undefined"

#: src/backend/controllers/splitter.py:256
msgid "BATCH_NOT_FOUND"
msgstr "Batch not found"

#: src/backend/controllers/splitter.py:257
msgid "BATCH_ID_NOT_FOUND"
msgstr "Batch %(id)s not found"

#: src/backend/controllers/splitter.py:266
#: src/backend/controllers/verifier.py:697
msgid "UPDATE_STATUS_ERROR"
msgstr "Error while updating status"

#: src/backend/controllers/splitter.py:301
#: src/backend/controllers/verifier.py:402
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr "Error while removing lock"

#: src/backend/controllers/splitter.py:411
msgid "ADD_DOCUMENT_ERROR"
msgstr "Error while adding document"

#: src/backend/controllers/splitter.py:546
#: src/backend/controllers/splitter.py:815
msgid "EXPORT_PDF_ERROR"
msgstr "Error while exporting PDF"

#: src/backend/controllers/splitter.py:568
#: src/backend/controllers/splitter.py:840
msgid "EXPORT_XML_ERROR"
msgstr "Error while exporting XML"

#: src/backend/controllers/splitter.py:583
msgid "UPDATE_BATCH_ERROR"
msgstr "Error while updating batch"

#: src/backend/controllers/splitter.py:596
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr "Error while updating document"

#: src/backend/controllers/splitter.py:609
#: src/backend/controllers/verifier.py:379
#: src/backend/controllers/verifier.py:385
msgid "UPDATE_DOCUMENT_ERROR"
msgstr "Error while updating document"

#: src/backend/controllers/splitter.py:624
#: src/backend/controllers/splitter.py:645
#: src/backend/controllers/splitter.py:660
#: src/backend/controllers/splitter.py:675
msgid "UPDATE_PAGES_ERROR"
msgstr "Error while updating pages"

#: src/backend/controllers/splitter.py:689
msgid "CMIS_CONNECTION_ERROR"
msgstr "Error while connecting to CMIS"

#: src/backend/controllers/splitter.py:702
msgid "OPENADS_CONNECTION_ERROR"
msgstr "OpenADS connection error"

#: src/backend/controllers/splitter.py:890
msgid "CHECK_FOLDER_ERROR"
msgstr "Check folder error"

#: src/backend/controllers/splitter.py:891
msgid "FOLDER_DOES_NOT_EXIST"
msgstr "Folder does not exist"

#: src/backend/controllers/splitter.py:908
msgid "OPENADS_ADD_DOC_ERROR"
msgstr "OpenADS add document error"

#: src/backend/controllers/splitter.py:1005
#: src/backend/controllers/verifier.py:676 src/backend/models/splitter.py:572
#: src/backend/models/verifier.py:194
msgid "GET_TOTALS_ERROR"
msgstr "Error while retrievings totals"

#: src/backend/controllers/status.py:31
msgid "RETRIEVES_STATUS_ERROR"
msgstr "Error while retrieving status"

#: src/backend/controllers/tasks_watcher.py:34
msgid "CREATE_TASK_ERROR"
msgstr "Error while createing new task"

#: src/backend/controllers/user.py:64
msgid "CREATE_USER_ERROR"
msgstr "Error while creating user"

#: src/backend/controllers/user.py:108 src/backend/controllers/user.py:124
#: src/backend/controllers/user.py:190 src/backend/models/user.py:140
#: src/backend/models/user.py:187
msgid "GET_USER_BY_ID_ERROR"
msgstr "Error while retrieving user"

#: src/backend/controllers/user.py:141
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr "Error while retrieving user"

#: src/backend/controllers/user.py:164
msgid "SEND_EMAIL_FORGOT_PASSWORD_ERROR"
msgstr "Error sending password reset email"

#: src/backend/controllers/user.py:184 src/backend/controllers/user.py:189
msgid "RESET_PASSWORD_ERROR"
msgstr "Erreur while reseting password"

#: src/backend/controllers/user.py:185
msgid "RESET_TOKEN_MISMATCH"
msgstr "Reset token mismatch. Maybe the token is expired"

#: src/backend/controllers/user.py:270
msgid "UPDATE_PROFILE"
msgstr "Update profile"

#: src/backend/controllers/user.py:271
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr "The old password do not match"

#: src/backend/controllers/user.py:277
msgid "UPDATE_USER"
msgstr "Update user"

#: src/backend/controllers/user.py:278
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr "Password do not match"

#: src/backend/controllers/user.py:306 src/backend/controllers/user.py:312
#: src/backend/models/user.py:255 src/backend/models/user.py:321
msgid "UPDATE_USER_ERROR"
msgstr "Error while updating user"

#: src/backend/controllers/user.py:326 src/backend/controllers/user.py:332
msgid "DELETE_USER_ERROR"
msgstr "Error while deleting user"

#: src/backend/controllers/user.py:346 src/backend/controllers/user.py:352
msgid "DISABLE_USER_ERROR"
msgstr "Error while disabling user"

#: src/backend/controllers/user.py:366 src/backend/controllers/user.py:372
msgid "ENABLE_USER_ERROR"
msgstr "Error while enabling user"

#: src/backend/controllers/user.py:389 src/backend/controllers/user.py:395
#: src/backend/models/user.py:277
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr "Error while updating user customers"

#: src/backend/controllers/user.py:410 src/backend/controllers/user.py:417
#: src/backend/models/user.py:299
msgid "UPDATE_FORMS_USER_ERROR"
msgstr "Error while updating user forms"

#: src/backend/controllers/verifier.py:79
msgid "FILE_UPLOADED_WS_WORKFLOW"
msgstr "File uploaded successfully via webservice with workflow"

#: src/backend/controllers/verifier.py:93 src/backend/models/splitter.py:219
#: src/backend/models/verifier.py:40
msgid "GET_DOCUMENT_BY_ID_ERROR"
msgstr "Error while retrieving document"

#: src/backend/controllers/verifier.py:110 src/backend/models/verifier.py:64
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR"
msgstr "Error while retrieving document using token"

#: src/backend/controllers/verifier.py:111
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR_MESSAGE"
msgstr "No document found with this token"

#: src/backend/controllers/verifier.py:224
#: src/backend/controllers/verifier.py:326
msgid "UPDATE_DOCUMENT_POSITIONS_ERROR"
msgstr "Error while updating document positions"

#: src/backend/controllers/verifier.py:247
#: src/backend/controllers/verifier.py:344
msgid "UPDATE_DOCUMENT_PAGES_ERROR"
msgstr "Error while updating document pages"

#: src/backend/controllers/verifier.py:270
#: src/backend/controllers/verifier.py:288
msgid "UPDATE_DOCUMENT_DATA_ERROR"
msgstr "Error while updating document datas"

#: src/backend/controllers/verifier.py:358
#: src/backend/controllers/verifier.py:364
msgid "DELETE_DOCUMENT_ERROR"
msgstr "Error while deleting document"

#: src/backend/controllers/verifier.py:569
#: src/backend/controllers/verifier.py:572
#: src/backend/controllers/verifier.py:589
#: src/backend/controllers/verifier.py:615
#: src/backend/controllers/verifier.py:616
msgid "API_INSEE_ERROR_CONNEXION"
msgstr "Error while connecting to INSEE API"

#: src/backend/controllers/verifier.py:646
msgid "VAT_NOT_VALID"
msgstr "VAT number not valid"

#: src/backend/controllers/verifier.py:653
#: src/backend/controllers/verifier.py:654
msgid "VAT_API_ERROR"
msgstr "API for VAT number unreachable"

#: src/backend/controllers/verifier.py:687
msgid "DOCUMENT_NOT_FOUND"
msgstr "document not found"

#: src/backend/controllers/verifier.py:688
msgid "DOCUMENT_ID_NOT_FOUND"
msgstr "document %(id)s not found"

#: src/backend/controllers/workflow.py:50
#: src/backend/controllers/workflow.py:59
#: src/backend/controllers/workflow.py:66
msgid "WORKFLOW_FOLDER_CREATION_ERROR"
msgstr "Error while creating input folder"

#: src/backend/controllers/workflow.py:51
msgid "FOLDER_NOT_ALLOWED_ERROR"
msgstr "Capture path not allowed"

#: src/backend/controllers/workflow.py:60
#: src/backend/controllers/workflow.py:297
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr "Cannot create folder because of permission issue"

#: src/backend/controllers/workflow.py:67
msgid "CAN_NOT_ACCESS_FOLDER_PERMISSION_ERROR"
msgstr "Cannot create folder because of permission issue"

#: src/backend/controllers/workflow.py:81
msgid "GET_WORKFLOW_BY_ID_ERROR"
msgstr "Error while retrieving workflow"

#: src/backend/controllers/workflow.py:94
msgid "GET_WORKFLOW_BY_WORKFLOW_ID_ERROR"
msgstr "Error while retrieving workflow"

#: src/backend/controllers/workflow.py:118
#: src/backend/controllers/workflow.py:124
msgid "DUPLICATE_WORKFLOW_ERROR"
msgstr "Error duplicating workflow"

#: src/backend/controllers/workflow.py:149
#: src/backend/controllers/workflow.py:161
#: src/backend/controllers/workflow.py:172
#: src/backend/controllers/workflow.py:190
msgid "CREATE_WORKFLOW_ERROR"
msgstr "Error while creating workflow"

#: src/backend/controllers/workflow.py:150
#: src/backend/controllers/workflow.py:200
msgid "NOT_ALLOWED_INPUT_PATH"
msgstr "The input path is not allowed"

#: src/backend/controllers/workflow.py:162
msgid "WORKFLOW_ID_ALREADY_EXISTS"
msgstr "The label short already exists"

#: src/backend/controllers/workflow.py:173
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr "The document capture path is already set in another workflow"

#: src/backend/controllers/workflow.py:199
#: src/backend/controllers/workflow.py:222
#: src/backend/controllers/workflow.py:228
msgid "UPDATE_WORKFLOW_ERROR"
msgstr "Error while trying to update workflow"

#: src/backend/controllers/workflow.py:243
#: src/backend/controllers/workflow.py:249
msgid "DELETE_WORKFLOW_ERROR"
msgstr "Error while deleting workflow"

#: src/backend/controllers/workflow.py:296
#: src/backend/controllers/workflow.py:318
msgid "FS_WATCHER_CREATION_ERROR"
msgstr "Error while creating fs watcher settings"

#: src/backend/controllers/workflow.py:319
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr "Fs watcher config doesnt exists"

#: src/backend/controllers/workflow.py:324
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr "Script sample doesn't exists"

#: src/backend/controllers/workflow.py:330
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr "Script folder doesn't exists"

#: src/backend/models/accounts.py:105
msgid "SUPPLIER_UPDATE_ERROR"
msgstr "Error while updating supplier"

#: src/backend/models/artificial_intelligence.py:80
msgid "IA_MODEL_CREATE_ERROR"
msgstr "Error while creating ai models"

#: src/backend/models/artificial_intelligence.py:101
msgid "IA_MODEL_UPDATE_ERROR"
msgstr "Error while updating ai models"

#: src/backend/models/auth.py:43 src/backend/models/auth.py:101
#: src/backend/models/user.py:43 src/backend/rest/auth.py:70
msgid "BAD_USERNAME"
msgstr "Bad username"

#: src/backend/models/auth.py:45 src/backend/models/user.py:45
msgid "BAD_PASSWORD"
msgstr "Bad password"

#: src/backend/models/auth.py:47
msgid "USER_DELETED"
msgstr "User deleted"

#: src/backend/models/auth.py:49
msgid "USER_DISABLED"
msgstr "User disabled"

#: src/backend/models/auth.py:70 src/backend/models/auth.py:80
#: src/backend/models/roles.py:60
msgid "ROLE_DOESNT_EXISTS"
msgstr "Role doesn't exists"

#: src/backend/models/auth.py:165
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr "Error while updating login method"

#: src/backend/models/auth.py:211
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Error while disabling login method"

#: src/backend/models/auth.py:233
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Error while enabling login method"

#: src/backend/models/custom_fields.py:55
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr "Error while creating custom field"

#: src/backend/models/custom_fields.py:58
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr "Custom field already exist"

#: src/backend/models/custom_fields.py:106
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr "Error while updating custom fields"

#: src/backend/models/custom_fields.py:129
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr "Error while deleting custom field"

#: src/backend/models/doctypes.py:54
msgid "DOCTYPE_ALREADY_EXIST"
msgstr "Doctype already exist"

#: src/backend/models/doctypes.py:100
msgid "UPDATE_DOCTYPE_ERROR"
msgstr "Error while updating doctype"

#: src/backend/models/forms.py:45
msgid "GET_FORMS_ERROR"
msgstr "Error while retrieving forms"

#: src/backend/models/forms.py:89
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr "Error while retrieving form settings"

#: src/backend/models/forms.py:112
msgid "GET_DEFAULT_FORM_ERROR"
msgstr "Error while retrieving default form"

#: src/backend/models/forms.py:136
msgid "UPDATE_FORM_ERROR"
msgstr "Error while updating form"

#: src/backend/models/forms.py:158
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr "Error while updating form fields"

#: src/backend/models/forms.py:215
msgid "ADD_FORM_ERROR"
msgstr "Error while creating form"

#: src/backend/models/forms.py:218
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr "Form label already exist"

#: src/backend/models/mailcollect.py:85
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr "Error while updating MailCollect process"

#: src/backend/models/outputs.py:78
msgid "OUTPUT_DOESNT_EXISTS"
msgstr "Output doesn't exists"

#: src/backend/models/outputs.py:101
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr "Output type doesn't exists"

#: src/backend/models/outputs.py:125
msgid "OUTPUT_UPDATE_ERROR"
msgstr "Error while updating output"

#: src/backend/models/outputs.py:145
msgid "OUTPUT_CREATE_ERROR"
msgstr "Error while creating output"

#: src/backend/models/positions_masks.py:63
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr "Error while retrieving positions mask"

#: src/backend/models/positions_masks.py:87
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr "Error while updating positions mask"

#: src/backend/models/positions_masks.py:109
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr "Error while updating positions mask fields"

#: src/backend/models/positions_masks.py:144
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr "Error while creating positions mask"

#: src/backend/models/positions_masks.py:147
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr "Positions mask label already exists"

#: src/backend/models/privileges.py:38 src/backend/models/privileges.py:59
#: src/backend/models/privileges.py:83
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr "Error while retrieving privileges"

#: src/backend/models/roles.py:126
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr "Error while updating role privileges"

#: src/backend/models/roles.py:148
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr "Error while creating role privileges"

#: src/backend/models/splitter.py:78
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr "Error while getting splitter index"

#: src/backend/models/splitter.py:125
msgid "UPDATE_SETTINGS_ERROR"
msgstr "Error while updating splitter settings"

#: src/backend/models/splitter.py:150
msgid "INSERT_PAGE_ERROR"
msgstr "Error while inserting splitter pages"

#: src/backend/models/splitter.py:244
msgid "GET_DOCUMENTS_ERROR"
msgstr "Error while getting splitter documents"

#: src/backend/models/splitter.py:266 src/backend/models/splitter.py:289
msgid "GET_PAGES_ERROR"
msgstr "Error while getting splitter pages"

#: src/backend/models/splitter.py:311
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr "Error while getting splitter source pages value"

#: src/backend/models/splitter.py:334
msgid "GET_DOCUMENT_ERROR"
msgstr "Error while retrieving document"

#: src/backend/models/splitter.py:356
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr "Error while getting splitter maximum index"

#: src/backend/models/status.py:40
msgid "NO_STATUS"
msgstr "No status"

#: src/backend/models/tasks_watcher.py:89
msgid "UPDATE_TASK_ERROR"
msgstr "Error while updating task"

#: src/backend/models/user.py:47
msgid "USER"
msgstr "User"

#: src/backend/models/user.py:47
msgid "ALREADY_REGISTERED"
msgstr "Already registered"

#: src/backend/models/user.py:163
msgid "GET_USER_BY_MAIL_ERROR"
msgstr "No user found with this email address"

#: src/backend/models/user.py:232
msgid "GET_FORMS_BY_USER_ID_ERROR"
msgstr "Error while retrieving forms by user"

#: src/backend/models/verifier.py:127 src/backend/models/verifier.py:148
msgid "DOCUMENT_UPDATE_ERROR"
msgstr "Error while updating document"

#: src/backend/models/workflow.py:60 src/backend/models/workflow.py:83
msgid "WORKFLOW_DOESNT_EXISTS"
msgstr "Workflow doesn't exists"

#: src/backend/models/workflow.py:105
msgid "WORKFLOW_CREATE_ERROR"
msgstr "Error while creating workflow"

#: src/backend/models/workflow.py:127
msgid "WORKFLOW_UPDATE_ERROR"
msgstr "Error while updating workflow"

#: src/backend/rest/accounts.py:35 src/backend/rest/accounts.py:45
#: src/backend/rest/accounts.py:58 src/backend/rest/accounts.py:69
#: src/backend/rest/accounts.py:82 src/backend/rest/accounts.py:95
#: src/backend/rest/accounts.py:108 src/backend/rest/accounts.py:120
#: src/backend/rest/accounts.py:133 src/backend/rest/accounts.py:153
#: src/backend/rest/accounts.py:164 src/backend/rest/accounts.py:175
#: src/backend/rest/accounts.py:186 src/backend/rest/accounts.py:206
#: src/backend/rest/accounts.py:226 src/backend/rest/accounts.py:238
#: src/backend/rest/accounts.py:248 src/backend/rest/accounts.py:259
#: src/backend/rest/accounts.py:271 src/backend/rest/accounts.py:282
#: src/backend/rest/accounts.py:326
#: src/backend/rest/artificial_intelligence.py:30
#: src/backend/rest/artificial_intelligence.py:40
#: src/backend/rest/artificial_intelligence.py:51
#: src/backend/rest/artificial_intelligence.py:61
#: src/backend/rest/artificial_intelligence.py:71
#: src/backend/rest/artificial_intelligence.py:83
#: src/backend/rest/artificial_intelligence.py:96
#: src/backend/rest/artificial_intelligence.py:108 src/backend/rest/auth.py:91
#: src/backend/rest/auth.py:114 src/backend/rest/auth.py:124
#: src/backend/rest/auth.py:144 src/backend/rest/auth.py:155
#: src/backend/rest/auth.py:178 src/backend/rest/auth.py:189
#: src/backend/rest/config.py:31 src/backend/rest/config.py:41
#: src/backend/rest/config.py:51 src/backend/rest/config.py:61
#: src/backend/rest/config.py:72 src/backend/rest/config.py:82
#: src/backend/rest/config.py:92 src/backend/rest/config.py:109
#: src/backend/rest/config.py:120 src/backend/rest/config.py:132
#: src/backend/rest/config.py:144 src/backend/rest/custom_fields.py:32
#: src/backend/rest/custom_fields.py:46 src/backend/rest/custom_fields.py:57
#: src/backend/rest/custom_fields.py:68 src/backend/rest/custom_fields.py:78
#: src/backend/rest/doctypes.py:31 src/backend/rest/doctypes.py:47
#: src/backend/rest/doctypes.py:58 src/backend/rest/doctypes.py:69
#: src/backend/rest/doctypes.py:80 src/backend/rest/forms.py:32
#: src/backend/rest/forms.py:46 src/backend/rest/forms.py:58
#: src/backend/rest/forms.py:91 src/backend/rest/forms.py:102
#: src/backend/rest/forms.py:114 src/backend/rest/forms.py:125
#: src/backend/rest/history.py:39 src/backend/rest/history.py:49
#: src/backend/rest/history.py:59 src/backend/rest/locale.py:31
#: src/backend/rest/mailcollect.py:29 src/backend/rest/mailcollect.py:45
#: src/backend/rest/mailcollect.py:56 src/backend/rest/mailcollect.py:72
#: src/backend/rest/mailcollect.py:86 src/backend/rest/mailcollect.py:97
#: src/backend/rest/mailcollect.py:108 src/backend/rest/monitoring.py:29
#: src/backend/rest/monitoring.py:39 src/backend/rest/monitoring.py:50
#: src/backend/rest/outputs.py:31 src/backend/rest/outputs.py:44
#: src/backend/rest/outputs.py:63 src/backend/rest/outputs.py:75
#: src/backend/rest/outputs.py:87 src/backend/rest/outputs.py:100
#: src/backend/rest/outputs.py:112 src/backend/rest/outputs.py:124
#: src/backend/rest/positions_masks.py:33
#: src/backend/rest/positions_masks.py:43
#: src/backend/rest/positions_masks.py:54
#: src/backend/rest/positions_masks.py:65
#: src/backend/rest/positions_masks.py:77
#: src/backend/rest/positions_masks.py:89
#: src/backend/rest/positions_masks.py:101
#: src/backend/rest/positions_masks.py:112
#: src/backend/rest/positions_masks.py:123
#: src/backend/rest/positions_masks.py:134
#: src/backend/rest/positions_masks.py:145
#: src/backend/rest/positions_masks.py:157 src/backend/rest/privileges.py:29
#: src/backend/rest/privileges.py:39 src/backend/rest/roles.py:29
#: src/backend/rest/roles.py:39 src/backend/rest/roles.py:49
#: src/backend/rest/roles.py:60 src/backend/rest/roles.py:71
#: src/backend/rest/roles.py:81 src/backend/rest/roles.py:91
#: src/backend/rest/roles.py:101 src/backend/rest/splitter.py:30
#: src/backend/rest/splitter.py:52 src/backend/rest/splitter.py:62
#: src/backend/rest/splitter.py:72 src/backend/rest/splitter.py:83
#: src/backend/rest/splitter.py:98 src/backend/rest/splitter.py:108
#: src/backend/rest/splitter.py:119 src/backend/rest/splitter.py:133
#: src/backend/rest/splitter.py:144 src/backend/rest/splitter.py:155
#: src/backend/rest/splitter.py:166 src/backend/rest/splitter.py:177
#: src/backend/rest/splitter.py:188 src/backend/rest/splitter.py:203
#: src/backend/rest/splitter.py:206 src/backend/rest/splitter.py:224
#: src/backend/rest/splitter.py:236 src/backend/rest/splitter.py:247
#: src/backend/rest/splitter.py:258 src/backend/rest/splitter.py:268
#: src/backend/rest/status.py:31 src/backend/rest/tasks_watcher.py:30
#: src/backend/rest/user.py:29 src/backend/rest/user.py:40
#: src/backend/rest/user.py:65 src/backend/rest/user.py:75
#: src/backend/rest/user.py:107 src/backend/rest/user.py:118
#: src/backend/rest/user.py:128 src/backend/rest/user.py:138
#: src/backend/rest/user.py:155 src/backend/rest/user.py:166
#: src/backend/rest/user.py:176 src/backend/rest/verifier.py:45
#: src/backend/rest/verifier.py:100 src/backend/rest/verifier.py:112
#: src/backend/rest/verifier.py:133 src/backend/rest/verifier.py:146
#: src/backend/rest/verifier.py:158 src/backend/rest/verifier.py:170
#: src/backend/rest/verifier.py:183 src/backend/rest/verifier.py:196
#: src/backend/rest/verifier.py:209 src/backend/rest/verifier.py:222
#: src/backend/rest/verifier.py:234 src/backend/rest/verifier.py:245
#: src/backend/rest/verifier.py:264 src/backend/rest/verifier.py:283
#: src/backend/rest/verifier.py:303 src/backend/rest/verifier.py:315
#: src/backend/rest/verifier.py:327 src/backend/rest/verifier.py:350
#: src/backend/rest/verifier.py:368 src/backend/rest/verifier.py:380
#: src/backend/rest/verifier.py:391 src/backend/rest/verifier.py:404
#: src/backend/rest/verifier.py:417 src/backend/rest/verifier.py:428
#: src/backend/rest/verifier.py:441 src/backend/rest/verifier.py:452
#: src/backend/rest/workflow.py:32 src/backend/rest/workflow.py:45
#: src/backend/rest/workflow.py:58 src/backend/rest/workflow.py:71
#: src/backend/rest/workflow.py:83 src/backend/rest/workflow.py:95
#: src/backend/rest/workflow.py:107 src/backend/rest/workflow.py:119
#: src/backend/rest/workflow.py:132 src/backend/rest/workflow.py:145
msgid "UNAUTHORIZED_ROUTE"
msgstr "You are not authorized to access this route"

#: src/backend/rest/auth.py:45 src/backend/rest/auth.py:74
msgid "PGSQL_ERROR"
msgstr "Error while connecting to database"

#: src/backend/rest/auth.py:160
msgid "REQUEST_MODIFS_ERROR"
msgstr "Error in the database impossible to make the change"

#: src/backend/rest/monitoring.py:55 src/backend/rest/verifier.py:125
msgid "TOKEN_IS_MANDATORY"
msgstr "Valid token is mandatory"

#: src/backend/rest/splitter.py:45 src/backend/rest/verifier.py:93
msgid "UNKNOW_ERROR"
msgstr "Unknow error"

#: src/backend/rest/verifier.py:50
msgid "VERIFIER_UPLOAD_ERROR"
msgstr "Error while uploading file(s)"

#: src/backend/rest/verifier.py:51
msgid "WORKFLOW_ID_IS_MANDATORY"
msgstr "Workflow id is mandatory"

#: src/backend/rest/verifier.py:88
msgid "UNIQUE_URL_TOKEN_GENERATION_ERROR"
msgstr "Error while generating unique url token"

#: src/backend/rest/verifier.py:89
msgid "INTERFACE_IS_NOT_USED_OR_FORM_UNIQUE_URL_NOT_SET"
msgstr ""
"Interface use is not set in workflow or unique url settings is malformed "
"on the form"

