# French translations for Open-Capture
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the project
# FIRST AUTHOR <nathan.cheval@edissyum.com>, 2021.
msgid ""
msgstr ""
"Project-Id-Version:  0.1\n"
"Report-Msgid-Bugs-To: nathan.cheval@edissyum.com\n"
"POT-Creation-Date: 2023-12-14 11:04+0100\n"
"PO-Revision-Date: 2019-09-02 17:48+0200\n"
"Last-Translator: Nathan CHEVAL <nathan.cheval@edissyum.com>\n"
"Language: fr\n"
"Language-Team: fr <nathan.cheval@edissyum.com>\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.14.0\n"

#: custom/edissyum/src/backend/process_queue_splitter.py:212
#: custom/edissyum/src/backend/process_queue_verifier.py:183
#: custom/test/src/backend/process_queue_splitter.py:208
#: custom/test/src/backend/process_queue_verifier.py:184
msgid "FILE_UPLOADED_WORKFLOW"
msgstr "Fichier téléversé avec le workflow"

#: src/backend/functions.py:37 src/backend/functions.py:49
#: src/backend/functions.py:54
msgid "NO_DATA_OR_DATA_MISSING"
msgstr "Les données obligatoires sont manquantes ou incorrectes"

#: src/backend/functions.py:46
msgid "JSON_ERROR"
msgstr "La construction du JSON est incorrect"

#: src/backend/functions.py:49
msgid "IS_NOT"
msgstr "n'est pas de type"

#: src/backend/scripting_functions.py:77
msgid "WORFKLOW_NOT_FOUND"
msgstr "Le workflow n'existe pas"

#: src/backend/splitter_exports.py:95
msgid "OUTPUT_NOT_FOUND"
msgstr "La chaîne sortante n'existe pas"

#: src/backend/models/outputs.py:101 src/backend/splitter_exports.py:123
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr "Le type de chaîne sortante n'existe aps"

#: src/backend/splitter_exports.py:170 src/backend/splitter_exports.py:281
msgid "EXPORT_PDF_ERROR"
msgstr "Erreur lors de l'export PDF"

#: src/backend/splitter_exports.py:247 src/backend/splitter_exports.py:304
msgid "EXPORT_XML_ERROR"
msgstr "Erreur lors de l'export XML"

#: src/backend/splitter_exports.py:324
msgid "CHECK_FOLDER_ERROR"
msgstr "Erreur lors de la vérification du dossier"

#: src/backend/splitter_exports.py:325
msgid "FOLDER_DOES_NOT_EXIST"
msgstr "Dossier inexistant"

#: src/backend/splitter_exports.py:345
msgid "OPENADS_ADD_DOC_ERROR"
msgstr "Erreur lors de l'envoi de document à OpenADS"

#: src/backend/verifier_exports.py:151 src/backend/verifier_exports.py:154
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Le dossier de destination XML n'existe pas"

#: src/backend/verifier_exports.py:353 src/backend/verifier_exports.py:356
#: src/backend/verifier_exports.py:423 src/backend/verifier_exports.py:426
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Le dossier de destination PDF n'existe pas"

#: src/backend/verifier_exports.py:587 src/backend/verifier_exports.py:593
#: src/backend/verifier_exports.py:599
msgid "EXPORT_MEM_ERROR"
msgstr "Erreur lors de l'export vers MEM Courrier"

#: src/backend/verifier_exports.py:594
msgid "PDF_FILE_NOT_FOUND"
msgstr "Le fichier PDF est introuvable"

#: src/backend/verifier_exports.py:605
msgid "MEM_WS_INFO_WRONG"
msgstr "Les informations de connexion à MEM Courrier sont erronées"

#: src/backend/verifier_exports.py:611
msgid "MEM_WS_INFO_EMPTY"
msgstr "Les informations de connexion à MEM Courrier sont vides"

#: src/backend/classes/MEMWebServices.py:40
msgid "HOST_NOT_FOUND"
msgstr "L'URL de l'hôte n'existe pas"

#: src/backend/classes/SMTP.py:223
msgid "RESET_PASSWORD"
msgstr "Réinitialiser le mot de passe"

#: src/backend/classes/SMTP.py:225
msgid "FORGOT_EMAIL_HEADER"
msgstr ""
"Bonjour,<br/><br/>Vous avez demandé à réinitialiser le mot de passe de "
"votre compte Open-Capture.<br/><br/>Pour modifier votre mot de passe, "
"veuillez cliquer sur le lien ci-dessous :<br/><br/>"

#: src/backend/classes/SMTP.py:225
msgid "CLICK_HERE"
msgstr "Cliquez ici"

#: src/backend/classes/SMTP.py:225
msgid "FORGOT_EMAIL_FOOTER"
msgstr ""
"<br/><br/>Si vous n'êtes pas à l'origine de cette demande, merci "
"d'ignorer cet e-mail."

#: src/backend/classes/SMTP.py:242
msgid "SMTP_TEST_SEND"
msgstr "Test d'envoi de mail"

#: src/backend/classes/SMTP.py:243
msgid "SMTP_TEST_SEND_BODY"
msgstr "Ceci est un test d'envoi de mail depuis l'application Open-Capture"

#: src/backend/controllers/accounts.py:71 src/backend/models/accounts.py:61
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du compte tiers"

#: src/backend/controllers/accounts.py:84
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de l'adresse"

#: src/backend/controllers/accounts.py:111
#: src/backend/controllers/accounts.py:239
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr "Erreur lors de la mise à jour des positions du compte tiers"

#: src/backend/controllers/accounts.py:138
#: src/backend/controllers/accounts.py:270
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr "Erreur lors de la mise à jour des pages du compte tiers"

#: src/backend/controllers/accounts.py:196
msgid "SUPPLIER_UPDATED"
msgstr "Mise à jour du compte tiers&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:202
#: src/backend/controllers/accounts.py:208
msgid "UPDATE_SUPPLIER_ERROR"
msgstr "Erreur lors de la mise à jour du tiers"

#: src/backend/controllers/accounts.py:294
#: src/backend/controllers/accounts.py:300
#: src/backend/controllers/accounts.py:325
#: src/backend/controllers/accounts.py:332 src/backend/models/accounts.py:127
msgid "UPDATE_ADDRESS_ERROR"
msgstr "Erreur lors de la mise à jour de l'adresse"

#: src/backend/controllers/accounts.py:356 src/backend/models/accounts.py:147
msgid "CREATE_ADDRESS_ERROR"
msgstr "Erreur lors de la création de l'adresse"

#: src/backend/controllers/accounts.py:401
msgid "SUPPLIER_CREATED"
msgstr "Création du compte tiers&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:409
#: src/backend/controllers/accounts.py:415 src/backend/models/accounts.py:167
msgid "CREATE_SUPPLIER_ERROR"
msgstr "Erreur lors de la création du compte tiers"

#: src/backend/controllers/accounts.py:416
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "Un compte tiers existe déjà avec ce numéro de TVA"

#: src/backend/controllers/accounts.py:453 src/backend/controllers/user.py:248
#: src/backend/controllers/user.py:278 src/backend/models/accounts.py:231
#: src/backend/models/accounts.py:254 src/backend/models/accounts.py:273
#: src/backend/models/user.py:213
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du compte client"

#: src/backend/controllers/accounts.py:497
msgid "CUSTOMER_UPDATED"
msgstr "Mise à jour du compte client&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:502
#: src/backend/controllers/accounts.py:508 src/backend/models/accounts.py:295
msgid "UPDATE_CUSTOMER_ERROR"
msgstr "Erreur lors de la mise à jour du compte client"

#: src/backend/controllers/accounts.py:536
msgid "CUSTOMER_CREATED"
msgstr "Création du compte client&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:544
#: src/backend/controllers/accounts.py:550 src/backend/models/accounts.py:315
msgid "CREATE_CUSTOMER_ERROR"
msgstr "Erreur lors de la création du compte client"

#: src/backend/controllers/accounts.py:551
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "Un compte client existe déjà avec ce numéro de TVA"

#: src/backend/controllers/accounts.py:567
msgid "CUSTOMER_DELETED"
msgstr "Suppression du compte client&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:572
#: src/backend/controllers/accounts.py:578 src/backend/models/accounts.py:337
msgid "DELETE_CUSTOMER_ERROR"
msgstr "Erreur lors de la suppression du compte client"

#: src/backend/controllers/accounts.py:595
msgid "SUPPLIER_DELETED"
msgstr "Suppression du compte tiers&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:600
#: src/backend/controllers/accounts.py:606 src/backend/models/accounts.py:189
msgid "DELETE_SUPPLIER_ERROR"
msgstr "Erreur lors de la suppression du compte tiers"

#: src/backend/controllers/accounts.py:624
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr "Erreur lors du chargement du référentiel tiers"

#: src/backend/controllers/artificial_intelligence.py:74
#: src/backend/controllers/artificial_intelligence.py:372
#: src/backend/controllers/artificial_intelligence.py:398
msgid "GET_IA_MODEL_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du modèle d'apprentissage"

#: src/backend/controllers/artificial_intelligence.py:98
msgid "CREATE_IA_MODEL_ERROR"
msgstr "Erreur lors de la création du modèle d'apprentissage"

#: src/backend/controllers/artificial_intelligence.py:120
msgid "DELETE_AI_MODEL"
msgstr "Suppression du modèle&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:157
msgid "UPDATE_AI_MODEL"
msgstr "Mise à jour du modèle&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:162
msgid "UPDATE_IA_MODEL_ERROR"
msgstr "Erreur lors de la mise à jour du modèle d'apprentissage"

#: src/backend/controllers/artificial_intelligence.py:224
msgid "CREATE_AI_MODEL"
msgstr "Création du modèle&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:373
#: src/backend/controllers/artificial_intelligence.py:399
#: src/backend/models/artificial_intelligence.py:59
msgid "IA_MODEL_DOESNT_EXISTS"
msgstr "Le modèle d'apprentissage n'existe pas"

#: src/backend/controllers/artificial_intelligence.py:435
msgid "RENAME_AI_MODEL_ERROR"
msgstr "Erreur lors de la modification du modèle d'intelligence artificielle"

#: src/backend/controllers/artificial_intelligence.py:436
msgid "FILE_DOESNT_EXISTS"
msgstr "Le fichier de ce modèle n'existe pas"

#: src/backend/controllers/auth.py:68 src/backend/controllers/auth.py:115
#: src/backend/controllers/auth.py:169 src/backend/controllers/auth.py:196
#: src/backend/controllers/auth.py:208 src/backend/controllers/auth.py:334
#: src/backend/controllers/auth.py:394
msgid "SESSION_EXPIRED"
msgstr "Votre session à expirée, veuillez vous reconnecter"

#: src/backend/controllers/auth.py:69 src/backend/controllers/auth.py:335
#: src/backend/controllers/auth.py:395 src/backend/controllers/auth.py:406
#: src/backend/controllers/auth.py:416 src/backend/controllers/auth.py:461
msgid "JWT_ERROR"
msgstr "Erreur lors de l'authentification par token"

#: src/backend/controllers/auth.py:197
msgid "RESET_JWT_ERROR"
msgstr "Erreur lors du décodage du token de réinitialisation"

#: src/backend/controllers/auth.py:209
msgid "UNIQUE_URL_JWT_ERROR"
msgstr "Erreur lors du décodage du token d'URL unique"

#: src/backend/controllers/auth.py:243
msgid "LOGOUT"
msgstr "Déconnexion de l'utilisateur"

#: src/backend/controllers/auth.py:250 src/backend/controllers/auth.py:265
#: src/backend/controllers/auth.py:311 src/backend/controllers/auth.py:367
#: src/backend/controllers/auth.py:492 src/backend/controllers/auth.py:503
#: src/backend/controllers/auth.py:513 src/backend/rest/auth.py:82
msgid "LOGIN_ERROR"
msgstr "Erreur lors de la connexion"

#: src/backend/controllers/auth.py:266
msgid "USER_WEBSERVICE"
msgstr ""
"L'utilisateur n'a pas le droit de se connecter à l'application "
"(utilisateur webservice)"

#: src/backend/controllers/auth.py:306 src/backend/controllers/auth.py:362
msgid "LOGIN"
msgstr "Connexion de l'utilisateur"

#: src/backend/controllers/auth.py:406
msgid "AUTHORIZATION_HEADER_INCORRECT"
msgstr "Le header d'authentification est incorrect ('Bearer' ou 'Basic' attendu)"

#: src/backend/controllers/auth.py:416
msgid "ACCOUNT_ALREADY_LOGGED"
msgstr ""
"Votre compte est déjà connecté sur un autre poste. Une seule connexion "
"est autorisée par utilisateur"

#: src/backend/controllers/auth.py:448
msgid "FIRSTNAME"
msgstr "Prénom"

#: src/backend/controllers/auth.py:463 src/backend/controllers/auth.py:468
msgid "REST_ERROR"
msgstr "Erreur lors de l'authentification avec l'utilisateur webservice"

#: src/backend/controllers/auth.py:464
msgid "USER_DO_NOT_EXISTS"
msgstr "L'utilisateur n'existe pas en base de données"

#: src/backend/controllers/auth.py:468
msgid "PASSWORD_INCORRECT"
msgstr "Le mot de passe est incorrect"

#: src/backend/controllers/auth.py:473
msgid "AUTH_ERROR"
msgstr "Erreur lors de l'authentification"

#: src/backend/controllers/auth.py:473
msgid "VALID_TOKEN_OR_USER_WS_MANDATORY"
msgstr "Un token valide ou un compte de webservice est obligatoire"

#: src/backend/controllers/auth.py:504
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr "Plusieurs méthodes d'authentification sont activées"

#: src/backend/controllers/auth.py:528
msgid "LDAP_ERROR"
msgstr "Erreur LDAP"

#: src/backend/controllers/auth.py:529 src/backend/models/auth.py:140
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr "Aucune configurations LDAP n'est disponible"

#: src/backend/controllers/auth.py:540 src/backend/models/auth.py:165
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr "Erreur lors de la mise à jour de la méthode d'authentification"

#: src/backend/controllers/auth.py:555
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr "Echec lors de l'exécution de la requête"

#: src/backend/controllers/auth.py:567
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr "Erreur lors de la désactivation de cette méthode"

#: src/backend/controllers/auth.py:579
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr "Erreur lors de l'activation de cette méthode"

#: src/backend/controllers/auth.py:609 src/backend/controllers/auth.py:796
#: src/backend/controllers/auth.py:852 src/backend/controllers/auth.py:867
#: src/backend/controllers/auth.py:875 src/backend/controllers/auth.py:881
msgid "LDAP_CONNECTION_ERROR"
msgstr "Impossible de se connecter au serveur LDAP"

#: src/backend/controllers/auth.py:610
msgid "LOGIN_LDAP_ERROR"
msgstr "Information(s) de connexion incorrecte(s)"

#: src/backend/controllers/auth.py:784 src/backend/controllers/auth.py:790
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr "Information(s) de synchronisation incorrecte(s)"

#: src/backend/controllers/auth.py:786 src/backend/controllers/auth.py:792
#: src/backend/controllers/auth.py:798 src/backend/controllers/auth.py:804
#: src/backend/controllers/auth.py:810
msgid "LDAP_SYNCHRO_ERROR"
msgstr "Erreur lors de la synchronisation LDAP"

#: src/backend/controllers/auth.py:802 src/backend/controllers/auth.py:808
#: src/backend/controllers/auth.py:887
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr "Informations non complètes"

#: src/backend/controllers/auth.py:850 src/backend/controllers/auth.py:865
#: src/backend/controllers/auth.py:873
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr "Information(s) incorrecte(s)"

#: src/backend/controllers/auth.py:885
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr "Il manque une ou plusieurs informations pour établir la connexion"

#: src/backend/controllers/config.py:64
msgid "LANGUAGE_CHANGED"
msgstr "Changemement de la langue vers&nbsp;<strong>%(lang)s</strong>"

#: src/backend/controllers/config.py:79
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr "Erreur lors de la récupération de la configuration"

#: src/backend/controllers/config.py:109
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr "Erreur lors de la récupération des configurations"

#: src/backend/controllers/config.py:139
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr "Erreur lors de la récupération des docservers"

#: src/backend/controllers/config.py:177
msgid "RETRIEVE_REGEX_ERRORS"
msgstr "Erreur lors de la récupération des regex"

#: src/backend/controllers/config.py:189 src/backend/controllers/config.py:218
#: src/backend/controllers/config.py:230 src/backend/controllers/config.py:257
#: src/backend/models/config.py:199 src/backend/models/config.py:223
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr "Erreur lors de la mise à jour de la configuration"

#: src/backend/controllers/config.py:190 src/backend/controllers/config.py:231
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr "La valeur d'expiration du token ne peut être inférieure à 0"

#: src/backend/controllers/config.py:213 src/backend/controllers/config.py:252
msgid "UPDATE_CONFIGURATION"
msgstr "Mise à jour de la configuration&nbsp;<strong>%(config)s</strong>"

#: src/backend/controllers/config.py:280
msgid "UPDATE_REGEX"
msgstr "Mise à jour de la regex&nbsp;<strong>%(regex)s</strong>"

#: src/backend/controllers/config.py:285 src/backend/models/config.py:245
msgid "UPDATE_REGEX_ERROR"
msgstr "Erreur lors de la mise à jour des REGEX"

#: src/backend/controllers/config.py:307
msgid "UPDATE_DOCSERVER"
msgstr "Mise à jour de la zone de stockage&nbsp;<strong>%(docserver)s</strong>"

#: src/backend/controllers/config.py:312 src/backend/models/config.py:271
msgid "UPDATE_DOCSERVER_ERROR"
msgstr "Erreur lors de la mise à jour de la docserver"

#: src/backend/controllers/config.py:354 src/backend/controllers/config.py:370
#: src/backend/controllers/config.py:375
msgid "ERROR_UPDATING_IMAGE"
msgstr "Erreur lors de la modification de l'image de connexion"

#: src/backend/controllers/config.py:355 src/backend/controllers/config.py:371
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr "Le dossier d'image du custom n'est pas accessible"

#: src/backend/controllers/config.py:365
msgid "UPDATE_LOGIN_IMAGE"
msgstr "Modification de l'image de login"

#: src/backend/controllers/config.py:376
msgid "CUSTOM_NOT_PRESENT"
msgstr "Aucun custom n'est présent"

#: src/backend/controllers/custom_fields.py:33
#: src/backend/controllers/custom_fields.py:49
#: src/backend/controllers/custom_fields.py:62
msgid "CUSTOM_FIELDS_ERROR"
msgstr "Erreur sur les champs personnalisés"

#: src/backend/controllers/custom_fields.py:75
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr "Erreur lors de la suppression du champ personnalisé"

#: src/backend/controllers/doctypes.py:39
#: src/backend/controllers/doctypes.py:81 src/backend/models/doctypes.py:131
#: src/backend/models/doctypes.py:134
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr "Erreur lors de la modification du type de document par défaut"

#: src/backend/controllers/doctypes.py:45 src/backend/models/doctypes.py:51
msgid "ADD_DOCTYPE_ERROR"
msgstr "Erreur lors de l'ajout d'un type de document"

#: src/backend/controllers/doctypes.py:65
#: src/backend/controllers/doctypes.py:101
#: src/backend/controllers/doctypes.py:114
#: src/backend/controllers/doctypes.py:166
#: src/backend/controllers/doctypes.py:197
#: src/backend/controllers/doctypes.py:236
#: src/backend/controllers/doctypes.py:264
#: src/backend/controllers/doctypes.py:288
#: src/backend/controllers/doctypes.py:317 src/backend/controllers/user.py:556
msgid "DOCTYPE_ERROR"
msgstr "Erreur sur les types de documents"

#: src/backend/controllers/doctypes.py:133
msgid "BUNDLESEPARATOR"
msgstr "SEPARATEUR DE LOT / BUNDLE SEPARATOR"

#: src/backend/controllers/doctypes.py:140
msgid "DOCUMENTSEPARATOR"
msgstr "SEPARATEUR DE DOCUMENT / DOCUMENT SEPARATOR"

#: src/backend/controllers/doctypes.py:159
msgid "DOCTYPESEPARATOR"
msgstr "SEPARATEUR AVEC TYPE DE DOCUMENT / SEPARATOR WITH DOCUMENT TYPE"

#: src/backend/controllers/forms.py:72 src/backend/controllers/forms.py:106
#: src/backend/controllers/forms.py:229
msgid "FORMS_ERROR"
msgstr "Erreur sur les formulaires"

#: src/backend/controllers/forms.py:101
msgid "CREATE_FORM"
msgstr "Création du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:121 src/backend/controllers/forms.py:170
#: src/backend/models/forms.py:66
msgid "GET_FORM_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du formulaire"

#: src/backend/controllers/forms.py:153
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr "Erreur lors de la récupération des champs du formulaire"

#: src/backend/controllers/forms.py:218
msgid "UPDATE_FORM"
msgstr "Mise à jour du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:223 src/backend/controllers/forms.py:381
#: src/backend/controllers/forms.py:387
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du formulaire"

#: src/backend/controllers/forms.py:245
msgid "DELETE_FORM"
msgstr "Suppression du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:250 src/backend/controllers/forms.py:256
msgid "DELETE_FORM_ERROR"
msgstr "Erreur lors de la suppression du formulaire"

#: src/backend/controllers/forms.py:265 src/backend/controllers/outputs.py:66
#: src/backend/controllers/positions_masks.py:167
#: src/backend/controllers/workflow.py:120
msgid "COPY_OF"
msgstr "Copie de"

#: src/backend/controllers/forms.py:286
msgid "DUPLICATE_FORM"
msgstr "Duplication du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:291 src/backend/controllers/forms.py:297
msgid "DUPLICATE_FORM_ERROR"
msgstr "Erreur lors de la duplication du formulaire"

#: src/backend/controllers/forms.py:313
msgid "DISABLE_FORM"
msgstr "Désactivation du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:318 src/backend/controllers/forms.py:324
msgid "DISABLE_FORM_ERROR"
msgstr "Erreur lors de la désactivation du formulaire"

#: src/backend/controllers/forms.py:340
msgid "ENABLE_FORM"
msgstr "Activation du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:345 src/backend/controllers/forms.py:351
msgid "ENABLE_FORM_ERROR"
msgstr "Erreur lors de l'activation du formulaire"

#: src/backend/controllers/forms.py:367
msgid "GET_FORMS_FIELDS_ERROR"
msgstr "Erreur lors de la récupération des champs du formulaire"

#: src/backend/controllers/history.py:31
msgid "ADD_HISTORY_ERROR"
msgstr "Erreur lors de l'ajout dans l'historique"

#: src/backend/controllers/mailcollect.py:38
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr "Erreur lors de la récupération des processus MailCollect"

#: src/backend/controllers/mailcollect.py:53
msgid "UPDATE_MAILCOLLECT_PROCESS"
msgstr "Mise à jour du processus MailCollect&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:61
msgid "UPDATE_PROCESS_ERROR"
msgstr "Erreur lors de la mise à jour du processus MailCollect"

#: src/backend/controllers/mailcollect.py:76
msgid "CREATE_MAILCOLLECT_PROCESS"
msgstr "Création du processus MailCollect&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:82
msgid "CREATE_PROCESS_ERROR"
msgstr "Erreur lors de la création d'un processus MailCollect"

#: src/backend/controllers/mailcollect.py:98
msgid "DELETE_MAILCOLLECT_PROCESS"
msgstr "Suppression du processus MailCollect&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:103
#: src/backend/controllers/mailcollect.py:109
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Erreur lors de la suppression d'un processus MailCollect"

#: src/backend/controllers/mailcollect.py:125
msgid "ENABLE_MAILCOLLECT_PROCESS"
msgstr "Activation du processus MailCollect&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:130
#: src/backend/controllers/mailcollect.py:136
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Erreur lors de l'activation d'un processus MailCollect"

#: src/backend/controllers/mailcollect.py:152
msgid "DISABLE_MAILCOLLECT_PROCESS"
msgstr "Désactivation du processus MailCollect&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:157
#: src/backend/controllers/mailcollect.py:163
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Erreur lors de la désactivation d'un processus MailCollect"

#: src/backend/controllers/mailcollect.py:177
#: src/backend/controllers/mailcollect.py:187
msgid "MAILCOLLECT_ERROR"
msgstr "Erreur MailCollect"

#: src/backend/controllers/outputs.py:75
msgid "DUPLICATE_OUTPUT"
msgstr "Chaîne sortante dupliquée&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:80 src/backend/controllers/outputs.py:86
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr "Erreur lors de la duplication de la chaîne sortante"

#: src/backend/controllers/outputs.py:115
#: src/backend/controllers/outputs.py:144
#: src/backend/controllers/outputs.py:150
msgid "UPDATE_OUTPUT_ERROR"
msgstr "Erreur lors de mise à jour de la chaîne sortante"

#: src/backend/controllers/outputs.py:116
msgid "NOT_ALLOWED_OUTPUT_PATH"
msgstr "Le chemin d'export de la chaîne sortant n'est pas autorisé"

#: src/backend/controllers/outputs.py:139
msgid "UPDATE_OUTPUT"
msgstr "Mise à jour de la chaîne sortante&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:173
msgid "CREATE_OUTPUT"
msgstr "Création de la chaîne sortante&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:181
msgid "CREATE_OUTPUT_ERROR"
msgstr "Erreur lors de la création de la chaîne sortante"

#: src/backend/controllers/outputs.py:194
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de la chaîne sortante"

#: src/backend/controllers/outputs.py:207
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr "Erreur lors de la récupération des types de chaîne sortante"

#: src/backend/controllers/outputs.py:223
msgid "DELETE_OUTPUT"
msgstr "Suppression de la chaîne sortante&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:228
#: src/backend/controllers/outputs.py:234
msgid "DELETE_OUTPUT_ERROR"
msgstr "Erreur lors de la suppression de la chaîne sortante"

#: src/backend/controllers/outputs.py:262
#: src/backend/controllers/outputs.py:271
#: src/backend/controllers/outputs.py:278
msgid "OUTPUT_FOLDER_CREATION_ERROR"
msgstr "Erreur lors de la création du dossier de sortie"

#: src/backend/controllers/outputs.py:263
#: src/backend/controllers/workflow.py:65
msgid "FOLDER_NOT_ALLOWED_ERROR"
msgstr "Le chemin de capture n'est pas autorisé"

#: src/backend/controllers/outputs.py:272
#: src/backend/controllers/workflow.py:74
#: src/backend/controllers/workflow.py:395
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr "Problème de permissions pour créer le dossier"

#: src/backend/controllers/outputs.py:279
#: src/backend/controllers/workflow.py:81
msgid "CAN_NOT_ACCESS_FOLDER_PERMISSION_ERROR"
msgstr "Impossible d'accéder au dossier de travail"

#: src/backend/controllers/positions_masks.py:43
#: src/backend/controllers/positions_masks.py:74
#: src/backend/controllers/positions_masks.py:125
#: src/backend/controllers/positions_masks.py:131
msgid "POSITION_MASKS_ERROR"
msgstr "Erreur sur les masques de positionnement"

#: src/backend/controllers/positions_masks.py:65
msgid "CREATE_POSITIONS_MASK"
msgstr "Création du masque de positionnement&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:89
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du masque de positionnement"

#: src/backend/controllers/positions_masks.py:120
msgid "UPDATE_POSITIONS_MASK"
msgstr "Mise à jour du masque de positionnement&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:147
#: src/backend/controllers/positions_masks.py:232
msgid "DELETE_POSITIONS_MASK"
msgstr "Suppression du masque de positionnement&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:152
#: src/backend/controllers/positions_masks.py:158
msgid "DELETE_POSITION_MASK_ERROR"
msgstr "Erreur lors de la suppression du masque de positionnement"

#: src/backend/controllers/positions_masks.py:183
#: src/backend/controllers/positions_masks.py:189
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la duplication du masque de positionnement"

#: src/backend/controllers/positions_masks.py:205
msgid "DISABLE_POSITIONS_MASK"
msgstr "Désactivation du masque de positionnement&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:210
#: src/backend/controllers/positions_masks.py:216
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr "Erreur lors de désactivation du masque de positionnement"

#: src/backend/controllers/positions_masks.py:237
#: src/backend/controllers/positions_masks.py:243
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr "Erreur lors de l'activation du masque de positionnement"

#: src/backend/controllers/positions_masks.py:266
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Erreur lors de la mise à jour des positions du masque de positionnement"

#: src/backend/controllers/positions_masks.py:289
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Erreur lors de la mise à jour des pages du masque de positionnement"

#: src/backend/controllers/positions_masks.py:307
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr "Erreur lors de la suppression des positions du masque de positionnement"

#: src/backend/controllers/positions_masks.py:325
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr "Erreur lors de la suppression des pages du masque de positionnement"

#: src/backend/controllers/privileges.py:38
#: src/backend/controllers/privileges.py:66
#: src/backend/controllers/privileges.py:94
msgid "GET_PRIVILEGES_ERROR"
msgstr "Erreur lors de la récupération des privilèges"

#: src/backend/controllers/roles.py:39 src/backend/controllers/user.py:122
#: src/backend/controllers/user.py:138 src/backend/controllers/user.py:219
#: src/backend/models/user.py:143 src/backend/models/user.py:190
msgid "GET_USER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de l'utilisateur"

#: src/backend/controllers/roles.py:49 src/backend/controllers/roles.py:169
msgid "GET_ROLE_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du rôle"

#: src/backend/controllers/roles.py:88
msgid "UPDATE_ROLE"
msgstr "Mise à jour du rôle&nbsp;<strong>%(role)s</strong>"

#: src/backend/controllers/roles.py:93 src/backend/controllers/roles.py:99
#: src/backend/controllers/roles.py:150 src/backend/controllers/roles.py:156
#: src/backend/models/roles.py:85
msgid "UPDATE_ROLE_ERROR"
msgstr "Erreur lors de la mise à jour du rôle"

#: src/backend/controllers/roles.py:121
msgid "CREATE_ROLE"
msgstr "Création du rôle&nbsp;<strong>%(role)s</strong>"

#: src/backend/controllers/roles.py:130 src/backend/models/roles.py:105
msgid "CREATE_ROLE_ERROR"
msgstr "Erreur lors de la création du rôle"

#: src/backend/controllers/roles.py:185
msgid "DELETE_ROLE"
msgstr "Suppression du rôle&nbsp;<strong>%(role)s</strong>"

#: src/backend/controllers/roles.py:190 src/backend/controllers/roles.py:196
msgid "DELETE_ROLE_ERROR"
msgstr "Erreur lors de la suppression du rôle"

#: src/backend/controllers/roles.py:210 src/backend/controllers/roles.py:216
msgid "DISABLE_ROLE_ERROR"
msgstr "Erreur lors de la désactivation du rôle"

#: src/backend/controllers/roles.py:230 src/backend/controllers/roles.py:236
msgid "ENABLE_ROLE_ERROR"
msgstr "Erreur lors de l'activation du rôle"

#: src/backend/controllers/smtp.py:47
msgid "SMTP_TEST_SEND_EMAIL_ERROR"
msgstr "Erreur lors de l'envoi du mail de test"

#: src/backend/controllers/smtp.py:53
msgid "SMTP_TEST_CONNECTION_ERROR"
msgstr "Erreur lors de la connexion SMTP"

#: src/backend/controllers/splitter.py:114
msgid "LOAD_METADATA_ERROR"
msgstr "Erreur du chargement des métadonnées"

#: src/backend/controllers/splitter.py:170
#: src/backend/controllers/verifier.py:125
msgid "AT"
msgstr "à"

#: src/backend/controllers/splitter.py:194
msgid "FORM_UNDEFINED"
msgstr "Formulaire non défini"

#: src/backend/controllers/splitter.py:197
msgid "CUSTOMER_UNDEFINED"
msgstr "Compte client non défini"

#: src/backend/controllers/splitter.py:255
#: src/backend/controllers/splitter.py:286
msgid "BATCH_NOT_FOUND"
msgstr "Lot non trouvé"

#: src/backend/controllers/splitter.py:256
#: src/backend/controllers/splitter.py:287
msgid "BATCH_ID_NOT_FOUND"
msgstr "Lot %(id)s non trouvé"

#: src/backend/controllers/splitter.py:270
msgid "DELETE_BATCH_SUCCESS"
msgstr "Suppression du lot n°<strong>%(batch_id)s</strong>"

#: src/backend/controllers/splitter.py:275
#: src/backend/controllers/splitter.py:296
#: src/backend/controllers/verifier.py:784
msgid "UPDATE_STATUS_ERROR"
msgstr "Erreur lors de la mise à jour du statut"

#: src/backend/controllers/splitter.py:331
#: src/backend/controllers/splitter.py:344
#: src/backend/controllers/verifier.py:402
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr "Erreur lors de la suppression du verrou"

#: src/backend/controllers/splitter.py:446
msgid "ADD_DOCUMENT_ERROR"
msgstr "Erreur lors de l'ajout d'un document"

#: src/backend/controllers/splitter.py:472
msgid "UPDATE_BATCH_ERROR"
msgstr "Erreur lors de la mise à jour du lot"

#: src/backend/controllers/splitter.py:486
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr "Erreur lors de la mise à jour du document"

#: src/backend/controllers/splitter.py:499
#: src/backend/controllers/verifier.py:379
#: src/backend/controllers/verifier.py:385
msgid "UPDATE_DOCUMENT_ERROR"
msgstr "Erreur lors de la mise à jour du document"

#: src/backend/controllers/splitter.py:517
#: src/backend/controllers/splitter.py:533
#: src/backend/controllers/splitter.py:548
msgid "UPDATE_PAGES_ERROR"
msgstr "Erreur lors de la modification des pages"

#: src/backend/controllers/splitter.py:562
msgid "CMIS_CONNECTION_ERROR"
msgstr "Erreur lors de la connexion CMIS"

#: src/backend/controllers/splitter.py:575
msgid "OPENADS_CONNECTION_ERROR"
msgstr "Erreur lors de la connexion OpenADS"

#: src/backend/controllers/splitter.py:675
#: src/backend/controllers/verifier.py:763 src/backend/models/splitter.py:595
#: src/backend/models/verifier.py:195
msgid "GET_TOTALS_ERROR"
msgstr "Erreur lors de la récupération des totaux"

#: src/backend/controllers/splitter.py:774
msgid "GET_BATCH_OUTPUTS_ERROR"
msgstr "Erreur lors de la récupération du workflow"

#: src/backend/controllers/status.py:31
msgid "RETRIEVES_STATUS_ERROR"
msgstr "Erreur lors de la récupération des status"

#: src/backend/controllers/user.py:73
msgid "CREATE_USER"
msgstr "Création de l'utilisateur&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:78
msgid "CREATE_USER_ERROR"
msgstr "Erreur lors de la création de l'utilisateur"

#: src/backend/controllers/user.py:155
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr "Erreur lors de la récupération de l'utilisateur"

#: src/backend/controllers/user.py:181
msgid "USER_FORGOT_SUCCESS"
msgstr ""
"Envoi d'email de réinitialisation de mot de passe pour "
"l'utilisateur&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:186
msgid "SEND_EMAIL_FORGOT_PASSWORD_ERROR"
msgstr "Erreur lors de l'envoi de l'email de réinitialisation du mot de passe"

#: src/backend/controllers/user.py:209
msgid "USER_RESET_PASSWORD_SUCCESS"
msgstr ""
"Mot de passe de l'utilisateur&nbsp;<strong>%(user)s</strong> réinitialisé"
" avec succès"

#: src/backend/controllers/user.py:213 src/backend/controllers/user.py:218
msgid "RESET_PASSWORD_ERROR"
msgstr "Erreur lors de la réinitilisation du mot de passe"

#: src/backend/controllers/user.py:214
msgid "RESET_TOKEN_MISMATCH"
msgstr "Le token de réinitialisation est invalide. Il est peut être expiré"

#: src/backend/controllers/user.py:299
msgid "UPDATE_PROFILE"
msgstr "Mise à jour du profile"

#: src/backend/controllers/user.py:300
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr "L'ancien mot de passe ne corresponds pas"

#: src/backend/controllers/user.py:306
msgid "UPDATE_USER"
msgstr "Mise à jour de l'utilisateur"

#: src/backend/controllers/user.py:307
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr "Les mots de passes ne correspondent pas"

#: src/backend/controllers/user.py:337
msgid "USER_UPDATED"
msgstr "Mise à jour du compte utilisateur&nbsp<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:342 src/backend/controllers/user.py:348
#: src/backend/models/user.py:258 src/backend/models/user.py:324
msgid "UPDATE_USER_ERROR"
msgstr "Erreur lors de la mise à jour de l'utilisateur"

#: src/backend/controllers/user.py:364
msgid "DELETE_USER"
msgstr "Suppression de l'utilisateur&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:372 src/backend/controllers/user.py:378
msgid "DELETE_USER_ERROR"
msgstr "Erreur lors de la suppression de l'utilisateur"

#: src/backend/controllers/user.py:394
msgid "DISABLE_USER"
msgstr "Désactivation de l'utilisateur&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:402 src/backend/controllers/user.py:408
msgid "DISABLE_USER_ERROR"
msgstr "Erreur lors de désactiver de l'utilisateur"

#: src/backend/controllers/user.py:424
msgid "ENABLE_USER"
msgstr "Activation de l'utilisateur&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:432 src/backend/controllers/user.py:438
msgid "ENABLE_USER_ERROR"
msgstr "Erreur lors de l'activation de l'utilisateur"

#: src/backend/controllers/user.py:455 src/backend/controllers/user.py:461
#: src/backend/models/user.py:280
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr "Erreur lors de la mise à jour des comptes clients de l'utilisateur"

#: src/backend/controllers/user.py:476 src/backend/controllers/user.py:483
#: src/backend/models/user.py:302
msgid "UPDATE_FORMS_USER_ERROR"
msgstr "Erreur lors de la mise à jour des formulaires de l'utilisateur"

#: src/backend/controllers/user.py:527
msgid "USER_EXPORT_ERROR"
msgstr "Erreur lors de l'export des utilisateurs"

#: src/backend/controllers/user.py:572
msgid "GET_DEFAULT_ROUTE_ERROR"
msgstr "Erreur lors de la récupération de la route par défaut"

#: src/backend/controllers/verifier.py:89 src/backend/models/splitter.py:219
#: src/backend/models/verifier.py:40
msgid "GET_DOCUMENT_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du document"

#: src/backend/controllers/verifier.py:106 src/backend/models/verifier.py:64
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR"
msgstr "Erreur lors de la récupération du document par token"

#: src/backend/controllers/verifier.py:107
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR_MESSAGE"
msgstr "Aucun document trouvé avec ce token"

#: src/backend/controllers/verifier.py:217
#: src/backend/controllers/verifier.py:319
msgid "UPDATE_DOCUMENT_POSITIONS_ERROR"
msgstr "Erreur lors de la mise à jour des positions du document"

#: src/backend/controllers/verifier.py:240
#: src/backend/controllers/verifier.py:337
msgid "UPDATE_DOCUMENT_PAGES_ERROR"
msgstr "Erreur lors de la mise à jour des pages du document"

#: src/backend/controllers/verifier.py:263
#: src/backend/controllers/verifier.py:281
msgid "UPDATE_DOCUMENT_DATA_ERROR"
msgstr "Erreur lors de la mise à jour des données du document"

#: src/backend/controllers/verifier.py:353
msgid "DELETE_DOCUMENT_SUCCESS"
msgstr "Suppression du document n°<strong>%(document_id)s</strong>"

#: src/backend/controllers/verifier.py:358
#: src/backend/controllers/verifier.py:364
msgid "DELETE_DOCUMENT_ERROR"
msgstr "Erreur lors de la suppression du document"

#: src/backend/controllers/verifier.py:493
#: src/backend/controllers/workflow.py:228
#: src/backend/controllers/workflow.py:297
#: src/backend/controllers/workflow.py:486 src/backend/process/main.py:61
msgid "SCRIPT_CONTAINS_NOT_ALLOWED_CODE"
msgstr "Le script contient du code non autorisé :"

#: src/backend/controllers/verifier.py:656
#: src/backend/controllers/verifier.py:659
#: src/backend/controllers/verifier.py:676
#: src/backend/controllers/verifier.py:702
#: src/backend/controllers/verifier.py:703
msgid "API_INSEE_ERROR_CONNEXION"
msgstr "Erreur lors de la connexion à l'api de l'INSEE"

#: src/backend/controllers/verifier.py:733
msgid "VAT_NOT_VALID"
msgstr "Numéro de TVA invalide"

#: src/backend/controllers/verifier.py:740
#: src/backend/controllers/verifier.py:741
msgid "VAT_API_ERROR"
msgstr "Impossible de joindre l'API de vérification du numéro de TVA"

#: src/backend/controllers/verifier.py:774
msgid "DOCUMENT_NOT_FOUND"
msgstr "Document non trouvé"

#: src/backend/controllers/verifier.py:775
msgid "DOCUMENT_ID_NOT_FOUND"
msgstr "Document %(id)s non trouvé"

#: src/backend/controllers/verifier.py:830
msgid "NO_FORM"
msgstr "Pas de formulaire associé"

#: src/backend/controllers/workflow.py:64
#: src/backend/controllers/workflow.py:73
#: src/backend/controllers/workflow.py:80
msgid "WORKFLOW_FOLDER_CREATION_ERROR"
msgstr "Erreur lors de la création du dossier de travail"

#: src/backend/controllers/workflow.py:95
msgid "GET_WORKFLOW_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du workflow"

#: src/backend/controllers/workflow.py:108
msgid "GET_WORKFLOW_BY_WORKFLOW_ID_ERROR"
msgstr "Erreur lors de la récupération du workflow"

#: src/backend/controllers/workflow.py:133
msgid "DUPLICATE_WORKFLOW"
msgstr "Duplication du workflow&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:138
#: src/backend/controllers/workflow.py:144
msgid "DUPLICATE_WORKFLOW_ERROR"
msgstr "Erreur lors de la duplication du workflow"

#: src/backend/controllers/workflow.py:169
#: src/backend/controllers/workflow.py:181
#: src/backend/controllers/workflow.py:192
#: src/backend/controllers/workflow.py:227
#: src/backend/controllers/workflow.py:247
msgid "CREATE_WORKFLOW_ERROR"
msgstr "Erreur lors de la création du workflow"

#: src/backend/controllers/workflow.py:170
#: src/backend/controllers/workflow.py:257
msgid "NOT_ALLOWED_INPUT_PATH"
msgstr "Le chemin de capture de la chaîne entrante n'est pas autorisé"

#: src/backend/controllers/workflow.py:182
msgid "WORKFLOW_ID_ALREADY_EXISTS"
msgstr "Le libellé technique du workflow existe déjà"

#: src/backend/controllers/workflow.py:193
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr "Le chemin de capture est déjà paramétré dans une autre chaîne entrante"

#: src/backend/controllers/workflow.py:239
msgid "CREATE_WORKFLOW"
msgstr "Création du workflow&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:256
#: src/backend/controllers/workflow.py:296
#: src/backend/controllers/workflow.py:313
#: src/backend/controllers/workflow.py:319
msgid "UPDATE_WORKFLOW_ERROR"
msgstr "Erreur lors de la mise à jour du workflow"

#: src/backend/controllers/workflow.py:308
msgid "UPDATE_WORKFLOW"
msgstr "Mise à jour du workflow&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:336
msgid "DELETE_WORKFLOW"
msgstr "Suppression du workflow&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:341
#: src/backend/controllers/workflow.py:347
msgid "DELETE_WORKFLOW_ERROR"
msgstr "Erreur lors de la suppression du workflow"

#: src/backend/controllers/workflow.py:394
#: src/backend/controllers/workflow.py:416
msgid "FS_WATCHER_CREATION_ERROR"
msgstr "Erreur lors de la création des paramètres du fs watcher"

#: src/backend/controllers/workflow.py:417
#: src/backend/controllers/workflow.py:470
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr "La configuration du fs watcher est introuvable"

#: src/backend/controllers/workflow.py:422
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr "Le script d'exemple n'existe pas"

#: src/backend/controllers/workflow.py:428
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr "Le dossier des scripts n'existe pas"

#: src/backend/controllers/workflow.py:469
msgid "FS_WATCHER_DELETION_ERROR"
msgstr "Erreur lors de la suppression de l'entrée du fs watcher"

#: src/backend/controllers/workflow.py:496
msgid "LINE"
msgstr "Ligne"

#: src/backend/controllers/workflow.py:497
msgid "COLUMN"
msgstr "colonne"

#: src/backend/models/accounts.py:105
msgid "SUPPLIER_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour du tiers"

#: src/backend/models/artificial_intelligence.py:80
msgid "IA_MODEL_CREATE_ERROR"
msgstr "Erreur lors de la création du modèle d'apprentissage"

#: src/backend/models/artificial_intelligence.py:101
msgid "IA_MODEL_UPDATE_ERROR"
msgstr "Erreur lors de la modification du modèle d'apprentissage"

#: src/backend/models/auth.py:43 src/backend/models/auth.py:101
#: src/backend/models/user.py:43 src/backend/rest/auth.py:83
msgid "BAD_USERNAME"
msgstr "Mauvais nom de compte"

#: src/backend/models/auth.py:45 src/backend/models/user.py:45
msgid "BAD_PASSWORD"
msgstr "Mauvais mot de passe"

#: src/backend/models/auth.py:47
msgid "USER_DELETED"
msgstr "Utilisateur supprimé"

#: src/backend/models/auth.py:49
msgid "USER_DISABLED"
msgstr "Utilisateur desactivé"

#: src/backend/models/auth.py:70 src/backend/models/auth.py:80
#: src/backend/models/roles.py:61
msgid "ROLE_DOESNT_EXISTS"
msgstr "Le rôle n'existe pas"

#: src/backend/models/auth.py:211
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Erreur lors de la désactivation de cette méthode d'authentification"

#: src/backend/models/auth.py:233
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Erreur lors de l'activation de cette méthode d'authentification"

#: src/backend/models/custom_fields.py:57
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr "Erreur lors de la création du champ custom"

#: src/backend/models/custom_fields.py:60
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr "Le champ custom existe déjà"

#: src/backend/models/custom_fields.py:110
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour du champ custom"

#: src/backend/models/custom_fields.py:133
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr "Erreur lors de la suppression du champ custom"

#: src/backend/models/doctypes.py:54
msgid "DOCTYPE_ALREADY_EXIST"
msgstr "Le type de document existe déjà"

#: src/backend/models/doctypes.py:100
msgid "UPDATE_DOCTYPE_ERROR"
msgstr "Erreur lors de la mise à jour du type de document"

#: src/backend/models/forms.py:45
msgid "GET_FORMS_ERROR"
msgstr "Erreur lors de la récupération des formulaires"

#: src/backend/models/forms.py:89
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr "Erreur lors de la récupération des paramètres du formulaire"

#: src/backend/models/forms.py:112
msgid "GET_DEFAULT_FORM_ERROR"
msgstr "Erreur lors de la récupération du formulaire par défaut"

#: src/backend/models/forms.py:136
msgid "UPDATE_FORM_ERROR"
msgstr "Erreur lors de la mise à jour du formulaire"

#: src/backend/models/forms.py:158
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du formulaire"

#: src/backend/models/forms.py:215
msgid "ADD_FORM_ERROR"
msgstr "Erreur lors de la création du formulaire"

#: src/backend/models/forms.py:218
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr "Le libellé de formulaire existe déjà"

#: src/backend/models/mailcollect.py:86
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour d'un processus MailCollect"

#: src/backend/models/outputs.py:78
msgid "OUTPUT_DOESNT_EXISTS"
msgstr "La chaîne sortante n'existe pas"

#: src/backend/models/outputs.py:125
msgid "OUTPUT_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour de la chaîne sortante"

#: src/backend/models/outputs.py:145
msgid "OUTPUT_CREATE_ERROR"
msgstr "Erreur lors de la création de la chaîne sortante"

#: src/backend/models/positions_masks.py:63
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du masque de positionnement"

#: src/backend/models/positions_masks.py:87
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la mise à jour du masque de positionnement"

#: src/backend/models/positions_masks.py:109
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du masque de positionnement"

#: src/backend/models/positions_masks.py:144
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la création du masque de positionnement"

#: src/backend/models/positions_masks.py:147
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr "Le libellé du masque de positionnement existe déjà"

#: src/backend/models/privileges.py:38 src/backend/models/privileges.py:59
#: src/backend/models/privileges.py:83
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr "Erreur lors de la récupération des privilèges"

#: src/backend/models/roles.py:127
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour des privilèges du rôle"

#: src/backend/models/roles.py:149
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr "Erreur lors de la création des privilèges du rôle"

#: src/backend/models/splitter.py:78
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr "Erreur lors de l'obtention de l'index du Splitter"

#: src/backend/models/splitter.py:125
msgid "UPDATE_SETTINGS_ERROR"
msgstr "Erreur lors de la mise à jour des paramètres du Splitter"

#: src/backend/models/splitter.py:150
msgid "INSERT_PAGE_ERROR"
msgstr "Erreur lors de l'insertion des pages du Splitter"

#: src/backend/models/splitter.py:244
msgid "GET_DOCUMENTS_ERROR"
msgstr "Erreur lors de la récupération des documents du Splitter"

#: src/backend/models/splitter.py:266 src/backend/models/splitter.py:289
msgid "GET_PAGES_ERROR"
msgstr "Erreur lors de l'obtention des pages du Splitter"

#: src/backend/models/splitter.py:311
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr "Erreur lors de l'obtention de la valeur des pages source du Splitter"

#: src/backend/models/splitter.py:334
msgid "GET_DOCUMENT_ERROR"
msgstr "Erreur lors de la récupération du document"

#: src/backend/models/splitter.py:356
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr "Erreur lors de l'obtention de l'index maximum du Splitter"

#: src/backend/models/status.py:40
msgid "NO_STATUS"
msgstr "Aucun status existant"

#: src/backend/models/user.py:47
msgid "USER"
msgstr "L'utilisateur"

#: src/backend/models/user.py:47
msgid "ALREADY_REGISTERED"
msgstr "est déjà enregistré"

#: src/backend/models/user.py:50
msgid "USER_RESTORED"
msgstr "l'utilisateur est restauré"

#: src/backend/models/user.py:166
msgid "GET_USER_BY_MAIL_ERROR"
msgstr "Aucun utilisateur asssocié à cette addresse email"

#: src/backend/models/user.py:235
msgid "GET_FORMS_BY_USER_ID_ERROR"
msgstr "Erreur lors de la récupération des formulaires de l'utilisateur"

#: src/backend/models/verifier.py:128 src/backend/models/verifier.py:149
msgid "DOCUMENT_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour du document"

#: src/backend/models/workflow.py:60 src/backend/models/workflow.py:83
msgid "WORKFLOW_DOESNT_EXISTS"
msgstr "Le workflow n'existe pas"

#: src/backend/models/workflow.py:105
msgid "WORKFLOW_CREATE_ERROR"
msgstr "Erreur lors de la création du modèle workflow"

#: src/backend/models/workflow.py:127
msgid "WORKFLOW_UPDATE_ERROR"
msgstr "Erreur lors de la modification du workflow"

#: src/backend/rest/accounts.py:35 src/backend/rest/accounts.py:56
#: src/backend/rest/accounts.py:69 src/backend/rest/accounts.py:81
#: src/backend/rest/accounts.py:118 src/backend/rest/accounts.py:140
#: src/backend/rest/accounts.py:162 src/backend/rest/accounts.py:188
#: src/backend/rest/accounts.py:215 src/backend/rest/accounts.py:249
#: src/backend/rest/accounts.py:283 src/backend/rest/accounts.py:294
#: src/backend/rest/accounts.py:305 src/backend/rest/accounts.py:334
#: src/backend/rest/accounts.py:363 src/backend/rest/accounts.py:375
#: src/backend/rest/accounts.py:397 src/backend/rest/accounts.py:408
#: src/backend/rest/accounts.py:434 src/backend/rest/accounts.py:459
#: src/backend/rest/accounts.py:503
#: src/backend/rest/artificial_intelligence.py:30
#: src/backend/rest/artificial_intelligence.py:40
#: src/backend/rest/artificial_intelligence.py:51
#: src/backend/rest/artificial_intelligence.py:62
#: src/backend/rest/artificial_intelligence.py:74
#: src/backend/rest/artificial_intelligence.py:92
#: src/backend/rest/artificial_intelligence.py:107
#: src/backend/rest/artificial_intelligence.py:119 src/backend/rest/auth.py:113
#: src/backend/rest/auth.py:163 src/backend/rest/auth.py:173
#: src/backend/rest/auth.py:199 src/backend/rest/auth.py:232
#: src/backend/rest/auth.py:271 src/backend/rest/auth.py:290
#: src/backend/rest/config.py:30 src/backend/rest/config.py:40
#: src/backend/rest/config.py:61 src/backend/rest/config.py:71
#: src/backend/rest/config.py:82 src/backend/rest/config.py:103
#: src/backend/rest/config.py:124 src/backend/rest/config.py:152
#: src/backend/rest/config.py:171 src/backend/rest/config.py:194
#: src/backend/rest/config.py:217 src/backend/rest/custom_fields.py:32
#: src/backend/rest/custom_fields.py:46 src/backend/rest/custom_fields.py:57
#: src/backend/rest/custom_fields.py:68 src/backend/rest/custom_fields.py:78
#: src/backend/rest/doctypes.py:31 src/backend/rest/doctypes.py:47
#: src/backend/rest/doctypes.py:58 src/backend/rest/doctypes.py:69
#: src/backend/rest/doctypes.py:80 src/backend/rest/doctypes.py:90
#: src/backend/rest/doctypes.py:101 src/backend/rest/doctypes.py:116
#: src/backend/rest/forms.py:34 src/backend/rest/forms.py:62
#: src/backend/rest/forms.py:74 src/backend/rest/forms.py:120
#: src/backend/rest/forms.py:143 src/backend/rest/forms.py:164
#: src/backend/rest/forms.py:184 src/backend/rest/forms.py:210
#: src/backend/rest/forms.py:221 src/backend/rest/forms.py:232
#: src/backend/rest/forms.py:243 src/backend/rest/forms.py:255
#: src/backend/rest/history.py:54 src/backend/rest/history.py:79
#: src/backend/rest/history.py:99 src/backend/rest/locale.py:31
#: src/backend/rest/mailcollect.py:30 src/backend/rest/mailcollect.py:40
#: src/backend/rest/mailcollect.py:64 src/backend/rest/mailcollect.py:99
#: src/backend/rest/mailcollect.py:133 src/backend/rest/mailcollect.py:144
#: src/backend/rest/mailcollect.py:155 src/backend/rest/monitoring.py:30
#: src/backend/rest/monitoring.py:40 src/backend/rest/monitoring.py:50
#: src/backend/rest/monitoring.py:61 src/backend/rest/outputs.py:32
#: src/backend/rest/outputs.py:55 src/backend/rest/outputs.py:74
#: src/backend/rest/outputs.py:86 src/backend/rest/outputs.py:98
#: src/backend/rest/outputs.py:124 src/backend/rest/outputs.py:136
#: src/backend/rest/outputs.py:161 src/backend/rest/outputs.py:172
#: src/backend/rest/positions_masks.py:33
#: src/backend/rest/positions_masks.py:53
#: src/backend/rest/positions_masks.py:74
#: src/backend/rest/positions_masks.py:85
#: src/backend/rest/positions_masks.py:109
#: src/backend/rest/positions_masks.py:120
#: src/backend/rest/positions_masks.py:131
#: src/backend/rest/positions_masks.py:142
#: src/backend/rest/positions_masks.py:153
#: src/backend/rest/positions_masks.py:164
#: src/backend/rest/positions_masks.py:175
#: src/backend/rest/positions_masks.py:186 src/backend/rest/privileges.py:29
#: src/backend/rest/privileges.py:39 src/backend/rest/roles.py:55
#: src/backend/rest/roles.py:65 src/backend/rest/roles.py:87
#: src/backend/rest/roles.py:106 src/backend/rest/roles.py:116
#: src/backend/rest/roles.py:126 src/backend/rest/roles.py:136
#: src/backend/rest/splitter.py:31 src/backend/rest/splitter.py:53
#: src/backend/rest/splitter.py:63 src/backend/rest/splitter.py:73
#: src/backend/rest/splitter.py:84 src/backend/rest/splitter.py:105
#: src/backend/rest/splitter.py:116 src/backend/rest/splitter.py:126
#: src/backend/rest/splitter.py:137 src/backend/rest/splitter.py:151
#: src/backend/rest/splitter.py:162 src/backend/rest/splitter.py:173
#: src/backend/rest/splitter.py:184 src/backend/rest/splitter.py:195
#: src/backend/rest/splitter.py:214 src/backend/rest/splitter.py:225
#: src/backend/rest/splitter.py:240 src/backend/rest/splitter.py:243
#: src/backend/rest/splitter.py:261 src/backend/rest/splitter.py:273
#: src/backend/rest/splitter.py:284 src/backend/rest/splitter.py:295
#: src/backend/rest/splitter.py:305 src/backend/rest/splitter.py:316
#: src/backend/rest/status.py:32 src/backend/rest/user.py:31
#: src/backend/rest/user.py:59 src/backend/rest/user.py:96
#: src/backend/rest/user.py:118 src/backend/rest/user.py:179
#: src/backend/rest/user.py:206 src/backend/rest/user.py:216
#: src/backend/rest/user.py:226 src/backend/rest/user.py:243
#: src/backend/rest/user.py:263 src/backend/rest/user.py:273
#: src/backend/rest/user.py:293 src/backend/rest/user.py:308
#: src/backend/rest/verifier.py:70 src/backend/rest/verifier.py:130
#: src/backend/rest/verifier.py:158 src/backend/rest/verifier.py:186
#: src/backend/rest/verifier.py:198 src/backend/rest/verifier.py:209
#: src/backend/rest/verifier.py:221 src/backend/rest/verifier.py:233
#: src/backend/rest/verifier.py:258 src/backend/rest/verifier.py:283
#: src/backend/rest/verifier.py:308 src/backend/rest/verifier.py:333
#: src/backend/rest/verifier.py:355 src/backend/rest/verifier.py:366
#: src/backend/rest/verifier.py:394 src/backend/rest/verifier.py:422
#: src/backend/rest/verifier.py:451 src/backend/rest/verifier.py:462
#: src/backend/rest/verifier.py:474 src/backend/rest/verifier.py:507
#: src/backend/rest/verifier.py:543 src/backend/rest/verifier.py:564
#: src/backend/rest/verifier.py:575 src/backend/rest/verifier.py:597
#: src/backend/rest/verifier.py:619 src/backend/rest/verifier.py:639
#: src/backend/rest/verifier.py:652 src/backend/rest/verifier.py:663
#: src/backend/rest/verifier.py:684 src/backend/rest/workflow.py:32
#: src/backend/rest/workflow.py:54 src/backend/rest/workflow.py:84
#: src/backend/rest/workflow.py:109 src/backend/rest/workflow.py:121
#: src/backend/rest/workflow.py:133 src/backend/rest/workflow.py:145
#: src/backend/rest/workflow.py:157 src/backend/rest/workflow.py:185
#: src/backend/rest/workflow.py:209 src/backend/rest/workflow.py:220
msgid "UNAUTHORIZED_ROUTE"
msgstr "Vous n'êtes pas autorisé à accéder à cette route"

#: src/backend/rest/accounts.py:44 src/backend/rest/accounts.py:104
#: src/backend/rest/accounts.py:126 src/backend/rest/accounts.py:148
#: src/backend/rest/accounts.py:175 src/backend/rest/accounts.py:201
#: src/backend/rest/accounts.py:227 src/backend/rest/accounts.py:271
#: src/backend/rest/accounts.py:315 src/backend/rest/accounts.py:344
#: src/backend/rest/accounts.py:385 src/backend/rest/accounts.py:422
#: src/backend/rest/accounts.py:447 src/backend/rest/auth.py:38
#: src/backend/rest/auth.py:100 src/backend/rest/auth.py:122
#: src/backend/rest/auth.py:142 src/backend/rest/auth.py:187
#: src/backend/rest/auth.py:220 src/backend/rest/auth.py:253
#: src/backend/rest/auth.py:278 src/backend/rest/auth.py:297
#: src/backend/rest/config.py:49 src/backend/rest/config.py:91
#: src/backend/rest/config.py:112 src/backend/rest/config.py:134
#: src/backend/rest/config.py:159 src/backend/rest/config.py:182
#: src/backend/rest/config.py:205 src/backend/rest/config.py:228
#: src/backend/rest/forms.py:46 src/backend/rest/forms.py:86
#: src/backend/rest/forms.py:131 src/backend/rest/forms.py:152
#: src/backend/rest/forms.py:172 src/backend/rest/forms.py:197
#: src/backend/rest/forms.py:268 src/backend/rest/history.py:40
#: src/backend/rest/history.py:67 src/backend/rest/history.py:87
#: src/backend/rest/mailcollect.py:52 src/backend/rest/mailcollect.py:87
#: src/backend/rest/mailcollect.py:121 src/backend/rest/mem.py:37
#: src/backend/rest/mem.py:56 src/backend/rest/mem.py:75
#: src/backend/rest/mem.py:94 src/backend/rest/mem.py:113
#: src/backend/rest/mem.py:132 src/backend/rest/mem.py:151
#: src/backend/rest/mem.py:170 src/backend/rest/mem.py:189
#: src/backend/rest/mem.py:214 src/backend/rest/monitoring.py:70
#: src/backend/rest/outputs.py:40 src/backend/rest/outputs.py:111
#: src/backend/rest/outputs.py:148 src/backend/rest/outputs.py:180
#: src/backend/rest/positions_masks.py:41
#: src/backend/rest/positions_masks.py:62
#: src/backend/rest/positions_masks.py:97 src/backend/rest/roles.py:37
#: src/backend/rest/roles.py:75 src/backend/rest/roles.py:94
#: src/backend/rest/roles.py:145 src/backend/rest/smtp.py:39
#: src/backend/rest/splitter.py:93 src/backend/rest/user.py:47
#: src/backend/rest/user.py:69 src/backend/rest/user.py:106
#: src/backend/rest/user.py:133 src/backend/rest/user.py:150
#: src/backend/rest/user.py:166 src/backend/rest/user.py:194
#: src/backend/rest/user.py:251 src/backend/rest/user.py:281
#: src/backend/rest/user.py:318 src/backend/rest/verifier.py:83
#: src/backend/rest/verifier.py:145 src/backend/rest/verifier.py:173
#: src/backend/rest/verifier.py:245 src/backend/rest/verifier.py:270
#: src/backend/rest/verifier.py:295 src/backend/rest/verifier.py:320
#: src/backend/rest/verifier.py:343 src/backend/rest/verifier.py:376
#: src/backend/rest/verifier.py:404 src/backend/rest/verifier.py:432
#: src/backend/rest/verifier.py:486 src/backend/rest/verifier.py:518
#: src/backend/rest/verifier.py:551 src/backend/rest/verifier.py:584
#: src/backend/rest/verifier.py:606 src/backend/rest/verifier.py:627
#: src/backend/rest/verifier.py:672 src/backend/rest/workflow.py:41
#: src/backend/rest/workflow.py:69 src/backend/rest/workflow.py:92
#: src/backend/rest/workflow.py:172 src/backend/rest/workflow.py:197
#: src/backend/rest/workflow.py:227
msgid "BAD_REQUEST"
msgstr "Erreur de requête"

#: src/backend/rest/auth.py:58 src/backend/rest/auth.py:87
msgid "PGSQL_ERROR"
msgstr "Erreur lors de la connexion à la base de donnée"

#: src/backend/rest/splitter.py:46 src/backend/rest/verifier.py:123
msgid "UNKNOW_ERROR"
msgstr "Erreur inconnue"

#: src/backend/rest/verifier.py:49 src/backend/rest/verifier.py:59
msgid "UPLOAD_ERRROR"
msgstr "Erreur lors de l'upload de(s) fichier(s)"

#: src/backend/rest/verifier.py:50
msgid "FILE_EXTENSION_NOT_ALLOWED"
msgstr "L'extension du fichier n'est pas autorisée"

#: src/backend/rest/verifier.py:60
msgid "FILE_MIME_NOT_ALLOWED"
msgstr "Le type MIME du fichier n'est pas autorisé"

#: src/backend/rest/verifier.py:118
msgid "UNIQUE_URL_TOKEN_GENERATION_ERROR"
msgstr "Erreur lors de la génération du token de l'URL unique"

#: src/backend/rest/verifier.py:119
msgid "INTERFACE_IS_NOT_USED_OR_FORM_UNIQUE_URL_NOT_SET"
msgstr ""
"L'utilisation de l'interface est désactivée dans le workflow ou l'URL "
"unique n'est pas configurée correctement"
