# Translations template for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-12-12 11:48+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.11.0\n"

#: launch_worker.py:47 launch_worker_splitter.py:49
msgid "FILE_UPLOADED"
msgstr ""

#: src/backend/verifier_exports.py:85 src/backend/verifier_exports.py:88
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/verifier_exports.py:171 src/backend/verifier_exports.py:174
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/splitter.py:328
#: src/backend/controllers/splitter.py:334 src/backend/verifier_exports.py:326
#: src/backend/verifier_exports.py:332 src/backend/verifier_exports.py:338
msgid "EXPORT_MAARCH_ERROR"
msgstr ""

#: src/backend/verifier_exports.py:333
msgid "PDF_FILE_NOT_FOUND"
msgstr ""

#: src/backend/verifier_exports.py:344
msgid "MAARCH_WS_INFO_WRONG"
msgstr ""

#: src/backend/controllers/splitter.py:340 src/backend/verifier_exports.py:350
msgid "MAARCH_WS_INFO_EMPTY"
msgstr ""

#: src/backend/classes/MaarchWebServices.py:38
msgid "HOST_NOT_FOUND"
msgstr ""

#: src/backend/controllers/accounts.py:45 src/backend/models/accounts.py:55
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:58 src/backend/models/accounts.py:75
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:79
#: src/backend/controllers/accounts.py:158
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:100
#: src/backend/controllers/accounts.py:189
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:121
#: src/backend/controllers/accounts.py:127
msgid "UPDATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:213
#: src/backend/controllers/accounts.py:219
#: src/backend/controllers/accounts.py:243
#: src/backend/controllers/accounts.py:249 src/backend/models/accounts.py:115
msgid "UPDATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:273 src/backend/models/accounts.py:132
msgid "CREATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:310
#: src/backend/controllers/accounts.py:316 src/backend/models/accounts.py:149
msgid "CREATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:317
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:337 src/backend/controllers/user.py:146
#: src/backend/models/accounts.py:204 src/backend/models/accounts.py:224
#: src/backend/models/accounts.py:240 src/backend/models/user.py:163
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:377
#: src/backend/controllers/accounts.py:383 src/backend/models/accounts.py:259
msgid "UPDATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:411
#: src/backend/controllers/accounts.py:417 src/backend/models/accounts.py:276
msgid "CREATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:418
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:432
#: src/backend/controllers/accounts.py:438 src/backend/models/accounts.py:295
msgid "DELETE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:453
#: src/backend/controllers/accounts.py:459 src/backend/models/accounts.py:168
msgid "DELETE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:481
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:63
#: src/backend/controllers/artificial_intelligence.py:365
msgid "GET_IA_MODEL_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:85
msgid "CREATE_IA_MODEL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:96
msgid "UPDATE_IA_MODEL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:363
#: src/backend/models/artificial_intelligence.py:52
msgid "IA_MODEL_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/auth.py:84 src/backend/controllers/auth.py:131
#: src/backend/controllers/auth.py:173 src/backend/controllers/auth.py:220
#: src/backend/controllers/auth.py:231 src/backend/controllers/auth.py:241
#: src/backend/controllers/auth.py:268 src/backend/rest/auth.py:69
msgid "LOGIN_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:149 src/backend/controllers/auth.py:188
#: src/backend/controllers/auth.py:196 src/backend/controllers/auth.py:199
#: src/backend/controllers/auth.py:201
msgid "JWT_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:196
msgid "ACCOUNT_ALREADY_LOGGED"
msgstr ""

#: src/backend/controllers/auth.py:232
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr ""

#: src/backend/controllers/auth.py:256
msgid "LDAP_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:257 src/backend/models/auth.py:132
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr ""

#: src/backend/controllers/auth.py:283
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:295
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:307
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:331 src/backend/models/auth.py:319
#: src/backend/models/auth.py:334 src/backend/models/auth.py:342
#: src/backend/models/auth.py:348 src/backend/models/auth.py:549
msgid "LDAP_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:332
msgid "LOGIN_LDAP_ERROR"
msgstr ""

#: src/backend/controllers/config.py:62
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:78
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:94
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:110
msgid "RETRIEVE_REGEX_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:122 src/backend/controllers/config.py:142
#: src/backend/models/config.py:157
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr ""

#: src/backend/controllers/config.py:123
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr ""

#: src/backend/controllers/config.py:163 src/backend/models/config.py:176
msgid "UPDATE_REGEX_ERROR"
msgstr ""

#: src/backend/controllers/config.py:183 src/backend/models/config.py:199
msgid "UPDATE_DOCSERVER_ERROR"
msgstr ""

#: src/backend/controllers/config.py:224 src/backend/controllers/config.py:234
#: src/backend/controllers/config.py:239
msgid "ERROR_UPDATING_IMAGE"
msgstr ""

#: src/backend/controllers/config.py:225 src/backend/controllers/config.py:235
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr ""

#: src/backend/controllers/config.py:240
msgid "CUSTOM_NOT_PRESENT"
msgstr ""

#: src/backend/controllers/custom_fields.py:33
#: src/backend/controllers/custom_fields.py:49
#: src/backend/controllers/custom_fields.py:62
msgid "CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/custom_fields.py:75
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:35
#: src/backend/controllers/doctypes.py:77 src/backend/models/doctypes.py:119
#: src/backend/models/doctypes.py:122
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:41 src/backend/models/doctypes.py:48
msgid "ADD_DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:61
#: src/backend/controllers/doctypes.py:97
#: src/backend/controllers/doctypes.py:110
#: src/backend/controllers/doctypes.py:142
#: src/backend/controllers/doctypes.py:171
msgid "DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:130
msgid "DOCTYPESEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:133
msgid "DOCUMENTSEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:136
msgid "BUNDLESEPARATOR"
msgstr ""

#: src/backend/controllers/forms.py:41 src/backend/controllers/forms.py:51
#: src/backend/controllers/forms.py:77 src/backend/controllers/forms.py:185
msgid "FORMS_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:92 src/backend/controllers/forms.py:141
#: src/backend/models/forms.py:57
msgid "GET_FORM_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:124
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:179 src/backend/controllers/forms.py:307
#: src/backend/controllers/forms.py:313
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:199 src/backend/controllers/forms.py:205
msgid "DELETE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:214 src/backend/controllers/inputs.py:66
#: src/backend/controllers/outputs.py:54
#: src/backend/controllers/positions_masks.py:159
msgid "COPY_OF"
msgstr ""

#: src/backend/controllers/forms.py:231 src/backend/controllers/forms.py:237
msgid "DUPLICATE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:251 src/backend/controllers/forms.py:257
msgid "DISABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:271 src/backend/controllers/forms.py:277
msgid "ENABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:293
msgid "GET_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/history.py:28
msgid "ADD_HISTORY_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:48 src/backend/controllers/inputs.py:54
msgid "UPDATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:79 src/backend/controllers/inputs.py:85
msgid "DUPLICATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:110 src/backend/controllers/inputs.py:121
#: src/backend/controllers/inputs.py:134
msgid "CREATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:111
msgid "INPUT_ID_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:122
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:147
msgid "GET_INPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:168 src/backend/controllers/inputs.py:174
msgid "DELETE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:210
msgid "FS_WATCHER_DELETION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:211 src/backend/controllers/inputs.py:278
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr ""

#: src/backend/controllers/inputs.py:257 src/backend/controllers/inputs.py:277
msgid "FS_WATCHER_CREATION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:258
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:283
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:289
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/mailcollect.py:36
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:52
msgid "UPDATE_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:68
msgid "CREATE_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:82
#: src/backend/controllers/mailcollect.py:88
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:102
#: src/backend/controllers/mailcollect.py:108
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:122
#: src/backend/controllers/mailcollect.py:128
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:142
#: src/backend/controllers/mailcollect.py:152
msgid "MAILCOLLECT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:61 src/backend/controllers/outputs.py:67
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:92 src/backend/controllers/outputs.py:98
msgid "UPDATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:122
msgid "CREATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:135
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:148
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:162
#: src/backend/controllers/outputs.py:168
msgid "DELETE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:42
#: src/backend/controllers/positions_masks.py:62
#: src/backend/controllers/positions_masks.py:117
#: src/backend/controllers/positions_masks.py:123
msgid "POSITION_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:77
#: src/backend/controllers/positions_masks.py:94
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:141
#: src/backend/controllers/positions_masks.py:147
msgid "DELETE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:175
#: src/backend/controllers/positions_masks.py:181
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:199
#: src/backend/controllers/positions_masks.py:205
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:223
#: src/backend/controllers/positions_masks.py:229
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:255
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:281
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:302
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:323
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/privileges.py:37
#: src/backend/controllers/privileges.py:65
msgid "GET_PRIVILEGES_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:47 src/backend/controllers/roles.py:53
#: src/backend/controllers/roles.py:95 src/backend/controllers/roles.py:101
#: src/backend/models/roles.py:75
msgid "UPDATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:75 src/backend/models/roles.py:92
msgid "CREATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:114
msgid "GET_ROLE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:128 src/backend/controllers/roles.py:134
msgid "DELETE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:148 src/backend/controllers/roles.py:154
msgid "DISABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:168 src/backend/controllers/roles.py:174
msgid "ENABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:84
msgid "LOAD_METADATA_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:116
#: src/backend/controllers/verifier.py:75
msgid "AT"
msgstr ""

#: src/backend/controllers/splitter.py:138
msgid "FORM_UNDEFINED"
msgstr ""

#: src/backend/controllers/splitter.py:277
msgid "ADD_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:396
#: src/backend/controllers/splitter.py:655
msgid "EXPORT_PDF_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:418
#: src/backend/controllers/splitter.py:679
msgid "EXPORT_XML_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:434
msgid "UPDATE_BATCH_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:447
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:460
msgid "UPDATE_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:475
#: src/backend/controllers/splitter.py:496
#: src/backend/controllers/splitter.py:511
#: src/backend/controllers/splitter.py:526
msgid "UPDATE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:540
msgid "CMIS_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:553
msgid "OPENADS_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:728
msgid "CHECK_FOLDER_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:747
msgid "OPENADS_ADD_DOC_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:815
#: src/backend/controllers/verifier.py:559 src/backend/models/splitter.py:460
#: src/backend/models/verifier.py:153
msgid "GET_TOTALS_ERROR"
msgstr ""

#: src/backend/controllers/status.py:31
msgid "RETRIEVES_STATUS_ERROR"
msgstr ""

#: src/backend/controllers/tasks_watcher.py:34
msgid "CREATE_TASK_ERROR"
msgstr ""

#: src/backend/controllers/user.py:61
msgid "CREATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:99 src/backend/models/user.py:122
#: src/backend/models/user.py:143
msgid "GET_USER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/user.py:116
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr ""

#: src/backend/controllers/user.py:162
msgid "UPDATE_PROFILE"
msgstr ""

#: src/backend/controllers/user.py:163
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:168
msgid "UPDATE_USER"
msgstr ""

#: src/backend/controllers/user.py:169
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:196 src/backend/controllers/user.py:202
#: src/backend/models/user.py:183
msgid "UPDATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:216 src/backend/controllers/user.py:222
msgid "DELETE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:236 src/backend/controllers/user.py:242
msgid "DISABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:256 src/backend/controllers/user.py:262
msgid "ENABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:279 src/backend/controllers/user.py:285
#: src/backend/models/user.py:202
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:56 src/backend/models/verifier.py:37
msgid "GET_INVOICE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:167
#: src/backend/controllers/verifier.py:269
msgid "UPDATE_INVOICE_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:190
#: src/backend/controllers/verifier.py:287
msgid "UPDATE_INVOICE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:213
#: src/backend/controllers/verifier.py:231
msgid "UPDATE_INVOICE_DATA_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:301
#: src/backend/controllers/verifier.py:307
msgid "DELETE_INVOICE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:322
#: src/backend/controllers/verifier.py:328
msgid "UPDATE_INVOICE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:345
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:467
#: src/backend/controllers/verifier.py:470
#: src/backend/controllers/verifier.py:487
#: src/backend/controllers/verifier.py:506
#: src/backend/controllers/verifier.py:507
msgid "API_INSEE_ERROR_CONNEXION"
msgstr ""

#: src/backend/controllers/verifier.py:531
msgid "VAT_NOT_VALID"
msgstr ""

#: src/backend/controllers/verifier.py:536
#: src/backend/controllers/verifier.py:537
msgid "VAT_API_ERROR"
msgstr ""

#: src/backend/models/accounts.py:96
msgid "SUPPLIER_UPDATE_ERROR"
msgstr ""

#: src/backend/models/artificial_intelligence.py:70
msgid "IA_MODEL_CREATE_ERROR"
msgstr ""

#: src/backend/models/artificial_intelligence.py:88
msgid "IA_MODEL_UPDATE_ERROR"
msgstr ""

#: src/backend/models/auth.py:47 src/backend/models/auth.py:99
#: src/backend/models/user.py:40 src/backend/rest/auth.py:70
msgid "BAD_USERNAME"
msgstr ""

#: src/backend/models/auth.py:49 src/backend/models/user.py:42
msgid "BAD_PASSWORD"
msgstr ""

#: src/backend/models/auth.py:51
msgid "USER_DELETED"
msgstr ""

#: src/backend/models/auth.py:53
msgid "USER_DISABLED"
msgstr ""

#: src/backend/models/auth.py:71 src/backend/models/auth.py:81
#: src/backend/models/roles.py:54
msgid "ROLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/auth.py:154
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/models/auth.py:194
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/auth.py:213
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/auth.py:317 src/backend/models/auth.py:332
#: src/backend/models/auth.py:340
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr ""

#: src/backend/models/auth.py:352 src/backend/rest/auth.py:108
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr ""

#: src/backend/models/auth.py:354 src/backend/models/auth.py:555
#: src/backend/models/auth.py:561 src/backend/rest/auth.py:110
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr ""

#: src/backend/models/auth.py:537 src/backend/models/auth.py:543
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr ""

#: src/backend/models/auth.py:539 src/backend/models/auth.py:545
#: src/backend/models/auth.py:551 src/backend/models/auth.py:557
#: src/backend/models/auth.py:563
msgid "LDAP_SYNCHRO_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:52
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:55
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr ""

#: src/backend/models/custom_fields.py:97
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:117
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/doctypes.py:51
msgid "DOCTYPE_ALREADY_EXIST"
msgstr ""

#: src/backend/models/doctypes.py:91
msgid "UPDATE_DOCTYPE_ERROR"
msgstr ""

#: src/backend/models/forms.py:77
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/forms.py:97
msgid "GET_DEFAULT_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:118
msgid "UPDATE_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:137
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/forms.py:187
msgid "ADD_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:190
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/inputs.py:54
msgid "INPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/inputs.py:90
msgid "INPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/inputs.py:107
msgid "INPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/mailcollect.py:76
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:69
msgid "OUTPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:89
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:110
msgid "OUTPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:127
msgid "OUTPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:57
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:78
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:97
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:129
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:132
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/privileges.py:35 src/backend/models/privileges.py:53
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr ""

#: src/backend/models/roles.py:111
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr ""

#: src/backend/models/roles.py:130
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:69
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/splitter.py:110
msgid "UPDATE_SETTINGS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:132
msgid "INSERT_PAGE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:193
msgid "GET_BATCH_ERROR"
msgstr ""

#: src/backend/models/splitter.py:213
msgid "GET_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:232 src/backend/models/splitter.py:252
msgid "GET_PAGES_ERROR"
msgstr ""

#: src/backend/models/splitter.py:271
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:291
msgid "GET_DOCUMENT_ERROR"
msgstr ""

#: src/backend/models/splitter.py:310
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/status.py:37
msgid "NO_STATUS"
msgstr ""

#: src/backend/models/tasks_watcher.py:72
msgid "UPDATE_TASK_ERROR"
msgstr ""

#: src/backend/models/user.py:44
msgid "USER"
msgstr ""

#: src/backend/models/user.py:44
msgid "ALREADY_REGISTERED"
msgstr ""

#: src/backend/models/verifier.py:92 src/backend/models/verifier.py:110
msgid "INVOICE_UPDATE_ERROR"
msgstr ""

#: src/backend/rest/auth.py:45 src/backend/rest/auth.py:74
msgid "PGSQL_ERROR"
msgstr ""

#: src/backend/rest/auth.py:133 src/backend/rest/auth.py:161
#: src/backend/rest/auth.py:176
msgid "REQUEST_MODIFS_ERROR"
msgstr ""

#: src/backend/rest/auth.py:146
msgid "RETRIEVE_LOGIN_METHODS_ERROR"
msgstr ""

#: src/backend/rest/splitter.py:39 src/backend/rest/verifier.py:37
msgid "UNKNOW_ERROR"
msgstr ""

