# French translations for Open-Capture
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the project
# FIRST AUTHOR <nathan.cheval@edissyum.com>, 2021.
msgid ""
msgstr ""
"Project-Id-Version:  0.1\n"
"Report-Msgid-Bugs-To: nathan.cheval@edissyum.com\n"
"POT-Creation-Date: 2025-07-23 11:43+0200\n"
"PO-Revision-Date: 2019-09-02 17:48+0200\n"
"Last-Translator: Nathan CHEVAL <nathan.cheval@edissyum.com>\n"
"Language: fr\n"
"Language-Team: fr <nathan.cheval@edissyum.com>\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: launch_worker_mail.py:276 launch_worker_mail.py:346
msgid "NO_SUBJECT"
msgstr "Sans objet"

#: custom/acc/src/backend/process_queue_splitter.py:232
#: custom/acc/src/backend/process_queue_verifier.py:198
#: custom/edissyum/src/backend/process_queue_verifier.py:185
#: custom/test/src/backend/process_queue_verifier.py:189
msgid "FILE_UPLOADED_WORKFLOW"
msgstr "Fichier téléversé avec le workflow"

#: custom/edissyum/src/backend/process_queue_splitter.py:244
#: custom/test/src/backend/process_queue_splitter.py:237
msgid "BATCH"
msgstr "Lot"

#: custom/edissyum/src/backend/process_queue_splitter.py:244
#: custom/test/src/backend/process_queue_splitter.py:237
msgid "CREATED_USING"
msgstr "créé avec le workflow"

#: custom/edissyum/src/backend/process_queue_splitter.py:266
#: custom/test/src/backend/process_queue_splitter.py:259
#: src/backend/controllers/splitter.py:511
msgid "DOCUMENT"
msgstr "Document"

#: custom/edissyum/src/backend/process_queue_splitter.py:266
#: custom/test/src/backend/process_queue_splitter.py:259
#: src/backend/controllers/splitter.py:511
msgid "CREATED_ON_BATCH"
msgstr "créé sur le lot"

#: src/backend/functions.py:43 src/backend/functions.py:55
#: src/backend/functions.py:60
msgid "NO_DATA_OR_DATA_MISSING"
msgstr "Les données obligatoires sont manquantes ou incorrectes"

#: src/backend/functions.py:52
msgid "JSON_ERROR"
msgstr "La construction du JSON est incorrect"

#: src/backend/functions.py:55
msgid "IS_NOT"
msgstr "n'est pas de type"

#: src/backend/functions.py:115 src/backend/functions.py:133
#: src/backend/functions.py:143
msgid "UPLOAD_ERRROR"
msgstr "Erreur lors de l'upload de(s) fichier(s)"

#: src/backend/functions.py:116
msgid "FORMATS_FILE_NOT_FOUND"
msgstr ""
"Le fichier contenant les extensions autorisées et les types MIME associés"
" est introuvable"

#: src/backend/functions.py:134
msgid "FILE_EXTENSION_NOT_ALLOWED"
msgstr "L'extension du fichier n'est pas autorisée"

#: src/backend/functions.py:144
msgid "FILE_MIME_NOT_ALLOWED"
msgstr "Le type MIME du fichier ne correspond pas à l'extension"

#: src/backend/scripting_functions.py:80
msgid "WORFKLOW_NOT_FOUND"
msgstr "Le workflow n'existe pas"

#: src/backend/controllers/verifier.py:627
#: src/backend/controllers/workflow.py:448
#: src/backend/scripting_functions.py:153
#: src/backend/scripting_functions.py:212
msgid "SCRIPT_CONTAINS_NOT_ALLOWED_CODE"
msgstr "Le script contient du code non autorisé :"

#: src/backend/splitter_exports.py:100
msgid "OUTPUT_NOT_FOUND"
msgstr "La chaîne sortante n'existe pas"

#: src/backend/models/outputs.py:101 src/backend/splitter_exports.py:135
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr "Le type de chaîne sortante n'existe pas"

#: src/backend/splitter_exports.py:186 src/backend/splitter_exports.py:333
msgid "EXPORT_PDF_ERROR"
msgstr "Erreur lors de l'export PDF"

#: src/backend/splitter_exports.py:263
msgid "EXPORT_VERIFIER_ERROR"
msgstr "Erreur lors de l'export vers le Verifier"

#: src/backend/splitter_exports.py:274
msgid "EXPORT_OPENCAPTUREFORMEM_ERROR"
msgstr "Erreur lors de l'export vers Open-Capture For MEM"

#: src/backend/splitter_exports.py:298 src/backend/splitter_exports.py:366
msgid "EXPORT_XML_ERROR"
msgstr "Erreur lors de l'export XML"

#: src/backend/splitter_exports.py:391
msgid "CHECK_FOLDER_ERROR"
msgstr "Erreur lors de la vérification du dossier"

#: src/backend/splitter_exports.py:392
msgid "FOLDER_DOES_NOT_EXIST"
msgstr "Dossier inexistant"

#: src/backend/splitter_exports.py:412
msgid "OPENADS_ADD_DOC_ERROR"
msgstr "Erreur lors de l'envoi de document à OpenADS"

#: src/backend/verifier_exports.py:180 src/backend/verifier_exports.py:183
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Le dossier de destination XML n'existe pas"

#: src/backend/verifier_exports.py:391 src/backend/verifier_exports.py:394
#: src/backend/verifier_exports.py:484 src/backend/verifier_exports.py:487
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Le dossier de destination PDF n'existe pas"

#: src/backend/verifier_exports.py:574 src/backend/verifier_exports.py:609
#: src/backend/verifier_exports.py:615 src/backend/verifier_exports.py:697
msgid "EXPORT_COOG_ERROR"
msgstr "Erreur lors de l'export vers COOG"

#: src/backend/verifier_exports.py:575
msgid "COOG_JSON_ERROR"
msgstr "Le JSON de l'export vers COOG est incorrect"

#: src/backend/verifier_exports.py:621
msgid "COOG_WS_INFO_WRONG"
msgstr "Les informations de connexion à COOG sont erronées"

#: src/backend/verifier_exports.py:627
msgid "COOG_WS_INFO_EMPTY"
msgstr "Les informations de connexion à COOG sont vides"

#: src/backend/verifier_exports.py:643 src/backend/verifier_exports.py:671
#, fuzzy
msgid "EXPORT_OPENCRM_ERROR"
msgstr "Erreur lors de l'export vers MEM Courrier"

#: src/backend/verifier_exports.py:672
#, fuzzy
msgid "OPENCRM_JSON_ERROR"
msgstr "Le JSON de l'export vers COOG est incorrect"

#: src/backend/verifier_exports.py:703
#, fuzzy
msgid "OPENCRM_WS_INFO_WRONG"
msgstr "Les informations de connexion à MEM Courrier sont erronées"

#: src/backend/verifier_exports.py:709
#, fuzzy
msgid "OPENCRM_WS_INFO_EMPTY"
msgstr "Les informations de connexion à MEM Courrier sont vides"

#: src/backend/verifier_exports.py:895 src/backend/verifier_exports.py:901
#: src/backend/verifier_exports.py:907
msgid "EXPORT_MEM_ERROR"
msgstr "Erreur lors de l'export vers MEM Courrier"

#: src/backend/verifier_exports.py:902
msgid "PDF_FILE_NOT_FOUND"
msgstr "Le fichier PDF est introuvable"

#: src/backend/verifier_exports.py:913
msgid "MEM_WS_INFO_WRONG"
msgstr "Les informations de connexion à MEM Courrier sont erronées"

#: src/backend/verifier_exports.py:919
msgid "MEM_WS_INFO_EMPTY"
msgstr "Les informations de connexion à MEM Courrier sont vides"

#: src/backend/classes/COOGWebServices.py:44
#: src/backend/classes/MEMWebServices.py:40
#: src/backend/classes/OpenCRMWebServices.py:44
msgid "HOST_NOT_FOUND"
msgstr "L'URL de l'hôte n'existe pas"

#: src/backend/classes/COOGWebServices.py:46
#: src/backend/classes/COOGWebServices.py:52
#: src/backend/classes/OpenCRMWebServices.py:46
#: src/backend/classes/OpenCRMWebServices.py:52
msgid "SERVER_ERROR"
msgstr "Erreur serveur"

#: src/backend/classes/Mail.py:270
msgid "FROM"
msgstr "De"

#: src/backend/classes/Mail.py:271
msgid "SEND"
msgstr "Envoyé"

#: src/backend/classes/Mail.py:272
msgid "TO"
msgstr "À"

#: src/backend/classes/Mail.py:274
msgid "COPIES"
msgstr "Copies"

#: src/backend/classes/Mail.py:275
msgid "SUBJECT"
msgstr "Sujet"

#: src/backend/classes/OpenCaptureForMEMWebServices.py:44
msgid "HOST_NOT_FOUND_OR_OTHER_ERROR"
msgstr "L'URL de l'hôte n'existe pas ou une autre erreur est survenue"

#: src/backend/classes/SMTP.py:228
msgid "RESET_PASSWORD"
msgstr "Réinitialiser le mot de passe"

#: src/backend/classes/SMTP.py:230
msgid "FORGOT_EMAIL_HEADER"
msgstr ""
"Bonjour,<br/><br/>Vous avez demandé à réinitialiser le mot de passe de "
"votre compte Open-Capture.<br/><br/>Pour modifier votre mot de passe, "
"veuillez cliquer sur le lien ci-dessous :<br/><br/>"

#: src/backend/classes/SMTP.py:230
msgid "CLICK_HERE"
msgstr "Cliquez ici"

#: src/backend/classes/SMTP.py:230
msgid "FORGOT_EMAIL_FOOTER"
msgstr ""
"<br/><br/>Si vous n'êtes pas à l'origine de cette demande, merci "
"d'ignorer cet e-mail."

#: src/backend/classes/SMTP.py:247
msgid "SMTP_TEST_SEND"
msgstr "Test d'envoi de mail"

#: src/backend/classes/SMTP.py:248
msgid "SMTP_TEST_SEND_BODY"
msgstr "Ceci est un test d'envoi de mail depuis l'application Open-Capture"

#: src/backend/controllers/accounts.py:82 src/backend/models/accounts.py:61
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du compte tiers"

#: src/backend/controllers/accounts.py:95
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de l'adresse"

#: src/backend/controllers/accounts.py:122
#: src/backend/controllers/accounts.py:270
#: src/backend/controllers/accounts.py:276
#: src/backend/controllers/accounts.py:313
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr "Erreur lors de la mise à jour des positions du compte tiers"

#: src/backend/controllers/accounts.py:149
#: src/backend/controllers/accounts.py:307
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr "Erreur lors de la mise à jour des pages du compte tiers"

#: src/backend/controllers/accounts.py:215
#: src/backend/controllers/accounts.py:233
#: src/backend/controllers/accounts.py:239
msgid "UPDATE_SUPPLIER_ERROR"
msgstr "Erreur lors de la mise à jour du tiers"

#: src/backend/controllers/accounts.py:216
#: src/backend/controllers/accounts.py:469
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "Un compte tiers existe déjà avec ce numéro de TVA ou ce numéro DUNS"

#: src/backend/controllers/accounts.py:228
msgid "SUPPLIER_UPDATED"
msgstr "Mise à jour du compte tiers&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:341
#: src/backend/controllers/accounts.py:347
#: src/backend/controllers/accounts.py:372
#: src/backend/controllers/accounts.py:379 src/backend/models/accounts.py:127
msgid "UPDATE_ADDRESS_ERROR"
msgstr "Erreur lors de la mise à jour de l'adresse"

#: src/backend/controllers/accounts.py:403 src/backend/models/accounts.py:147
msgid "CREATE_ADDRESS_ERROR"
msgstr "Erreur lors de la création de l'adresse"

#: src/backend/controllers/accounts.py:454
msgid "SUPPLIER_CREATED"
msgstr "Création du compte tiers&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:462
#: src/backend/controllers/accounts.py:468 src/backend/models/accounts.py:167
msgid "CREATE_SUPPLIER_ERROR"
msgstr "Erreur lors de la création du compte tiers"

#: src/backend/controllers/accounts.py:506 src/backend/controllers/user.py:260
#: src/backend/controllers/user.py:290 src/backend/models/accounts.py:225
#: src/backend/models/accounts.py:248 src/backend/models/accounts.py:267
#: src/backend/models/user.py:225
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du compte client"

#: src/backend/controllers/accounts.py:570
msgid "CUSTOMER_UPDATED"
msgstr "Mise à jour du compte client&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:575
#: src/backend/controllers/accounts.py:581
#: src/backend/controllers/splitter.py:334 src/backend/models/accounts.py:289
msgid "UPDATE_CUSTOMER_ERROR"
msgstr "Erreur lors de la mise à jour du compte client"

#: src/backend/controllers/accounts.py:609
msgid "CUSTOMER_CREATED"
msgstr "Création du compte client&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:617
#: src/backend/controllers/accounts.py:623 src/backend/models/accounts.py:309
msgid "CREATE_CUSTOMER_ERROR"
msgstr "Erreur lors de la création du compte client"

#: src/backend/controllers/accounts.py:624
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "Un compte client existe déjà avec ce numéro de TVA"

#: src/backend/controllers/accounts.py:640
msgid "CUSTOMER_DELETED"
msgstr "Suppression du compte client&nbsp<strong>%(customer)s</strong>"

#: src/backend/controllers/accounts.py:645
#: src/backend/controllers/accounts.py:651 src/backend/models/accounts.py:331
msgid "DELETE_CUSTOMER_ERROR"
msgstr "Erreur lors de la suppression du compte client"

#: src/backend/controllers/accounts.py:667
msgid "SUPPLIER_DELETED"
msgstr "Suppression du compte tiers&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:672
msgid "DELETE_SUPPLIER_ERROR"
msgstr "Erreur lors de la suppression du compte tiers"

#: src/backend/controllers/accounts.py:801
#, fuzzy
msgid "CIVILITY_DELETED"
msgstr "Suppression du compte tiers&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:806
#, fuzzy
msgid "DELETE_CIVILITY_ERROR"
msgstr "Erreur lors de la suppression du rôle"

#: src/backend/controllers/accounts.py:807
#, fuzzy
msgid "CIVILITY_NOT_FOUND"
msgstr "Fichier introuvable"

#: src/backend/controllers/accounts.py:821
#, fuzzy
msgid "CIVILITY_CREATED"
msgstr "Création du compte tiers&nbsp<strong>%(supplier)s</strong>"

#: src/backend/controllers/accounts.py:829
#: src/backend/controllers/accounts.py:835 src/backend/models/accounts.py:412
#, fuzzy
msgid "CREATE_CIVILITY_ERROR"
msgstr "Erreur lors de la création du rôle"

#: src/backend/controllers/accounts.py:836
#, fuzzy
msgid "CIVILITY_ALREADY_EXISTS"
msgstr "Le type de document existe déjà"

#: src/backend/controllers/artificial_intelligence.py:74
#: src/backend/controllers/artificial_intelligence.py:376
#: src/backend/controllers/artificial_intelligence.py:402
msgid "GET_IA_MODEL_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du modèle d'apprentissage"

#: src/backend/controllers/artificial_intelligence.py:99
msgid "CREATE_IA_MODEL_ERROR"
msgstr "Erreur lors de la création du modèle d'apprentissage"

#: src/backend/controllers/artificial_intelligence.py:121
msgid "DELETE_AI_MODEL"
msgstr "Suppression du modèle&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:160
msgid "UPDATE_AI_MODEL"
msgstr "Mise à jour du modèle&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:165
msgid "UPDATE_IA_MODEL_ERROR"
msgstr "Erreur lors de la mise à jour du modèle d'apprentissage"

#: src/backend/controllers/artificial_intelligence.py:228
msgid "CREATE_AI_MODEL"
msgstr "Création du modèle&nbsp;<strong>%(model)s</strong>"

#: src/backend/controllers/artificial_intelligence.py:377
#: src/backend/controllers/artificial_intelligence.py:403
#: src/backend/models/artificial_intelligence.py:59
msgid "IA_MODEL_DOESNT_EXISTS"
msgstr "Le modèle d'apprentissage n'existe pas"

#: src/backend/controllers/artificial_intelligence.py:439
msgid "RENAME_AI_MODEL_ERROR"
msgstr "Erreur lors de la modification du modèle d'intelligence artificielle"

#: src/backend/controllers/artificial_intelligence.py:440
msgid "FILE_DOESNT_EXISTS"
msgstr "Le fichier de ce modèle n'existe pas"

#: src/backend/controllers/attachments.py:90
msgid "UPLOAD_ATTACHMENTS_VERIFIER"
msgstr ""
"Téléversement d'une pièce jointe dans le document "
"n°<strong>%(document_id)s</strong>"

#: src/backend/controllers/attachments.py:92
msgid "UPLOAD_ATTACHMENTS_SPLITTER"
msgstr ""
"Téléversement d'une pièce jointe dans le lot "
"n°<strong>%(batch_id)s</strong>"

#: src/backend/controllers/attachments.py:161
msgid "DELETE_ATTACHMENTS"
msgstr "Suppression de la pièce jointe n°<strong>%(attachment_id)s</strong>"

#: src/backend/controllers/auth.py:57 src/backend/controllers/auth.py:86
msgid "PGSQL_ERROR"
msgstr "Erreur lors de la connexion à la base de donnée"

#: src/backend/controllers/auth.py:81 src/backend/controllers/auth.py:374
#: src/backend/controllers/auth.py:389 src/backend/controllers/auth.py:416
#: src/backend/controllers/auth.py:616 src/backend/controllers/auth.py:627
#: src/backend/controllers/auth.py:637
msgid "LOGIN_ERROR"
msgstr "Erreur lors de la connexion"

#: src/backend/controllers/auth.py:82 src/backend/models/auth.py:43
msgid "BAD_AUTHENTICATION"
msgstr "Les informations d'authentification sont incorrectes"

#: src/backend/controllers/auth.py:143 src/backend/controllers/auth.py:175
#: src/backend/controllers/auth.py:227 src/backend/controllers/auth.py:281
#: src/backend/controllers/auth.py:310 src/backend/controllers/auth.py:324
#: src/backend/controllers/auth.py:440 src/backend/controllers/auth.py:502
#: src/backend/controllers/auth.py:517
msgid "SESSION_EXPIRED"
msgstr "Votre session à expirée, veuillez vous reconnecter"

#: src/backend/controllers/auth.py:144 src/backend/controllers/auth.py:176
#: src/backend/controllers/auth.py:441 src/backend/controllers/auth.py:455
#: src/backend/controllers/auth.py:502 src/backend/controllers/auth.py:518
#: src/backend/controllers/auth.py:528 src/backend/controllers/auth.py:540
#: src/backend/controllers/auth.py:585
msgid "JWT_ERROR"
msgstr "Erreur lors de l'authentification par token"

#: src/backend/controllers/auth.py:311
msgid "RESET_JWT_ERROR"
msgstr "Erreur lors du décodage du token de réinitialisation"

#: src/backend/controllers/auth.py:325
msgid "UNIQUE_URL_JWT_ERROR"
msgstr "Erreur lors du décodage du token d'URL unique"

#: src/backend/controllers/auth.py:367
msgid "LOGOUT"
msgstr "Déconnexion de l'utilisateur"

#: src/backend/controllers/auth.py:390
msgid "USER_WEBSERVICE"
msgstr ""
"L'utilisateur n'a pas le droit de se connecter à l'application "
"(utilisateur webservice)"

#: src/backend/controllers/auth.py:411 src/backend/controllers/auth.py:482
msgid "LOGIN"
msgstr "Connexion de l'utilisateur"

#: src/backend/controllers/auth.py:455 src/backend/controllers/auth.py:588
msgid "USER_DO_NOT_EXISTS"
msgstr "L'utilisateur n'existe pas en base de données"

#: src/backend/controllers/auth.py:528
msgid "AUTHORIZATION_HEADER_INCORRECT"
msgstr "Le header d'authentification est incorrect ('Bearer' ou 'Basic' attendu)"

#: src/backend/controllers/auth.py:540
msgid "ACCOUNT_ALREADY_LOGGED"
msgstr ""
"Votre compte est déjà connecté sur un autre poste. Une seule connexion "
"est autorisée par utilisateur"

#: src/backend/controllers/auth.py:572
msgid "FIRSTNAME"
msgstr "Prénom"

#: src/backend/controllers/auth.py:587 src/backend/controllers/auth.py:592
msgid "REST_ERROR"
msgstr "Erreur lors de l'authentification avec l'utilisateur webservice"

#: src/backend/controllers/auth.py:592
msgid "PASSWORD_INCORRECT"
msgstr "Le mot de passe est incorrect"

#: src/backend/controllers/auth.py:597
msgid "AUTH_ERROR"
msgstr "Erreur lors de l'authentification"

#: src/backend/controllers/auth.py:597
msgid "VALID_TOKEN_OR_USER_WS_MANDATORY"
msgstr "Un token valide ou un compte de webservice est obligatoire"

#: src/backend/controllers/auth.py:628
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr "Plusieurs méthodes d'authentification sont activées"

#: src/backend/controllers/auth.py:652
msgid "LDAP_ERROR"
msgstr "Erreur LDAP"

#: src/backend/controllers/auth.py:653 src/backend/models/auth.py:136
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr "Aucune configurations LDAP n'est disponible"

#: src/backend/controllers/auth.py:664 src/backend/models/auth.py:161
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr "Erreur lors de la mise à jour de la méthode d'authentification"

#: src/backend/controllers/auth.py:679
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr "Echec lors de l'exécution de la requête"

#: src/backend/controllers/auth.py:691
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr "Erreur lors de la désactivation de cette méthode"

#: src/backend/controllers/auth.py:703
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr "Erreur lors de l'activation de cette méthode"

#: src/backend/controllers/auth.py:733 src/backend/controllers/auth.py:926
#: src/backend/controllers/auth.py:977 src/backend/controllers/auth.py:992
#: src/backend/controllers/auth.py:1000 src/backend/controllers/auth.py:1006
msgid "LDAP_CONNECTION_ERROR"
msgstr "Impossible de se connecter au serveur LDAP"

#: src/backend/controllers/auth.py:734
msgid "LOGIN_LDAP_ERROR"
msgstr "Information(s) de connexion incorrecte(s)"

#: src/backend/controllers/auth.py:915 src/backend/controllers/auth.py:920
#: src/backend/controllers/auth.py:925 src/backend/controllers/auth.py:930
#: src/backend/controllers/auth.py:935
msgid "LDAP_SYNCHRO_ERROR"
msgstr "Erreur lors de la synchronisation LDAP"

#: src/backend/controllers/auth.py:916 src/backend/controllers/auth.py:921
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr "Information(s) de synchronisation incorrecte(s)"

#: src/backend/controllers/auth.py:931 src/backend/controllers/auth.py:936
#: src/backend/controllers/auth.py:1012
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr "Informations non complètes"

#: src/backend/controllers/auth.py:975 src/backend/controllers/auth.py:990
#: src/backend/controllers/auth.py:998
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr "Information(s) incorrecte(s)"

#: src/backend/controllers/auth.py:1010
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr "Il manque une ou plusieurs informations pour établir la connexion"

#: src/backend/controllers/config.py:64
msgid "LANGUAGE_CHANGED"
msgstr "Changemement de la langue vers&nbsp;<strong>%(lang)s</strong>"

#: src/backend/controllers/config.py:79
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr "Erreur lors de la récupération de la configuration"

#: src/backend/controllers/config.py:109
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr "Erreur lors de la récupération des configurations"

#: src/backend/controllers/config.py:140
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr "Erreur lors de la récupération des docservers"

#: src/backend/controllers/config.py:178 src/backend/controllers/config.py:193
msgid "RETRIEVE_REGEX_ERRORS"
msgstr "Erreur lors de la récupération des regex"

#: src/backend/controllers/config.py:204 src/backend/controllers/config.py:233
#: src/backend/controllers/config.py:245 src/backend/controllers/config.py:272
#: src/backend/models/config.py:199 src/backend/models/config.py:223
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr "Erreur lors de la mise à jour de la configuration"

#: src/backend/controllers/config.py:205 src/backend/controllers/config.py:246
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr "La valeur d'expiration du token ne peut être inférieure à 0"

#: src/backend/controllers/config.py:228 src/backend/controllers/config.py:267
msgid "UPDATE_CONFIGURATION"
msgstr "Mise à jour de la configuration&nbsp;<strong>%(config)s</strong>"

#: src/backend/controllers/config.py:295
msgid "UPDATE_REGEX"
msgstr "Mise à jour de la regex&nbsp;<strong>%(regex)s</strong>"

#: src/backend/controllers/config.py:300 src/backend/models/config.py:245
msgid "UPDATE_REGEX_ERROR"
msgstr "Erreur lors de la mise à jour des REGEX"

#: src/backend/controllers/config.py:322
msgid "UPDATE_DOCSERVER"
msgstr "Mise à jour de la zone de stockage&nbsp;<strong>%(docserver)s</strong>"

#: src/backend/controllers/config.py:327 src/backend/models/config.py:271
msgid "UPDATE_DOCSERVER_ERROR"
msgstr "Erreur lors de la mise à jour de la docserver"

#: src/backend/controllers/config.py:369 src/backend/controllers/config.py:385
#: src/backend/controllers/config.py:390
msgid "ERROR_UPDATING_IMAGE"
msgstr "Erreur lors de la modification de l'image de connexion"

#: src/backend/controllers/config.py:370 src/backend/controllers/config.py:386
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr "Le dossier d'image du custom n'est pas accessible"

#: src/backend/controllers/config.py:380
msgid "UPDATE_LOGIN_IMAGE"
msgstr "Modification de l'image de login"

#: src/backend/controllers/config.py:391 src/backend/controllers/user.py:556
msgid "CUSTOM_NOT_PRESENT"
msgstr "Aucun custom n'est présent"

#: src/backend/controllers/custom_fields.py:33
#: src/backend/controllers/custom_fields.py:49
#: src/backend/controllers/custom_fields.py:62
msgid "CUSTOM_FIELDS_ERROR"
msgstr "Erreur sur les champs personnalisés"

#: src/backend/controllers/custom_fields.py:75
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr "Erreur lors de la suppression du champ personnalisé"

#: src/backend/controllers/doctypes.py:39
#: src/backend/controllers/doctypes.py:81 src/backend/models/doctypes.py:131
#: src/backend/models/doctypes.py:134
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr "Erreur lors de la modification du type de document par défaut"

#: src/backend/controllers/doctypes.py:45 src/backend/models/doctypes.py:51
msgid "ADD_DOCTYPE_ERROR"
msgstr "Erreur lors de l'ajout d'un type de document"

#: src/backend/controllers/doctypes.py:65
#: src/backend/controllers/doctypes.py:101
#: src/backend/controllers/doctypes.py:114
#: src/backend/controllers/doctypes.py:166
#: src/backend/controllers/doctypes.py:197
#: src/backend/controllers/doctypes.py:236
#: src/backend/controllers/doctypes.py:264
#: src/backend/controllers/doctypes.py:287
#: src/backend/controllers/doctypes.py:315
msgid "DOCTYPE_ERROR"
msgstr "Erreur sur les types de documents"

#: src/backend/controllers/doctypes.py:133
msgid "BUNDLESEPARATOR"
msgstr "SEPARATEUR DE LOT / BUNDLE SEPARATOR"

#: src/backend/controllers/doctypes.py:140
msgid "DOCUMENTSEPARATOR"
msgstr "SEPARATEUR DE DOCUMENT / DOCUMENT SEPARATOR"

#: src/backend/controllers/doctypes.py:159
msgid "DOCTYPESEPARATOR"
msgstr "SEPARATEUR AVEC TYPE DE DOCUMENT / SEPARATOR WITH DOCUMENT TYPE"

#: src/backend/controllers/forms.py:72 src/backend/controllers/forms.py:106
#: src/backend/controllers/forms.py:229
msgid "FORMS_ERROR"
msgstr "Erreur sur les formulaires"

#: src/backend/controllers/forms.py:101
msgid "CREATE_FORM"
msgstr "Création du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:121 src/backend/controllers/forms.py:170
#: src/backend/models/forms.py:66
msgid "GET_FORM_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du formulaire"

#: src/backend/controllers/forms.py:153
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr "Erreur lors de la récupération des champs du formulaire"

#: src/backend/controllers/forms.py:218
msgid "UPDATE_FORM"
msgstr "Mise à jour du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:223 src/backend/controllers/forms.py:381
#: src/backend/controllers/forms.py:387
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du formulaire"

#: src/backend/controllers/forms.py:245
msgid "DELETE_FORM"
msgstr "Suppression du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:250 src/backend/controllers/forms.py:256
msgid "DELETE_FORM_ERROR"
msgstr "Erreur lors de la suppression du formulaire"

#: src/backend/controllers/forms.py:265 src/backend/controllers/outputs.py:66
#: src/backend/controllers/positions_masks.py:148
#: src/backend/controllers/workflow.py:120
msgid "COPY_OF"
msgstr "Copie de"

#: src/backend/controllers/forms.py:286
msgid "DUPLICATE_FORM"
msgstr "Duplication du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:291 src/backend/controllers/forms.py:297
msgid "DUPLICATE_FORM_ERROR"
msgstr "Erreur lors de la duplication du formulaire"

#: src/backend/controllers/forms.py:313
msgid "DISABLE_FORM"
msgstr "Désactivation du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:318 src/backend/controllers/forms.py:324
msgid "DISABLE_FORM_ERROR"
msgstr "Erreur lors de la désactivation du formulaire"

#: src/backend/controllers/forms.py:340
msgid "ENABLE_FORM"
msgstr "Activation du formulaire&nbsp;<strong>%(form)s</strong>"

#: src/backend/controllers/forms.py:345 src/backend/controllers/forms.py:351
msgid "ENABLE_FORM_ERROR"
msgstr "Erreur lors de l'activation du formulaire"

#: src/backend/controllers/forms.py:367
msgid "GET_FORMS_FIELDS_ERROR"
msgstr "Erreur lors de la récupération des champs du formulaire"

#: src/backend/controllers/history.py:31
msgid "ADD_HISTORY_ERROR"
msgstr "Erreur lors de l'ajout dans l'historique"

#: src/backend/controllers/mailcollect.py:39
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr "Erreur lors de la récupération des processus MailCollect"

#: src/backend/controllers/mailcollect.py:54
msgid "UPDATE_MAILCOLLECT_PROCESS"
msgstr "Mise à jour du processus MailCollect&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:62
msgid "UPDATE_PROCESS_ERROR"
msgstr "Erreur lors de la mise à jour du processus MailCollect"

#: src/backend/controllers/mailcollect.py:77
msgid "CREATE_MAILCOLLECT_PROCESS"
msgstr "Création du processus MailCollect&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:83
msgid "CREATE_PROCESS_ERROR"
msgstr "Erreur lors de la création d'un processus MailCollect"

#: src/backend/controllers/mailcollect.py:99
msgid "DELETE_MAILCOLLECT_PROCESS"
msgstr "Suppression du processus MailCollect&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:104
#: src/backend/controllers/mailcollect.py:110
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Erreur lors de la suppression d'un processus MailCollect"

#: src/backend/controllers/mailcollect.py:126
msgid "ENABLE_MAILCOLLECT_PROCESS"
msgstr "Activation du processus MailCollect&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:131
#: src/backend/controllers/mailcollect.py:137
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Erreur lors de l'activation d'un processus MailCollect"

#: src/backend/controllers/mailcollect.py:153
msgid "DISABLE_MAILCOLLECT_PROCESS"
msgstr "Désactivation du processus MailCollect&nbsp;<strong>%(process)s</strong>"

#: src/backend/controllers/mailcollect.py:158
#: src/backend/controllers/mailcollect.py:164
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr "Erreur lors de la désactivation d'un processus MailCollect"

#: src/backend/controllers/mailcollect.py:200
#: src/backend/controllers/mailcollect.py:210
#: src/backend/controllers/mailcollect.py:223
#: src/backend/controllers/mailcollect.py:233
#: src/backend/controllers/mailcollect.py:242
#: src/backend/controllers/mailcollect.py:254
#: src/backend/controllers/mailcollect.py:264
#: src/backend/controllers/mailcollect.py:275
msgid "MAILCOLLECT_ERROR"
msgstr "Erreur MailCollect"

#: src/backend/controllers/outputs.py:75
msgid "DUPLICATE_OUTPUT"
msgstr "Chaîne sortante dupliquée&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:80 src/backend/controllers/outputs.py:86
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr "Erreur lors de la duplication de la chaîne sortante"

#: src/backend/controllers/outputs.py:115
#: src/backend/controllers/outputs.py:144
#: src/backend/controllers/outputs.py:150
msgid "UPDATE_OUTPUT_ERROR"
msgstr "Erreur lors de mise à jour de la chaîne sortante"

#: src/backend/controllers/outputs.py:116
msgid "NOT_ALLOWED_OUTPUT_PATH"
msgstr "Le chemin d'export de la chaîne sortant n'est pas autorisé"

#: src/backend/controllers/outputs.py:139
msgid "UPDATE_OUTPUT"
msgstr "Mise à jour de la chaîne sortante&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:173
msgid "CREATE_OUTPUT"
msgstr "Création de la chaîne sortante&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:181
msgid "CREATE_OUTPUT_ERROR"
msgstr "Erreur lors de la création de la chaîne sortante"

#: src/backend/controllers/outputs.py:194
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de la chaîne sortante"

#: src/backend/controllers/outputs.py:207
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr "Erreur lors de la récupération des types de chaîne sortante"

#: src/backend/controllers/outputs.py:223
msgid "DELETE_OUTPUT"
msgstr "Suppression de la chaîne sortante&nbsp;<strong>%(output)s</strong>"

#: src/backend/controllers/outputs.py:228
#: src/backend/controllers/outputs.py:234
msgid "DELETE_OUTPUT_ERROR"
msgstr "Erreur lors de la suppression de la chaîne sortante"

#: src/backend/controllers/outputs.py:262
#: src/backend/controllers/outputs.py:271
#: src/backend/controllers/outputs.py:278
msgid "OUTPUT_FOLDER_CREATION_ERROR"
msgstr "Erreur lors de la création du dossier de sortie"

#: src/backend/controllers/outputs.py:263
#: src/backend/controllers/workflow.py:65
msgid "FOLDER_NOT_ALLOWED_ERROR"
msgstr "Le chemin de capture n'est pas autorisé"

#: src/backend/controllers/outputs.py:272
#: src/backend/controllers/workflow.py:74
#: src/backend/controllers/workflow.py:353
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr "Problème de permissions pour créer le dossier"

#: src/backend/controllers/outputs.py:279
#: src/backend/controllers/workflow.py:81
msgid "CAN_NOT_ACCESS_FOLDER_PERMISSION_ERROR"
msgstr "Impossible d'accéder au dossier de travail"

#: src/backend/controllers/positions_masks.py:41
#: src/backend/controllers/positions_masks.py:64
#: src/backend/controllers/positions_masks.py:106
#: src/backend/controllers/positions_masks.py:112
msgid "POSITION_MASKS_ERROR"
msgstr "Erreur sur les masques de positionnement"

#: src/backend/controllers/positions_masks.py:55
msgid "CREATE_POSITIONS_MASK"
msgstr "Création du masque de positionnement&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:79
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du masque de positionnement"

#: src/backend/controllers/positions_masks.py:101
msgid "UPDATE_POSITIONS_MASK"
msgstr "Mise à jour du masque de positionnement&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:128
#: src/backend/controllers/positions_masks.py:214
msgid "DELETE_POSITIONS_MASK"
msgstr "Suppression du masque de positionnement&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:133
#: src/backend/controllers/positions_masks.py:139
msgid "DELETE_POSITION_MASK_ERROR"
msgstr "Erreur lors de la suppression du masque de positionnement"

#: src/backend/controllers/positions_masks.py:165
#: src/backend/controllers/positions_masks.py:171
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la duplication du masque de positionnement"

#: src/backend/controllers/positions_masks.py:187
msgid "DISABLE_POSITIONS_MASK"
msgstr "Désactivation du masque de positionnement&nbsp;<strong>%(mask)s</strong>"

#: src/backend/controllers/positions_masks.py:192
#: src/backend/controllers/positions_masks.py:198
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr "Erreur lors de désactivation du masque de positionnement"

#: src/backend/controllers/positions_masks.py:219
#: src/backend/controllers/positions_masks.py:225
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr "Erreur lors de l'activation du masque de positionnement"

#: src/backend/controllers/positions_masks.py:248
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Erreur lors de la mise à jour des positions du masque de positionnement"

#: src/backend/controllers/positions_masks.py:271
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Erreur lors de la mise à jour des pages du masque de positionnement"

#: src/backend/controllers/positions_masks.py:289
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr "Erreur lors de la suppression des positions du masque de positionnement"

#: src/backend/controllers/positions_masks.py:307
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr "Erreur lors de la suppression des pages du masque de positionnement"

#: src/backend/controllers/privileges.py:38
#: src/backend/controllers/privileges.py:66
#: src/backend/controllers/privileges.py:94
msgid "GET_PRIVILEGES_ERROR"
msgstr "Erreur lors de la récupération des privilèges"

#: src/backend/controllers/roles.py:39 src/backend/controllers/user.py:134
#: src/backend/controllers/user.py:150 src/backend/controllers/user.py:231
#: src/backend/models/user.py:155 src/backend/models/user.py:202
msgid "GET_USER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de l'utilisateur"

#: src/backend/controllers/roles.py:49 src/backend/controllers/roles.py:169
msgid "GET_ROLE_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du rôle"

#: src/backend/controllers/roles.py:88
msgid "UPDATE_ROLE"
msgstr "Mise à jour du rôle&nbsp;<strong>%(role)s</strong>"

#: src/backend/controllers/roles.py:93 src/backend/controllers/roles.py:99
#: src/backend/controllers/roles.py:150 src/backend/controllers/roles.py:156
#: src/backend/models/roles.py:85
msgid "UPDATE_ROLE_ERROR"
msgstr "Erreur lors de la mise à jour du rôle"

#: src/backend/controllers/roles.py:121
msgid "CREATE_ROLE"
msgstr "Création du rôle&nbsp;<strong>%(role)s</strong>"

#: src/backend/controllers/roles.py:130 src/backend/models/roles.py:105
msgid "CREATE_ROLE_ERROR"
msgstr "Erreur lors de la création du rôle"

#: src/backend/controllers/roles.py:185
msgid "DELETE_ROLE"
msgstr "Suppression du rôle&nbsp;<strong>%(role)s</strong>"

#: src/backend/controllers/roles.py:190 src/backend/controllers/roles.py:196
msgid "DELETE_ROLE_ERROR"
msgstr "Erreur lors de la suppression du rôle"

#: src/backend/controllers/roles.py:210 src/backend/controllers/roles.py:216
msgid "DISABLE_ROLE_ERROR"
msgstr "Erreur lors de la désactivation du rôle"

#: src/backend/controllers/roles.py:230 src/backend/controllers/roles.py:236
msgid "ENABLE_ROLE_ERROR"
msgstr "Erreur lors de l'activation du rôle"

#: src/backend/controllers/smtp.py:47
msgid "SMTP_TEST_SEND_EMAIL_ERROR"
msgstr "Erreur lors de l'envoi du mail de test"

#: src/backend/controllers/smtp.py:53
msgid "SMTP_TEST_CONNECTION_ERROR"
msgstr "Erreur lors de la connexion SMTP"

#: src/backend/controllers/splitter.py:118
msgid "LOAD_METADATA_ERROR"
msgstr "Erreur du chargement des métadonnées"

#: src/backend/controllers/splitter.py:178
#: src/backend/controllers/verifier.py:178
msgid "AT"
msgstr "à"

#: src/backend/controllers/splitter.py:210
msgid "FORM_UNDEFINED"
msgstr "Formulaire non défini"

#: src/backend/controllers/splitter.py:213
msgid "CUSTOMER_UNDEFINED"
msgstr "Compte client non défini"

#: src/backend/controllers/splitter.py:273
#: src/backend/controllers/splitter.py:304
#: src/backend/controllers/splitter.py:324
msgid "BATCH_NOT_FOUND"
msgstr "Lot non trouvé"

#: src/backend/controllers/splitter.py:274
#: src/backend/controllers/splitter.py:305
#: src/backend/controllers/splitter.py:325
msgid "BATCH_ID_NOT_FOUND"
msgstr "Lot %(id)s non trouvé"

#: src/backend/controllers/splitter.py:288
msgid "DELETE_BATCH_SUCCESS"
msgstr "Suppression du lot n°<strong>%(batch_id)s</strong>"

#: src/backend/controllers/splitter.py:293
#: src/backend/controllers/splitter.py:314
#: src/backend/controllers/verifier.py:949
msgid "UPDATE_STATUS_ERROR"
msgstr "Erreur lors de la mise à jour du statut"

#: src/backend/controllers/splitter.py:372
#: src/backend/controllers/splitter.py:385
#: src/backend/controllers/verifier.py:497
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr "Erreur lors de la suppression du verrou"

#: src/backend/controllers/splitter.py:516
msgid "ADD_DOCUMENT_ERROR"
msgstr "Erreur lors de l'ajout d'un document"

#: src/backend/controllers/splitter.py:548
msgid "UPDATE_BATCH_ERROR"
msgstr "Erreur lors de la mise à jour du lot"

#: src/backend/controllers/splitter.py:563
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr "Erreur lors de la mise à jour du document"

#: src/backend/controllers/splitter.py:576
#: src/backend/controllers/verifier.py:471
#: src/backend/controllers/verifier.py:477
msgid "UPDATE_DOCUMENT_ERROR"
msgstr "Erreur lors de la mise à jour du document"

#: src/backend/controllers/splitter.py:594
#: src/backend/controllers/splitter.py:617
#: src/backend/controllers/splitter.py:632
msgid "UPDATE_PAGES_ERROR"
msgstr "Erreur lors de la modification des pages"

#: src/backend/controllers/splitter.py:646
#: src/backend/controllers/splitter.py:653
#: src/backend/controllers/splitter.py:660
msgid "CMIS_CONNECTION_ERROR"
msgstr "Erreur lors de la connexion CMIS"

#: src/backend/controllers/splitter.py:654
msgid "CMIS_FOLDER_ERROR_MESSAGE"
msgstr "Erreur lors de la vérification du répertoire de dépôt"

#: src/backend/controllers/splitter.py:673
msgid "OPENADS_CONNECTION_ERROR"
msgstr "Erreur lors de la connexion OpenADS"

#: src/backend/controllers/splitter.py:773
#: src/backend/controllers/verifier.py:928 src/backend/models/splitter.py:618
#: src/backend/models/verifier.py:206
msgid "GET_TOTALS_ERROR"
msgstr "Erreur lors de la récupération des totaux"

#: src/backend/controllers/splitter.py:882
msgid "GET_BATCH_OUTPUTS_ERROR"
msgstr "Erreur lors de la récupération du workflow"

#: src/backend/controllers/status.py:46
msgid "RETRIEVES_STATUS_ERROR"
msgstr "Erreur lors de la récupération des status"

#: src/backend/controllers/user.py:41 src/backend/controllers/user.py:90
msgid "CREATE_USER_ERROR"
msgstr "Erreur lors de la création de l'utilisateur"

#: src/backend/controllers/user.py:42
msgid "USERNAME_ALREADY_EXISTS"
msgstr "Un utilisateur existe déjà avec ce nom d'utilisateur"

#: src/backend/controllers/user.py:85
msgid "CREATE_USER"
msgstr "Création de l'utilisateur&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:167
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr "Erreur lors de la récupération de l'utilisateur"

#: src/backend/controllers/user.py:193
msgid "USER_FORGOT_SUCCESS"
msgstr ""
"Envoi d'email de réinitialisation de mot de passe pour "
"l'utilisateur&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:198
msgid "SEND_EMAIL_FORGOT_PASSWORD_ERROR"
msgstr "Erreur lors de l'envoi de l'email de réinitialisation du mot de passe"

#: src/backend/controllers/user.py:221
msgid "USER_RESET_PASSWORD_SUCCESS"
msgstr ""
"Mot de passe de l'utilisateur&nbsp;<strong>%(user)s</strong> réinitialisé"
" avec succès"

#: src/backend/controllers/user.py:225 src/backend/controllers/user.py:230
msgid "RESET_PASSWORD_ERROR"
msgstr "Erreur lors de la réinitilisation du mot de passe"

#: src/backend/controllers/user.py:226
msgid "RESET_TOKEN_MISMATCH"
msgstr "Le token de réinitialisation est invalide. Il est peut être expiré"

#: src/backend/controllers/user.py:311
msgid "UPDATE_PROFILE"
msgstr "Mise à jour du profile"

#: src/backend/controllers/user.py:312
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr "L'ancien mot de passe ne corresponds pas"

#: src/backend/controllers/user.py:318
msgid "UPDATE_USER"
msgstr "Mise à jour de l'utilisateur"

#: src/backend/controllers/user.py:319
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr "Les mots de passes ne correspondent pas"

#: src/backend/controllers/user.py:349
msgid "USER_UPDATED"
msgstr "Mise à jour du compte utilisateur&nbsp<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:354 src/backend/controllers/user.py:360
#: src/backend/models/user.py:270 src/backend/models/user.py:336
msgid "UPDATE_USER_ERROR"
msgstr "Erreur lors de la mise à jour de l'utilisateur"

#: src/backend/controllers/user.py:377
msgid "DELETE_USER"
msgstr "Suppression de l'utilisateur&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:384 src/backend/controllers/user.py:390
msgid "DELETE_USER_ERROR"
msgstr "Erreur lors de la suppression de l'utilisateur"

#: src/backend/controllers/user.py:407
msgid "DISABLE_USER"
msgstr "Désactivation de l'utilisateur&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:414 src/backend/controllers/user.py:420
msgid "DISABLE_USER_ERROR"
msgstr "Erreur lors de désactiver de l'utilisateur"

#: src/backend/controllers/user.py:437
msgid "ENABLE_USER"
msgstr "Activation de l'utilisateur&nbsp;<strong>%(user)s</strong>"

#: src/backend/controllers/user.py:444 src/backend/controllers/user.py:450
msgid "ENABLE_USER_ERROR"
msgstr "Erreur lors de l'activation de l'utilisateur"

#: src/backend/controllers/user.py:467 src/backend/controllers/user.py:473
#: src/backend/models/user.py:292
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr "Erreur lors de la mise à jour des comptes clients de l'utilisateur"

#: src/backend/controllers/user.py:488 src/backend/controllers/user.py:495
#: src/backend/models/user.py:314
msgid "UPDATE_FORMS_USER_ERROR"
msgstr "Erreur lors de la mise à jour des formulaires de l'utilisateur"

#: src/backend/controllers/user.py:538
msgid "USER_EXPORT_ERROR"
msgstr "Erreur lors de l'export des utilisateurs"

#: src/backend/controllers/user.py:555 src/backend/controllers/user.py:572
msgid "ERROR_IMPORTING_USER"
msgstr "Erreur lors de l'importation des utilisateurs"

#: src/backend/controllers/user.py:588
msgid "GET_DEFAULT_ROUTE_ERROR"
msgstr "Erreur lors de la récupération de la route par défaut"

#: src/backend/controllers/verifier.py:53
msgid "UPLOAD_DOCUMENTS_ERROR"
msgstr "Erreur lors de l'upload des documents"

#: src/backend/controllers/verifier.py:62
#: src/backend/controllers/verifier.py:78
msgid "RETRY_FROM_MONITORING_ERROR"
msgstr "Erreur lors de la relance du processus"

#: src/backend/controllers/verifier.py:63
#, fuzzy
msgid "PROCESS_NOT_FOUND"
msgstr "L'URL de l'hôte n'existe pas"

#: src/backend/controllers/verifier.py:79 src/backend/rest/attachments.py:90
#: src/backend/rest/attachments.py:101 src/backend/rest/verifier.py:611
msgid "FILE_NOT_FOUND"
msgstr "Fichier introuvable"

#: src/backend/controllers/verifier.py:88 src/backend/rest/splitter.py:51
#: src/backend/rest/verifier.py:103
msgid "UNKNOW_ERROR"
msgstr "Erreur inconnue"

#: src/backend/controllers/verifier.py:142 src/backend/models/splitter.py:222
#: src/backend/models/verifier.py:41
msgid "GET_DOCUMENT_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du document"

#: src/backend/controllers/verifier.py:159 src/backend/models/verifier.py:65
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR"
msgstr "Erreur lors de la récupération du document par token"

#: src/backend/controllers/verifier.py:160
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR_MESSAGE"
msgstr "Aucun document trouvé avec ce token"

#: src/backend/controllers/verifier.py:309
#: src/backend/controllers/verifier.py:411
msgid "UPDATE_DOCUMENT_POSITIONS_ERROR"
msgstr "Erreur lors de la mise à jour des positions du document"

#: src/backend/controllers/verifier.py:332
#: src/backend/controllers/verifier.py:429
msgid "UPDATE_DOCUMENT_PAGES_ERROR"
msgstr "Erreur lors de la mise à jour des pages du document"

#: src/backend/controllers/verifier.py:355
#: src/backend/controllers/verifier.py:373
msgid "UPDATE_DOCUMENT_DATA_ERROR"
msgstr "Erreur lors de la mise à jour des données du document"

#: src/backend/controllers/verifier.py:445
msgid "DELETE_DOCUMENT_SUCCESS"
msgstr "Suppression du document n°<strong>%(document_id)s</strong>"

#: src/backend/controllers/verifier.py:450
#: src/backend/controllers/verifier.py:456
msgid "DELETE_DOCUMENT_ERROR"
msgstr "Erreur lors de la suppression du document"

#: src/backend/controllers/verifier.py:821
#: src/backend/controllers/verifier.py:824
#: src/backend/controllers/verifier.py:841
#: src/backend/controllers/verifier.py:867
#: src/backend/controllers/verifier.py:868
msgid "API_INSEE_ERROR_CONNEXION"
msgstr "Erreur lors de la connexion à l'api de l'INSEE"

#: src/backend/controllers/verifier.py:898
msgid "VAT_NOT_VALID"
msgstr "Numéro de TVA invalide"

#: src/backend/controllers/verifier.py:905
#: src/backend/controllers/verifier.py:906
msgid "VAT_API_ERROR"
msgstr "Impossible de joindre l'API de vérification du numéro de TVA"

#: src/backend/controllers/verifier.py:939
msgid "DOCUMENT_NOT_FOUND"
msgstr "Document non trouvé"

#: src/backend/controllers/verifier.py:940
msgid "DOCUMENT_ID_NOT_FOUND"
msgstr "Document %(id)s non trouvé"

#: src/backend/controllers/verifier.py:1000
msgid "NO_FORM"
msgstr "Pas de formulaire associé"

#: src/backend/controllers/verifier.py:1011
msgid "FORM_NOT_FOUND"
msgstr "Formulaire inexistant"

#: src/backend/controllers/workflow.py:64
#: src/backend/controllers/workflow.py:73
#: src/backend/controllers/workflow.py:80
msgid "WORKFLOW_FOLDER_CREATION_ERROR"
msgstr "Erreur lors de la création du dossier de travail"

#: src/backend/controllers/workflow.py:95
msgid "GET_WORKFLOW_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du workflow"

#: src/backend/controllers/workflow.py:108
msgid "GET_WORKFLOW_BY_WORKFLOW_ID_ERROR"
msgstr "Erreur lors de la récupération du workflow"

#: src/backend/controllers/workflow.py:133
msgid "DUPLICATE_WORKFLOW"
msgstr "Duplication du workflow&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:138
#: src/backend/controllers/workflow.py:144
msgid "DUPLICATE_WORKFLOW_ERROR"
msgstr "Erreur lors de la duplication du workflow"

#: src/backend/controllers/workflow.py:169
#: src/backend/controllers/workflow.py:181
#: src/backend/controllers/workflow.py:192
#: src/backend/controllers/workflow.py:216
msgid "CREATE_WORKFLOW_ERROR"
msgstr "Erreur lors de la création du workflow"

#: src/backend/controllers/workflow.py:170
#: src/backend/controllers/workflow.py:226
msgid "NOT_ALLOWED_INPUT_PATH"
msgstr "Le chemin de capture de la chaîne entrante n'est pas autorisé"

#: src/backend/controllers/workflow.py:182
msgid "WORKFLOW_ID_ALREADY_EXISTS"
msgstr "Le libellé technique du workflow existe déjà"

#: src/backend/controllers/workflow.py:193
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr "Le chemin de capture est déjà paramétré dans une autre chaîne entrante"

#: src/backend/controllers/workflow.py:208
msgid "CREATE_WORKFLOW"
msgstr "Création du workflow&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:225
#: src/backend/controllers/workflow.py:268
#: src/backend/controllers/workflow.py:274
msgid "UPDATE_WORKFLOW_ERROR"
msgstr "Erreur lors de la mise à jour du workflow"

#: src/backend/controllers/workflow.py:263
msgid "UPDATE_WORKFLOW"
msgstr "Mise à jour du workflow&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:291
msgid "DELETE_WORKFLOW"
msgstr "Suppression du workflow&nbsp;<strong>%(workflow)s</strong>"

#: src/backend/controllers/workflow.py:296
#: src/backend/controllers/workflow.py:302
msgid "DELETE_WORKFLOW_ERROR"
msgstr "Erreur lors de la suppression du workflow"

#: src/backend/controllers/workflow.py:352
#: src/backend/controllers/workflow.py:379
msgid "FS_WATCHER_CREATION_ERROR"
msgstr "Erreur lors de la création des paramètres du fs watcher"

#: src/backend/controllers/workflow.py:380
#: src/backend/controllers/workflow.py:432
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr "La configuration du fs watcher est introuvable"

#: src/backend/controllers/workflow.py:385
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr "Le script d'exemple n'existe pas"

#: src/backend/controllers/workflow.py:391
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr "Le dossier des scripts n'existe pas"

#: src/backend/controllers/workflow.py:431
msgid "FS_WATCHER_DELETION_ERROR"
msgstr "Erreur lors de la suppression de l'entrée du fs watcher"

#: src/backend/controllers/workflow.py:458
msgid "LINE"
msgstr "Ligne"

#: src/backend/controllers/workflow.py:459
msgid "COLUMN"
msgstr "colonne"

#: src/backend/models/accounts.py:105
msgid "SUPPLIER_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour du tiers"

#: src/backend/models/artificial_intelligence.py:80
msgid "IA_MODEL_CREATE_ERROR"
msgstr "Erreur lors de la création du modèle d'apprentissage"

#: src/backend/models/artificial_intelligence.py:101
msgid "IA_MODEL_UPDATE_ERROR"
msgstr "Erreur lors de la modification du modèle d'apprentissage"

#: src/backend/models/attachments.py:38
msgid "CREATE_ATTACHMENT_ERROR"
msgstr "Erreur lors de la création de la pièce jointe"

#: src/backend/models/auth.py:45
msgid "USER_DISABLED"
msgstr "Utilisateur desactivé"

#: src/backend/models/auth.py:66 src/backend/models/auth.py:76
#: src/backend/models/roles.py:61
msgid "ROLE_DOESNT_EXISTS"
msgstr "Le rôle n'existe pas"

#: src/backend/models/auth.py:97 src/backend/models/user.py:37
msgid "BAD_USERNAME"
msgstr "Mauvais nom de compte"

#: src/backend/models/auth.py:207
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Erreur lors de la désactivation de cette méthode d'authentification"

#: src/backend/models/auth.py:229
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr "Erreur lors de l'activation de cette méthode d'authentification"

#: src/backend/models/custom_fields.py:57
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr "Erreur lors de la création du champ custom"

#: src/backend/models/custom_fields.py:60
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr "Le champ custom existe déjà"

#: src/backend/models/custom_fields.py:111
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour du champ custom"

#: src/backend/models/custom_fields.py:134
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr "Erreur lors de la suppression du champ custom"

#: src/backend/models/doctypes.py:54
msgid "DOCTYPE_ALREADY_EXIST"
msgstr "Le type de document existe déjà"

#: src/backend/models/doctypes.py:100
msgid "UPDATE_DOCTYPE_ERROR"
msgstr "Erreur lors de la mise à jour du type de document"

#: src/backend/models/forms.py:45
msgid "GET_FORMS_ERROR"
msgstr "Erreur lors de la récupération des formulaires"

#: src/backend/models/forms.py:89
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr "Erreur lors de la récupération des paramètres du formulaire"

#: src/backend/models/forms.py:112
msgid "GET_DEFAULT_FORM_ERROR"
msgstr "Erreur lors de la récupération du formulaire par défaut"

#: src/backend/models/forms.py:136
msgid "UPDATE_FORM_ERROR"
msgstr "Erreur lors de la mise à jour du formulaire"

#: src/backend/models/forms.py:158
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du formulaire"

#: src/backend/models/forms.py:215
msgid "ADD_FORM_ERROR"
msgstr "Erreur lors de la création du formulaire"

#: src/backend/models/forms.py:218
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr "Le libellé de formulaire existe déjà"

#: src/backend/models/mailcollect.py:92
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour d'un processus MailCollect"

#: src/backend/models/outputs.py:78
msgid "OUTPUT_DOESNT_EXISTS"
msgstr "La chaîne sortante n'existe pas"

#: src/backend/models/outputs.py:125
msgid "OUTPUT_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour de la chaîne sortante"

#: src/backend/models/outputs.py:145
msgid "OUTPUT_CREATE_ERROR"
msgstr "Erreur lors de la création de la chaîne sortante"

#: src/backend/models/positions_masks.py:63
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du masque de positionnement"

#: src/backend/models/positions_masks.py:87
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la mise à jour du masque de positionnement"

#: src/backend/models/positions_masks.py:109
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du masque de positionnement"

#: src/backend/models/positions_masks.py:144
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la création du masque de positionnement"

#: src/backend/models/positions_masks.py:147
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr "Le libellé du masque de positionnement existe déjà"

#: src/backend/models/privileges.py:38 src/backend/models/privileges.py:59
#: src/backend/models/privileges.py:83
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr "Erreur lors de la récupération des privilèges"

#: src/backend/models/roles.py:127
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour des privilèges du rôle"

#: src/backend/models/roles.py:149
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr "Erreur lors de la création des privilèges du rôle"

#: src/backend/models/splitter.py:78
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr "Erreur lors de l'obtention de l'index du Splitter"

#: src/backend/models/splitter.py:125
msgid "UPDATE_SETTINGS_ERROR"
msgstr "Erreur lors de la mise à jour des paramètres du Splitter"

#: src/backend/models/splitter.py:150
msgid "INSERT_PAGE_ERROR"
msgstr "Erreur lors de l'insertion des pages du Splitter"

#: src/backend/models/splitter.py:247
msgid "GET_DOCUMENTS_ERROR"
msgstr "Erreur lors de la récupération des documents du Splitter"

#: src/backend/models/splitter.py:269 src/backend/models/splitter.py:292
msgid "GET_PAGES_ERROR"
msgstr "Erreur lors de l'obtention des pages du Splitter"

#: src/backend/models/splitter.py:314
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr "Erreur lors de l'obtention de la valeur des pages source du Splitter"

#: src/backend/models/splitter.py:337
msgid "GET_DOCUMENT_ERROR"
msgstr "Erreur lors de la récupération du document"

#: src/backend/models/splitter.py:359
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr "Erreur lors de l'obtention de l'index maximum du Splitter"

#: src/backend/models/status.py:40
msgid "NO_STATUS"
msgstr "Aucun status existant"

#: src/backend/models/user.py:39
msgid "BAD_PASSWORD"
msgstr "Mauvais mot de passe"

#: src/backend/models/user.py:50
msgid "USER"
msgstr "L'utilisateur"

#: src/backend/models/user.py:50
msgid "ALREADY_REGISTERED"
msgstr "est déjà enregistré"

#: src/backend/models/user.py:178
msgid "GET_USER_BY_MAIL_ERROR"
msgstr "Aucun utilisateur asssocié à cette addresse email"

#: src/backend/models/user.py:247
msgid "GET_FORMS_BY_USER_ID_ERROR"
msgstr "Erreur lors de la récupération des formulaires de l'utilisateur"

#: src/backend/models/verifier.py:129 src/backend/models/verifier.py:150
msgid "DOCUMENT_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour du document"

#: src/backend/models/workflow.py:60 src/backend/models/workflow.py:83
msgid "WORKFLOW_DOESNT_EXISTS"
msgstr "Le workflow n'existe pas"

#: src/backend/models/workflow.py:105
msgid "WORKFLOW_CREATE_ERROR"
msgstr "Erreur lors de la création du modèle workflow"

#: src/backend/models/workflow.py:127
msgid "WORKFLOW_UPDATE_ERROR"
msgstr "Erreur lors de la modification du workflow"

#: src/backend/rest/accounts.py:35 src/backend/rest/accounts.py:57
#: src/backend/rest/accounts.py:70 src/backend/rest/accounts.py:82
#: src/backend/rest/accounts.py:135 src/backend/rest/accounts.py:157
#: src/backend/rest/accounts.py:179 src/backend/rest/accounts.py:205
#: src/backend/rest/accounts.py:232 src/backend/rest/accounts.py:266
#: src/backend/rest/accounts.py:309 src/backend/rest/accounts.py:320
#: src/backend/rest/accounts.py:331 src/backend/rest/accounts.py:360
#: src/backend/rest/accounts.py:389 src/backend/rest/accounts.py:401
#: src/backend/rest/accounts.py:423 src/backend/rest/accounts.py:434
#: src/backend/rest/accounts.py:460 src/backend/rest/accounts.py:485
#: src/backend/rest/accounts.py:517 src/backend/rest/accounts.py:539
#: src/backend/rest/accounts.py:550 src/backend/rest/accounts.py:564
#: src/backend/rest/accounts.py:573 src/backend/rest/accounts.py:582
#: src/backend/rest/artificial_intelligence.py:30
#: src/backend/rest/artificial_intelligence.py:40
#: src/backend/rest/artificial_intelligence.py:51
#: src/backend/rest/artificial_intelligence.py:62
#: src/backend/rest/artificial_intelligence.py:74
#: src/backend/rest/artificial_intelligence.py:91
#: src/backend/rest/artificial_intelligence.py:106
#: src/backend/rest/artificial_intelligence.py:118
#: src/backend/rest/attachments.py:30 src/backend/rest/attachments.py:49
#: src/backend/rest/attachments.py:68 src/backend/rest/attachments.py:77
#: src/backend/rest/attachments.py:86 src/backend/rest/attachments.py:97
#: src/backend/rest/attachments.py:108 src/backend/rest/attachments.py:117
#: src/backend/rest/auth.py:82 src/backend/rest/auth.py:131
#: src/backend/rest/auth.py:141 src/backend/rest/auth.py:167
#: src/backend/rest/auth.py:200 src/backend/rest/auth.py:239
#: src/backend/rest/auth.py:258 src/backend/rest/config.py:30
#: src/backend/rest/config.py:40 src/backend/rest/config.py:61
#: src/backend/rest/config.py:73 src/backend/rest/config.py:84
#: src/backend/rest/config.py:105 src/backend/rest/config.py:125
#: src/backend/rest/config.py:135 src/backend/rest/config.py:163
#: src/backend/rest/config.py:182 src/backend/rest/config.py:205
#: src/backend/rest/config.py:229 src/backend/rest/custom_fields.py:32
#: src/backend/rest/custom_fields.py:54 src/backend/rest/custom_fields.py:65
#: src/backend/rest/custom_fields.py:76 src/backend/rest/custom_fields.py:86
#: src/backend/rest/doctypes.py:31 src/backend/rest/doctypes.py:47
#: src/backend/rest/doctypes.py:58 src/backend/rest/doctypes.py:69
#: src/backend/rest/doctypes.py:80 src/backend/rest/doctypes.py:90
#: src/backend/rest/doctypes.py:101 src/backend/rest/doctypes.py:116
#: src/backend/rest/forms.py:34 src/backend/rest/forms.py:62
#: src/backend/rest/forms.py:74 src/backend/rest/forms.py:120
#: src/backend/rest/forms.py:143 src/backend/rest/forms.py:164
#: src/backend/rest/forms.py:184 src/backend/rest/forms.py:210
#: src/backend/rest/forms.py:221 src/backend/rest/forms.py:232
#: src/backend/rest/forms.py:243 src/backend/rest/forms.py:255
#: src/backend/rest/history.py:54 src/backend/rest/history.py:79
#: src/backend/rest/history.py:99 src/backend/rest/history.py:109
#: src/backend/rest/locale.py:31 src/backend/rest/mailcollect.py:30
#: src/backend/rest/mailcollect.py:40 src/backend/rest/mailcollect.py:72
#: src/backend/rest/mailcollect.py:101 src/backend/rest/mailcollect.py:122
#: src/backend/rest/mailcollect.py:152 src/backend/rest/mailcollect.py:163
#: src/backend/rest/mailcollect.py:174 src/backend/rest/monitoring.py:30
#: src/backend/rest/monitoring.py:40 src/backend/rest/monitoring.py:50
#: src/backend/rest/monitoring.py:61 src/backend/rest/monitoring.py:95
#: src/backend/rest/outputs.py:32 src/backend/rest/outputs.py:55
#: src/backend/rest/outputs.py:74 src/backend/rest/outputs.py:86
#: src/backend/rest/outputs.py:98 src/backend/rest/outputs.py:124
#: src/backend/rest/outputs.py:136 src/backend/rest/outputs.py:161
#: src/backend/rest/outputs.py:172 src/backend/rest/positions_masks.py:33
#: src/backend/rest/positions_masks.py:53
#: src/backend/rest/positions_masks.py:74
#: src/backend/rest/positions_masks.py:85
#: src/backend/rest/positions_masks.py:109
#: src/backend/rest/positions_masks.py:120
#: src/backend/rest/positions_masks.py:131
#: src/backend/rest/positions_masks.py:142
#: src/backend/rest/positions_masks.py:153
#: src/backend/rest/positions_masks.py:164
#: src/backend/rest/positions_masks.py:175
#: src/backend/rest/positions_masks.py:186 src/backend/rest/privileges.py:29
#: src/backend/rest/privileges.py:39 src/backend/rest/roles.py:55
#: src/backend/rest/roles.py:65 src/backend/rest/roles.py:87
#: src/backend/rest/roles.py:106 src/backend/rest/roles.py:116
#: src/backend/rest/roles.py:126 src/backend/rest/roles.py:136
#: src/backend/rest/splitter.py:31 src/backend/rest/splitter.py:58
#: src/backend/rest/splitter.py:67 src/backend/rest/splitter.py:86
#: src/backend/rest/splitter.py:96 src/backend/rest/splitter.py:107
#: src/backend/rest/splitter.py:128 src/backend/rest/splitter.py:148
#: src/backend/rest/splitter.py:159 src/backend/rest/splitter.py:169
#: src/backend/rest/splitter.py:193 src/backend/rest/splitter.py:207
#: src/backend/rest/splitter.py:218 src/backend/rest/splitter.py:229
#: src/backend/rest/splitter.py:240 src/backend/rest/splitter.py:251
#: src/backend/rest/splitter.py:270 src/backend/rest/splitter.py:281
#: src/backend/rest/splitter.py:296 src/backend/rest/splitter.py:299
#: src/backend/rest/splitter.py:317 src/backend/rest/splitter.py:329
#: src/backend/rest/splitter.py:340 src/backend/rest/splitter.py:351
#: src/backend/rest/splitter.py:361 src/backend/rest/splitter.py:372
#: src/backend/rest/status.py:33 src/backend/rest/user.py:31
#: src/backend/rest/user.py:59 src/backend/rest/user.py:102
#: src/backend/rest/user.py:124 src/backend/rest/user.py:135
#: src/backend/rest/user.py:196 src/backend/rest/user.py:223
#: src/backend/rest/user.py:233 src/backend/rest/user.py:243
#: src/backend/rest/user.py:260 src/backend/rest/user.py:280
#: src/backend/rest/user.py:290 src/backend/rest/user.py:310
#: src/backend/rest/user.py:325 src/backend/rest/verifier.py:45
#: src/backend/rest/verifier.py:110 src/backend/rest/verifier.py:121
#: src/backend/rest/verifier.py:151 src/backend/rest/verifier.py:179
#: src/backend/rest/verifier.py:191 src/backend/rest/verifier.py:202
#: src/backend/rest/verifier.py:214 src/backend/rest/verifier.py:226
#: src/backend/rest/verifier.py:251 src/backend/rest/verifier.py:276
#: src/backend/rest/verifier.py:301 src/backend/rest/verifier.py:324
#: src/backend/rest/verifier.py:346 src/backend/rest/verifier.py:368
#: src/backend/rest/verifier.py:390 src/backend/rest/verifier.py:401
#: src/backend/rest/verifier.py:430 src/backend/rest/verifier.py:459
#: src/backend/rest/verifier.py:489 src/backend/rest/verifier.py:500
#: src/backend/rest/verifier.py:512 src/backend/rest/verifier.py:549
#: src/backend/rest/verifier.py:585 src/backend/rest/verifier.py:606
#: src/backend/rest/verifier.py:620 src/backend/rest/verifier.py:631
#: src/backend/rest/verifier.py:653 src/backend/rest/verifier.py:675
#: src/backend/rest/verifier.py:695 src/backend/rest/verifier.py:708
#: src/backend/rest/verifier.py:719 src/backend/rest/verifier.py:740
#: src/backend/rest/workflow.py:32 src/backend/rest/workflow.py:54
#: src/backend/rest/workflow.py:84 src/backend/rest/workflow.py:110
#: src/backend/rest/workflow.py:122 src/backend/rest/workflow.py:134
#: src/backend/rest/workflow.py:146 src/backend/rest/workflow.py:158
#: src/backend/rest/workflow.py:186 src/backend/rest/workflow.py:210
#: src/backend/rest/workflow.py:221
msgid "UNAUTHORIZED_ROUTE"
msgstr "Vous n'êtes pas autorisé à accéder à cette route"

#: src/backend/rest/accounts.py:45 src/backend/rest/accounts.py:121
#: src/backend/rest/accounts.py:143 src/backend/rest/accounts.py:165
#: src/backend/rest/accounts.py:192 src/backend/rest/accounts.py:218
#: src/backend/rest/accounts.py:244 src/backend/rest/accounts.py:297
#: src/backend/rest/accounts.py:341 src/backend/rest/accounts.py:370
#: src/backend/rest/accounts.py:411 src/backend/rest/accounts.py:448
#: src/backend/rest/accounts.py:473 src/backend/rest/accounts.py:590
#: src/backend/rest/attachments.py:38 src/backend/rest/attachments.py:57
#: src/backend/rest/auth.py:37 src/backend/rest/auth.py:55
#: src/backend/rest/auth.py:70 src/backend/rest/auth.py:91
#: src/backend/rest/auth.py:111 src/backend/rest/auth.py:155
#: src/backend/rest/auth.py:188 src/backend/rest/auth.py:221
#: src/backend/rest/auth.py:246 src/backend/rest/auth.py:265
#: src/backend/rest/config.py:49 src/backend/rest/config.py:93
#: src/backend/rest/config.py:114 src/backend/rest/config.py:145
#: src/backend/rest/config.py:170 src/backend/rest/config.py:193
#: src/backend/rest/config.py:217 src/backend/rest/config.py:240
#: src/backend/rest/coog.py:37 src/backend/rest/forms.py:46
#: src/backend/rest/forms.py:86 src/backend/rest/forms.py:131
#: src/backend/rest/forms.py:152 src/backend/rest/forms.py:172
#: src/backend/rest/forms.py:197 src/backend/rest/forms.py:268
#: src/backend/rest/history.py:40 src/backend/rest/history.py:67
#: src/backend/rest/history.py:87 src/backend/rest/mailcollect.py:60
#: src/backend/rest/mailcollect.py:89 src/backend/rest/mailcollect.py:110
#: src/backend/rest/mailcollect.py:140 src/backend/rest/mem.py:37
#: src/backend/rest/mem.py:56 src/backend/rest/mem.py:75
#: src/backend/rest/mem.py:94 src/backend/rest/mem.py:113
#: src/backend/rest/mem.py:132 src/backend/rest/mem.py:151
#: src/backend/rest/mem.py:170 src/backend/rest/mem.py:189
#: src/backend/rest/mem.py:214 src/backend/rest/monitoring.py:70
#: src/backend/rest/monitoring.py:103 src/backend/rest/opencaptureformem.py:37
#: src/backend/rest/opencaptureformem.py:55 src/backend/rest/opencrm.py:37
#: src/backend/rest/outputs.py:40 src/backend/rest/outputs.py:111
#: src/backend/rest/outputs.py:148 src/backend/rest/outputs.py:180
#: src/backend/rest/positions_masks.py:41
#: src/backend/rest/positions_masks.py:62
#: src/backend/rest/positions_masks.py:97 src/backend/rest/roles.py:37
#: src/backend/rest/roles.py:75 src/backend/rest/roles.py:94
#: src/backend/rest/roles.py:145 src/backend/rest/smtp.py:39
#: src/backend/rest/splitter.py:75 src/backend/rest/splitter.py:116
#: src/backend/rest/splitter.py:136 src/backend/rest/splitter.py:181
#: src/backend/rest/status.py:44 src/backend/rest/user.py:47
#: src/backend/rest/user.py:70 src/backend/rest/user.py:112
#: src/backend/rest/user.py:150 src/backend/rest/user.py:167
#: src/backend/rest/user.py:183 src/backend/rest/user.py:211
#: src/backend/rest/user.py:268 src/backend/rest/user.py:298
#: src/backend/rest/user.py:335 src/backend/rest/verifier.py:58
#: src/backend/rest/verifier.py:138 src/backend/rest/verifier.py:166
#: src/backend/rest/verifier.py:238 src/backend/rest/verifier.py:263
#: src/backend/rest/verifier.py:288 src/backend/rest/verifier.py:311
#: src/backend/rest/verifier.py:334 src/backend/rest/verifier.py:356
#: src/backend/rest/verifier.py:378 src/backend/rest/verifier.py:411
#: src/backend/rest/verifier.py:440 src/backend/rest/verifier.py:469
#: src/backend/rest/verifier.py:525 src/backend/rest/verifier.py:560
#: src/backend/rest/verifier.py:593 src/backend/rest/verifier.py:640
#: src/backend/rest/verifier.py:662 src/backend/rest/verifier.py:683
#: src/backend/rest/verifier.py:728 src/backend/rest/workflow.py:41
#: src/backend/rest/workflow.py:69 src/backend/rest/workflow.py:92
#: src/backend/rest/workflow.py:173 src/backend/rest/workflow.py:198
#: src/backend/rest/workflow.py:228
msgid "BAD_REQUEST"
msgstr "Erreur de requête"

#: src/backend/rest/attachments.py:90 src/backend/rest/attachments.py:101
#: src/backend/rest/verifier.py:611
msgid "DOWNLOAD_FILE"
msgstr "Téléchargement du fichier"

#: src/backend/rest/verifier.py:98
msgid "UNIQUE_URL_TOKEN_GENERATION_ERROR"
msgstr "Erreur lors de la génération du token de l'URL unique"

#: src/backend/rest/verifier.py:99
msgid "INTERFACE_IS_NOT_USED_OR_FORM_UNIQUE_URL_NOT_SET"
msgstr ""
"L'utilisation de l'interface est désactivée dans le workflow ou l'URL "
"unique n'est pas configurée correctement"
